/*
 * This file is generated by jOOQ.
*/
package models.public_;


import javax.annotation.Generated;

import models.public_.tables.BasConsultations;
import models.public_.tables.BasExamens;
import models.public_.tables.BasMedicaments;
import models.public_.tables.BasSoins;
import models.public_.tables.Consultations;
import models.public_.tables.Examens;
import models.public_.tables.Factures;
import models.public_.tables.FacturesDetails;
import models.public_.tables.InfosMedicale;
import models.public_.tables.MedecinPatient;
import models.public_.tables.Ordonances;
import models.public_.tables.Params;
import models.public_.tables.Partenaire;
import models.public_.tables.Patients;
import models.public_.tables.Personnels;
import models.public_.tables.Rendezvous;
import models.public_.tables.TypeConsultation;
import models.public_.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BAS_SONSULTATIONS_PKEY = Indexes0.BAS_SONSULTATIONS_PKEY;
    public static final Index BAS_EXAMENS_PKEY = Indexes0.BAS_EXAMENS_PKEY;
    public static final Index BAS_MEDICAMENTS_PKEY = Indexes0.BAS_MEDICAMENTS_PKEY;
    public static final Index BAS_SOIN_PK = Indexes0.BAS_SOIN_PK;
    public static final Index CONSULTATIONS_PKEY = Indexes0.CONSULTATIONS_PKEY;
    public static final Index EXAMENS_PKEY = Indexes0.EXAMENS_PKEY;
    public static final Index FACTURES_PKEY = Indexes0.FACTURES_PKEY;
    public static final Index NUM_FACT_UNIQUE = Indexes0.NUM_FACT_UNIQUE;
    public static final Index FACTURES_DETAILS_PKEY = Indexes0.FACTURES_DETAILS_PKEY;
    public static final Index INFOS_MEDICALE_PKEY = Indexes0.INFOS_MEDICALE_PKEY;
    public static final Index MEDECIN_PATIENT_PKEY = Indexes0.MEDECIN_PATIENT_PKEY;
    public static final Index ORDONANCES_PKEY = Indexes0.ORDONANCES_PKEY;
    public static final Index PARAMS_PKEY = Indexes0.PARAMS_PKEY;
    public static final Index PARTENAIRE_PKEY = Indexes0.PARTENAIRE_PKEY;
    public static final Index PATIENTS_PKEY = Indexes0.PATIENTS_PKEY;
    public static final Index PERSONNELS_PKEY = Indexes0.PERSONNELS_PKEY;
    public static final Index RENDEZVOUS_PKEY = Indexes0.RENDEZVOUS_PKEY;
    public static final Index TYPE_CONSULTATION_PKEY = Indexes0.TYPE_CONSULTATION_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index BAS_SONSULTATIONS_PKEY = createIndex("bas_sonsultations_pkey", BasConsultations.BAS_CONSULTATIONS, new OrderField[] { BasConsultations.BAS_CONSULTATIONS.ID }, true);
        public static Index BAS_EXAMENS_PKEY = createIndex("bas_examens_pkey", BasExamens.BAS_EXAMENS, new OrderField[] { BasExamens.BAS_EXAMENS.ID }, true);
        public static Index BAS_MEDICAMENTS_PKEY = createIndex("bas_medicaments_pkey", BasMedicaments.BAS_MEDICAMENTS, new OrderField[] { BasMedicaments.BAS_MEDICAMENTS.ID }, true);
        public static Index BAS_SOIN_PK = createIndex("bas_soin_pk", BasSoins.BAS_SOINS, new OrderField[] { BasSoins.BAS_SOINS.ID }, true);
        public static Index CONSULTATIONS_PKEY = createIndex("consultations_pkey", Consultations.CONSULTATIONS, new OrderField[] { Consultations.CONSULTATIONS.ID }, true);
        public static Index EXAMENS_PKEY = createIndex("examens_pkey", Examens.EXAMENS, new OrderField[] { Examens.EXAMENS.ID }, true);
        public static Index FACTURES_PKEY = createIndex("factures_pkey", Factures.FACTURES, new OrderField[] { Factures.FACTURES.ID }, true);
        public static Index NUM_FACT_UNIQUE = createIndex("num_fact_unique", Factures.FACTURES, new OrderField[] { Factures.FACTURES.NUM_FACT }, true);
        public static Index FACTURES_DETAILS_PKEY = createIndex("factures_details_pkey", FacturesDetails.FACTURES_DETAILS, new OrderField[] { FacturesDetails.FACTURES_DETAILS.ID }, true);
        public static Index INFOS_MEDICALE_PKEY = createIndex("infos_medicale_pkey", InfosMedicale.INFOS_MEDICALE, new OrderField[] { InfosMedicale.INFOS_MEDICALE.ID }, true);
        public static Index MEDECIN_PATIENT_PKEY = createIndex("medecin_patient_pkey", MedecinPatient.MEDECIN_PATIENT, new OrderField[] { MedecinPatient.MEDECIN_PATIENT.ID }, true);
        public static Index ORDONANCES_PKEY = createIndex("ordonances_pkey", Ordonances.ORDONANCES, new OrderField[] { Ordonances.ORDONANCES.ID }, true);
        public static Index PARAMS_PKEY = createIndex("params_pkey", Params.PARAMS, new OrderField[] { Params.PARAMS.ID }, true);
        public static Index PARTENAIRE_PKEY = createIndex("partenaire_pkey", Partenaire.PARTENAIRE, new OrderField[] { Partenaire.PARTENAIRE.ID }, true);
        public static Index PATIENTS_PKEY = createIndex("patients_pkey", Patients.PATIENTS, new OrderField[] { Patients.PATIENTS.ID }, true);
        public static Index PERSONNELS_PKEY = createIndex("personnels_pkey", Personnels.PERSONNELS, new OrderField[] { Personnels.PERSONNELS.ID }, true);
        public static Index RENDEZVOUS_PKEY = createIndex("rendezvous_pkey", Rendezvous.RENDEZVOUS, new OrderField[] { Rendezvous.RENDEZVOUS.ID_RDV }, true);
        public static Index TYPE_CONSULTATION_PKEY = createIndex("type_consultation_pkey", TypeConsultation.TYPE_CONSULTATION, new OrderField[] { TypeConsultation.TYPE_CONSULTATION.ID }, true);
        public static Index USERS_PKEY = createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.LOGIN }, true);
    }
}
