/*
 * This file is generated by jOOQ.
*/
package models.public_;


import javax.annotation.Generated;

import models.public_.tables.BasConsultations;
import models.public_.tables.BasExamens;
import models.public_.tables.BasMedicaments;
import models.public_.tables.BasSoins;
import models.public_.tables.Consultations;
import models.public_.tables.Examens;
import models.public_.tables.Factures;
import models.public_.tables.FacturesDetails;
import models.public_.tables.InfosMedicale;
import models.public_.tables.MedecinPatient;
import models.public_.tables.Ordonances;
import models.public_.tables.Params;
import models.public_.tables.Partenaire;
import models.public_.tables.Patients;
import models.public_.tables.Personnels;
import models.public_.tables.Rendezvous;
import models.public_.tables.TypeConsultation;
import models.public_.tables.Users;
import models.public_.tables.records.BasConsultationsRecord;
import models.public_.tables.records.BasExamensRecord;
import models.public_.tables.records.BasMedicamentsRecord;
import models.public_.tables.records.BasSoinsRecord;
import models.public_.tables.records.ConsultationsRecord;
import models.public_.tables.records.ExamensRecord;
import models.public_.tables.records.FacturesDetailsRecord;
import models.public_.tables.records.FacturesRecord;
import models.public_.tables.records.InfosMedicaleRecord;
import models.public_.tables.records.MedecinPatientRecord;
import models.public_.tables.records.OrdonancesRecord;
import models.public_.tables.records.ParamsRecord;
import models.public_.tables.records.PartenaireRecord;
import models.public_.tables.records.PatientsRecord;
import models.public_.tables.records.PersonnelsRecord;
import models.public_.tables.records.RendezvousRecord;
import models.public_.tables.records.TypeConsultationRecord;
import models.public_.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BasConsultationsRecord, Long> IDENTITY_BAS_CONSULTATIONS = Identities0.IDENTITY_BAS_CONSULTATIONS;
    public static final Identity<BasExamensRecord, Long> IDENTITY_BAS_EXAMENS = Identities0.IDENTITY_BAS_EXAMENS;
    public static final Identity<BasMedicamentsRecord, Long> IDENTITY_BAS_MEDICAMENTS = Identities0.IDENTITY_BAS_MEDICAMENTS;
    public static final Identity<BasSoinsRecord, Long> IDENTITY_BAS_SOINS = Identities0.IDENTITY_BAS_SOINS;
    public static final Identity<ConsultationsRecord, Long> IDENTITY_CONSULTATIONS = Identities0.IDENTITY_CONSULTATIONS;
    public static final Identity<ExamensRecord, Long> IDENTITY_EXAMENS = Identities0.IDENTITY_EXAMENS;
    public static final Identity<FacturesRecord, Long> IDENTITY_FACTURES = Identities0.IDENTITY_FACTURES;
    public static final Identity<FacturesDetailsRecord, Long> IDENTITY_FACTURES_DETAILS = Identities0.IDENTITY_FACTURES_DETAILS;
    public static final Identity<InfosMedicaleRecord, Long> IDENTITY_INFOS_MEDICALE = Identities0.IDENTITY_INFOS_MEDICALE;
    public static final Identity<MedecinPatientRecord, Long> IDENTITY_MEDECIN_PATIENT = Identities0.IDENTITY_MEDECIN_PATIENT;
    public static final Identity<OrdonancesRecord, Long> IDENTITY_ORDONANCES = Identities0.IDENTITY_ORDONANCES;
    public static final Identity<ParamsRecord, Long> IDENTITY_PARAMS = Identities0.IDENTITY_PARAMS;
    public static final Identity<PartenaireRecord, Long> IDENTITY_PARTENAIRE = Identities0.IDENTITY_PARTENAIRE;
    public static final Identity<PatientsRecord, Long> IDENTITY_PATIENTS = Identities0.IDENTITY_PATIENTS;
    public static final Identity<PersonnelsRecord, Long> IDENTITY_PERSONNELS = Identities0.IDENTITY_PERSONNELS;
    public static final Identity<RendezvousRecord, Long> IDENTITY_RENDEZVOUS = Identities0.IDENTITY_RENDEZVOUS;
    public static final Identity<TypeConsultationRecord, Long> IDENTITY_TYPE_CONSULTATION = Identities0.IDENTITY_TYPE_CONSULTATION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BasConsultationsRecord> BAS_SONSULTATIONS_PKEY = UniqueKeys0.BAS_SONSULTATIONS_PKEY;
    public static final UniqueKey<BasExamensRecord> BAS_EXAMENS_PKEY = UniqueKeys0.BAS_EXAMENS_PKEY;
    public static final UniqueKey<BasMedicamentsRecord> BAS_MEDICAMENTS_PKEY = UniqueKeys0.BAS_MEDICAMENTS_PKEY;
    public static final UniqueKey<BasSoinsRecord> BAS_SOIN_PK = UniqueKeys0.BAS_SOIN_PK;
    public static final UniqueKey<ConsultationsRecord> CONSULTATIONS_PKEY = UniqueKeys0.CONSULTATIONS_PKEY;
    public static final UniqueKey<ExamensRecord> EXAMENS_PKEY = UniqueKeys0.EXAMENS_PKEY;
    public static final UniqueKey<FacturesRecord> FACTURES_PKEY = UniqueKeys0.FACTURES_PKEY;
    public static final UniqueKey<FacturesRecord> NUM_FACT_UNIQUE = UniqueKeys0.NUM_FACT_UNIQUE;
    public static final UniqueKey<FacturesDetailsRecord> FACTURES_DETAILS_PKEY = UniqueKeys0.FACTURES_DETAILS_PKEY;
    public static final UniqueKey<InfosMedicaleRecord> INFOS_MEDICALE_PKEY = UniqueKeys0.INFOS_MEDICALE_PKEY;
    public static final UniqueKey<MedecinPatientRecord> MEDECIN_PATIENT_PKEY = UniqueKeys0.MEDECIN_PATIENT_PKEY;
    public static final UniqueKey<OrdonancesRecord> ORDONANCES_PKEY = UniqueKeys0.ORDONANCES_PKEY;
    public static final UniqueKey<ParamsRecord> PARAMS_PKEY = UniqueKeys0.PARAMS_PKEY;
    public static final UniqueKey<PartenaireRecord> PARTENAIRE_PKEY = UniqueKeys0.PARTENAIRE_PKEY;
    public static final UniqueKey<PatientsRecord> PATIENTS_PKEY = UniqueKeys0.PATIENTS_PKEY;
    public static final UniqueKey<PersonnelsRecord> PERSONNELS_PKEY = UniqueKeys0.PERSONNELS_PKEY;
    public static final UniqueKey<RendezvousRecord> RENDEZVOUS_PKEY = UniqueKeys0.RENDEZVOUS_PKEY;
    public static final UniqueKey<TypeConsultationRecord> TYPE_CONSULTATION_PKEY = UniqueKeys0.TYPE_CONSULTATION_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ConsultationsRecord, TypeConsultationRecord> CONSULTATIONS__TYPE_CONSULTATION_FKP = ForeignKeys0.CONSULTATIONS__TYPE_CONSULTATION_FKP;
    public static final ForeignKey<ConsultationsRecord, PatientsRecord> CONSULTATIONS__PATIENT_FKP = ForeignKeys0.CONSULTATIONS__PATIENT_FKP;
    public static final ForeignKey<ExamensRecord, ConsultationsRecord> EXAMENS__CONSULTATION_FKP = ForeignKeys0.EXAMENS__CONSULTATION_FKP;
    public static final ForeignKey<FacturesDetailsRecord, FacturesRecord> FACTURES_DETAILS__FKK_FACTURE = ForeignKeys0.FACTURES_DETAILS__FKK_FACTURE;
    public static final ForeignKey<InfosMedicaleRecord, PatientsRecord> INFOS_MEDICALE__PATIENT_FKY = ForeignKeys0.INFOS_MEDICALE__PATIENT_FKY;
    public static final ForeignKey<MedecinPatientRecord, PatientsRecord> MEDECIN_PATIENT__FK_PAT = ForeignKeys0.MEDECIN_PATIENT__FK_PAT;
    public static final ForeignKey<MedecinPatientRecord, PersonnelsRecord> MEDECIN_PATIENT__FK_MEDECIN = ForeignKeys0.MEDECIN_PATIENT__FK_MEDECIN;
    public static final ForeignKey<OrdonancesRecord, ConsultationsRecord> ORDONANCES__CONSULTATION_ORDONANCE_FKP = ForeignKeys0.ORDONANCES__CONSULTATION_ORDONANCE_FKP;
    public static final ForeignKey<PatientsRecord, PartenaireRecord> PATIENTS__PARTN_FRK = ForeignKeys0.PATIENTS__PARTN_FRK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BasConsultationsRecord, Long> IDENTITY_BAS_CONSULTATIONS = createIdentity(BasConsultations.BAS_CONSULTATIONS, BasConsultations.BAS_CONSULTATIONS.ID);
        public static Identity<BasExamensRecord, Long> IDENTITY_BAS_EXAMENS = createIdentity(BasExamens.BAS_EXAMENS, BasExamens.BAS_EXAMENS.ID);
        public static Identity<BasMedicamentsRecord, Long> IDENTITY_BAS_MEDICAMENTS = createIdentity(BasMedicaments.BAS_MEDICAMENTS, BasMedicaments.BAS_MEDICAMENTS.ID);
        public static Identity<BasSoinsRecord, Long> IDENTITY_BAS_SOINS = createIdentity(BasSoins.BAS_SOINS, BasSoins.BAS_SOINS.ID);
        public static Identity<ConsultationsRecord, Long> IDENTITY_CONSULTATIONS = createIdentity(Consultations.CONSULTATIONS, Consultations.CONSULTATIONS.ID);
        public static Identity<ExamensRecord, Long> IDENTITY_EXAMENS = createIdentity(Examens.EXAMENS, Examens.EXAMENS.ID);
        public static Identity<FacturesRecord, Long> IDENTITY_FACTURES = createIdentity(Factures.FACTURES, Factures.FACTURES.ID);
        public static Identity<FacturesDetailsRecord, Long> IDENTITY_FACTURES_DETAILS = createIdentity(FacturesDetails.FACTURES_DETAILS, FacturesDetails.FACTURES_DETAILS.ID);
        public static Identity<InfosMedicaleRecord, Long> IDENTITY_INFOS_MEDICALE = createIdentity(InfosMedicale.INFOS_MEDICALE, InfosMedicale.INFOS_MEDICALE.ID);
        public static Identity<MedecinPatientRecord, Long> IDENTITY_MEDECIN_PATIENT = createIdentity(MedecinPatient.MEDECIN_PATIENT, MedecinPatient.MEDECIN_PATIENT.ID);
        public static Identity<OrdonancesRecord, Long> IDENTITY_ORDONANCES = createIdentity(Ordonances.ORDONANCES, Ordonances.ORDONANCES.ID);
        public static Identity<ParamsRecord, Long> IDENTITY_PARAMS = createIdentity(Params.PARAMS, Params.PARAMS.ID);
        public static Identity<PartenaireRecord, Long> IDENTITY_PARTENAIRE = createIdentity(Partenaire.PARTENAIRE, Partenaire.PARTENAIRE.ID);
        public static Identity<PatientsRecord, Long> IDENTITY_PATIENTS = createIdentity(Patients.PATIENTS, Patients.PATIENTS.ID);
        public static Identity<PersonnelsRecord, Long> IDENTITY_PERSONNELS = createIdentity(Personnels.PERSONNELS, Personnels.PERSONNELS.ID);
        public static Identity<RendezvousRecord, Long> IDENTITY_RENDEZVOUS = createIdentity(Rendezvous.RENDEZVOUS, Rendezvous.RENDEZVOUS.ID_RDV);
        public static Identity<TypeConsultationRecord, Long> IDENTITY_TYPE_CONSULTATION = createIdentity(TypeConsultation.TYPE_CONSULTATION, TypeConsultation.TYPE_CONSULTATION.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BasConsultationsRecord> BAS_SONSULTATIONS_PKEY = createUniqueKey(BasConsultations.BAS_CONSULTATIONS, "bas_sonsultations_pkey", BasConsultations.BAS_CONSULTATIONS.ID);
        public static final UniqueKey<BasExamensRecord> BAS_EXAMENS_PKEY = createUniqueKey(BasExamens.BAS_EXAMENS, "bas_examens_pkey", BasExamens.BAS_EXAMENS.ID);
        public static final UniqueKey<BasMedicamentsRecord> BAS_MEDICAMENTS_PKEY = createUniqueKey(BasMedicaments.BAS_MEDICAMENTS, "bas_medicaments_pkey", BasMedicaments.BAS_MEDICAMENTS.ID);
        public static final UniqueKey<BasSoinsRecord> BAS_SOIN_PK = createUniqueKey(BasSoins.BAS_SOINS, "bas_soin_pk", BasSoins.BAS_SOINS.ID);
        public static final UniqueKey<ConsultationsRecord> CONSULTATIONS_PKEY = createUniqueKey(Consultations.CONSULTATIONS, "consultations_pkey", Consultations.CONSULTATIONS.ID);
        public static final UniqueKey<ExamensRecord> EXAMENS_PKEY = createUniqueKey(Examens.EXAMENS, "examens_pkey", Examens.EXAMENS.ID);
        public static final UniqueKey<FacturesRecord> FACTURES_PKEY = createUniqueKey(Factures.FACTURES, "factures_pkey", Factures.FACTURES.ID);
        public static final UniqueKey<FacturesRecord> NUM_FACT_UNIQUE = createUniqueKey(Factures.FACTURES, "num_fact_unique", Factures.FACTURES.NUM_FACT);
        public static final UniqueKey<FacturesDetailsRecord> FACTURES_DETAILS_PKEY = createUniqueKey(FacturesDetails.FACTURES_DETAILS, "factures_details_pkey", FacturesDetails.FACTURES_DETAILS.ID);
        public static final UniqueKey<InfosMedicaleRecord> INFOS_MEDICALE_PKEY = createUniqueKey(InfosMedicale.INFOS_MEDICALE, "infos_medicale_pkey", InfosMedicale.INFOS_MEDICALE.ID);
        public static final UniqueKey<MedecinPatientRecord> MEDECIN_PATIENT_PKEY = createUniqueKey(MedecinPatient.MEDECIN_PATIENT, "medecin_patient_pkey", MedecinPatient.MEDECIN_PATIENT.ID);
        public static final UniqueKey<OrdonancesRecord> ORDONANCES_PKEY = createUniqueKey(Ordonances.ORDONANCES, "ordonances_pkey", Ordonances.ORDONANCES.ID);
        public static final UniqueKey<ParamsRecord> PARAMS_PKEY = createUniqueKey(Params.PARAMS, "params_pkey", Params.PARAMS.ID);
        public static final UniqueKey<PartenaireRecord> PARTENAIRE_PKEY = createUniqueKey(Partenaire.PARTENAIRE, "partenaire_pkey", Partenaire.PARTENAIRE.ID);
        public static final UniqueKey<PatientsRecord> PATIENTS_PKEY = createUniqueKey(Patients.PATIENTS, "patients_pkey", Patients.PATIENTS.ID);
        public static final UniqueKey<PersonnelsRecord> PERSONNELS_PKEY = createUniqueKey(Personnels.PERSONNELS, "personnels_pkey", Personnels.PERSONNELS.ID);
        public static final UniqueKey<RendezvousRecord> RENDEZVOUS_PKEY = createUniqueKey(Rendezvous.RENDEZVOUS, "rendezvous_pkey", Rendezvous.RENDEZVOUS.ID_RDV);
        public static final UniqueKey<TypeConsultationRecord> TYPE_CONSULTATION_PKEY = createUniqueKey(TypeConsultation.TYPE_CONSULTATION, "type_consultation_pkey", TypeConsultation.TYPE_CONSULTATION.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = createUniqueKey(Users.USERS, "users_pkey", Users.USERS.LOGIN);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ConsultationsRecord, TypeConsultationRecord> CONSULTATIONS__TYPE_CONSULTATION_FKP = createForeignKey(models.public_.Keys.TYPE_CONSULTATION_PKEY, Consultations.CONSULTATIONS, "consultations__type_consultation_fkp", Consultations.CONSULTATIONS.TYPE_CONSULTATION);
        public static final ForeignKey<ConsultationsRecord, PatientsRecord> CONSULTATIONS__PATIENT_FKP = createForeignKey(models.public_.Keys.PATIENTS_PKEY, Consultations.CONSULTATIONS, "consultations__patient_fkp", Consultations.CONSULTATIONS.PATIENT);
        public static final ForeignKey<ExamensRecord, ConsultationsRecord> EXAMENS__CONSULTATION_FKP = createForeignKey(models.public_.Keys.CONSULTATIONS_PKEY, Examens.EXAMENS, "examens__consultation_fkp", Examens.EXAMENS.CONSULTATION);
        public static final ForeignKey<FacturesDetailsRecord, FacturesRecord> FACTURES_DETAILS__FKK_FACTURE = createForeignKey(models.public_.Keys.NUM_FACT_UNIQUE, FacturesDetails.FACTURES_DETAILS, "factures_details__fkk_facture", FacturesDetails.FACTURES_DETAILS.FACTURE);
        public static final ForeignKey<InfosMedicaleRecord, PatientsRecord> INFOS_MEDICALE__PATIENT_FKY = createForeignKey(models.public_.Keys.PATIENTS_PKEY, InfosMedicale.INFOS_MEDICALE, "infos_medicale__patient_fky", InfosMedicale.INFOS_MEDICALE.PATIENT);
        public static final ForeignKey<MedecinPatientRecord, PatientsRecord> MEDECIN_PATIENT__FK_PAT = createForeignKey(models.public_.Keys.PATIENTS_PKEY, MedecinPatient.MEDECIN_PATIENT, "medecin_patient__fk_pat", MedecinPatient.MEDECIN_PATIENT.PATIENT_ID);
        public static final ForeignKey<MedecinPatientRecord, PersonnelsRecord> MEDECIN_PATIENT__FK_MEDECIN = createForeignKey(models.public_.Keys.PERSONNELS_PKEY, MedecinPatient.MEDECIN_PATIENT, "medecin_patient__fk_medecin", MedecinPatient.MEDECIN_PATIENT.MEDECIN_ID);
        public static final ForeignKey<OrdonancesRecord, ConsultationsRecord> ORDONANCES__CONSULTATION_ORDONANCE_FKP = createForeignKey(models.public_.Keys.CONSULTATIONS_PKEY, Ordonances.ORDONANCES, "ordonances__consultation_ordonance_fkp", Ordonances.ORDONANCES.CONSULTATION);
        public static final ForeignKey<PatientsRecord, PartenaireRecord> PATIENTS__PARTN_FRK = createForeignKey(models.public_.Keys.PARTENAIRE_PKEY, Patients.PATIENTS, "patients__partn_frk", Patients.PATIENTS.PARTENAIRE);
    }
}
