/*
 * This file is generated by jOOQ.
*/
package models.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.bas_consultations_id_seq</code>
     */
    public static final Sequence<Long> BAS_CONSULTATIONS_ID_SEQ = new SequenceImpl<Long>("bas_consultations_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.bas_examens_id_seq</code>
     */
    public static final Sequence<Long> BAS_EXAMENS_ID_SEQ = new SequenceImpl<Long>("bas_examens_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.bas_medicaments_id_seq</code>
     */
    public static final Sequence<Long> BAS_MEDICAMENTS_ID_SEQ = new SequenceImpl<Long>("bas_medicaments_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.consultations_id_seq</code>
     */
    public static final Sequence<Long> CONSULTATIONS_ID_SEQ = new SequenceImpl<Long>("consultations_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.examens_id_seq</code>
     */
    public static final Sequence<Long> EXAMENS_ID_SEQ = new SequenceImpl<Long>("examens_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.infos_medicale_id_seq</code>
     */
    public static final Sequence<Long> INFOS_MEDICALE_ID_SEQ = new SequenceImpl<Long>("infos_medicale_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.medecin_patient_id_seq</code>
     */
    public static final Sequence<Long> MEDECIN_PATIENT_ID_SEQ = new SequenceImpl<Long>("medecin_patient_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.ordonances_id_seq</code>
     */
    public static final Sequence<Long> ORDONANCES_ID_SEQ = new SequenceImpl<Long>("ordonances_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.params_id_seq</code>
     */
    public static final Sequence<Long> PARAMS_ID_SEQ = new SequenceImpl<Long>("params_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.partenaire_id_seq</code>
     */
    public static final Sequence<Long> PARTENAIRE_ID_SEQ = new SequenceImpl<Long>("partenaire_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.patients_id_seq</code>
     */
    public static final Sequence<Long> PATIENTS_ID_SEQ = new SequenceImpl<Long>("patients_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.personnels_id_seq</code>
     */
    public static final Sequence<Long> PERSONNELS_ID_SEQ = new SequenceImpl<Long>("personnels_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.rendezvous_id_rdv_seq</code>
     */
    public static final Sequence<Long> RENDEZVOUS_ID_RDV_SEQ = new SequenceImpl<Long>("rendezvous_id_rdv_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.roles_id_role_seq</code>
     */
    public static final Sequence<Long> ROLES_ID_ROLE_SEQ = new SequenceImpl<Long>("roles_id_role_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.type_consultation_id_seq</code>
     */
    public static final Sequence<Long> TYPE_CONSULTATION_ID_SEQ = new SequenceImpl<Long>("type_consultation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
