/*
 * This file is generated by jOOQ.
*/
package models.public_;


import javax.annotation.Generated;

import models.public_.tables.BasConsultations;
import models.public_.tables.BasExamens;
import models.public_.tables.BasMedicaments;
import models.public_.tables.BasSoins;
import models.public_.tables.Consultations;
import models.public_.tables.Examens;
import models.public_.tables.InfosMedicale;
import models.public_.tables.MedecinPatient;
import models.public_.tables.Ordonances;
import models.public_.tables.Params;
import models.public_.tables.Partenaire;
import models.public_.tables.Patients;
import models.public_.tables.Personnels;
import models.public_.tables.SConsultations;
import models.public_.tables.TypeConsultation;
import models.public_.tables.Users;
import models.public_.tables.VConsultations;
import models.public_.tables.VExamens;
import models.public_.tables.VOrdononce;
import models.public_.tables.VPatients;
import models.public_.tables.VSoins;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bas_consultations</code>.
     */
    public static final BasConsultations BAS_CONSULTATIONS = models.public_.tables.BasConsultations.BAS_CONSULTATIONS;

    /**
     * The table <code>public.bas_examens</code>.
     */
    public static final BasExamens BAS_EXAMENS = models.public_.tables.BasExamens.BAS_EXAMENS;

    /**
     * The table <code>public.bas_medicaments</code>.
     */
    public static final BasMedicaments BAS_MEDICAMENTS = models.public_.tables.BasMedicaments.BAS_MEDICAMENTS;

    /**
     * The table <code>public.bas_soins</code>.
     */
    public static final BasSoins BAS_SOINS = models.public_.tables.BasSoins.BAS_SOINS;

    /**
     * The table <code>public.consultations</code>.
     */
    public static final Consultations CONSULTATIONS = models.public_.tables.Consultations.CONSULTATIONS;

    /**
     * The table <code>public.examens</code>.
     */
    public static final Examens EXAMENS = models.public_.tables.Examens.EXAMENS;

    /**
     * The table <code>public.infos_medicale</code>.
     */
    public static final InfosMedicale INFOS_MEDICALE = models.public_.tables.InfosMedicale.INFOS_MEDICALE;

    /**
     * The table <code>public.medecin_patient</code>.
     */
    public static final MedecinPatient MEDECIN_PATIENT = models.public_.tables.MedecinPatient.MEDECIN_PATIENT;

    /**
     * The table <code>public.ordonances</code>.
     */
    public static final Ordonances ORDONANCES = models.public_.tables.Ordonances.ORDONANCES;

    /**
     * The table <code>public.params</code>.
     */
    public static final Params PARAMS = models.public_.tables.Params.PARAMS;

    /**
     * The table <code>public.partenaire</code>.
     */
    public static final Partenaire PARTENAIRE = models.public_.tables.Partenaire.PARTENAIRE;

    /**
     * The table <code>public.patients</code>.
     */
    public static final Patients PATIENTS = models.public_.tables.Patients.PATIENTS;

    /**
     * The table <code>public.personnels</code>.
     */
    public static final Personnels PERSONNELS = models.public_.tables.Personnels.PERSONNELS;

    /**
     * The table <code>public.s_consultations</code>.
     */
    public static final SConsultations S_CONSULTATIONS = models.public_.tables.SConsultations.S_CONSULTATIONS;

    /**
     * The table <code>public.type_consultation</code>.
     */
    public static final TypeConsultation TYPE_CONSULTATION = models.public_.tables.TypeConsultation.TYPE_CONSULTATION;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = models.public_.tables.Users.USERS;

    /**
     * The table <code>public.v_consultations</code>.
     */
    public static final VConsultations V_CONSULTATIONS = models.public_.tables.VConsultations.V_CONSULTATIONS;

    /**
     * The table <code>public.v_examens</code>.
     */
    public static final VExamens V_EXAMENS = models.public_.tables.VExamens.V_EXAMENS;

    /**
     * The table <code>public.v_ordononce</code>.
     */
    public static final VOrdononce V_ORDONONCE = models.public_.tables.VOrdononce.V_ORDONONCE;

    /**
     * The table <code>public.v_patients</code>.
     */
    public static final VPatients V_PATIENTS = models.public_.tables.VPatients.V_PATIENTS;

    /**
     * The table <code>public.v_soins</code>.
     */
    public static final VSoins V_SOINS = models.public_.tables.VSoins.V_SOINS;
}
