/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.BasExamens;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasExamensRecord extends UpdatableRecordImpl<BasExamensRecord> implements Record7<Long, String, Long, Long, Boolean, Timestamp, String> {

    private static final long serialVersionUID = 696730954;

    /**
     * Setter for <code>public.bas_examens.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bas_examens.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bas_examens.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bas_examens.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bas_examens.prix_norm</code>.
     */
    public void setPrixNorm(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bas_examens.prix_norm</code>.
     */
    public Long getPrixNorm() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.bas_examens.prix_pcm</code>.
     */
    public void setPrixPcm(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bas_examens.prix_pcm</code>.
     */
    public Long getPrixPcm() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.bas_examens.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bas_examens.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.bas_examens.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bas_examens.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.bas_examens.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.bas_examens.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Long, Long, Boolean, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Long, Long, Boolean, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BasExamens.BAS_EXAMENS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BasExamens.BAS_EXAMENS.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return BasExamens.BAS_EXAMENS.PRIX_NORM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return BasExamens.BAS_EXAMENS.PRIX_PCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return BasExamens.BAS_EXAMENS.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return BasExamens.BAS_EXAMENS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BasExamens.BAS_EXAMENS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPrixNorm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getPrixPcm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPrixNorm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getPrixPcm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord value3(Long value) {
        setPrixNorm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord value4(Long value) {
        setPrixPcm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord value5(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord value6(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord value7(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BasExamensRecord values(Long value1, String value2, Long value3, Long value4, Boolean value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BasExamensRecord
     */
    public BasExamensRecord() {
        super(BasExamens.BAS_EXAMENS);
    }

    /**
     * Create a detached, initialised BasExamensRecord
     */
    public BasExamensRecord(Long id, String libelle, Long prixNorm, Long prixPcm, Boolean isDeleted, Timestamp whenDone, String whoDone) {
        super(BasExamens.BAS_EXAMENS);

        set(0, id);
        set(1, libelle);
        set(2, prixNorm);
        set(3, prixPcm);
        set(4, isDeleted);
        set(5, whenDone);
        set(6, whoDone);
    }
}
