/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.Consultations;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConsultationsRecord extends UpdatableRecordImpl<ConsultationsRecord> implements Record19<Long, Long, Long, String, Long, Long, Long, Boolean, Boolean, Timestamp, String, String, String, String, String, Timestamp, Double, Long, String> {

    private static final long serialVersionUID = 1755369245;

    /**
     * Setter for <code>public.consultations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.consultations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.consultations.type_consultation</code>.
     */
    public void setTypeConsultation(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.consultations.type_consultation</code>.
     */
    public Long getTypeConsultation() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.consultations.patient</code>.
     */
    public void setPatient(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.consultations.patient</code>.
     */
    public Long getPatient() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.consultations.tel_patient</code>.
     */
    public void setTelPatient(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.consultations.tel_patient</code>.
     */
    public String getTelPatient() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.consultations.cout</code>.
     */
    public void setCout(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.consultations.cout</code>.
     */
    public Long getCout() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.consultations.somme_recu</code>.
     */
    public void setSommeRecu(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.consultations.somme_recu</code>.
     */
    public Long getSommeRecu() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.consultations.somme_remise</code>.
     */
    public void setSommeRemise(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.consultations.somme_remise</code>.
     */
    public Long getSommeRemise() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.consultations.is_closed</code>.
     */
    public void setIsClosed(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.consultations.is_closed</code>.
     */
    public Boolean getIsClosed() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.consultations.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.consultations.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.consultations.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.consultations.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.consultations.numero_consul</code>.
     */
    public void setNumeroConsul(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.consultations.numero_consul</code>.
     */
    public String getNumeroConsul() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.consultations.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.consultations.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.consultations.nom_prenom_patient</code>.
     */
    public void setNomPrenomPatient(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.consultations.nom_prenom_patient</code>.
     */
    public String getNomPrenomPatient() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.consultations.montant_en_lettre</code>.
     */
    public void setMontantEnLettre(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.consultations.montant_en_lettre</code>.
     */
    public String getMontantEnLettre() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.consultations.observation</code>.
     */
    public void setObservation(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.consultations.observation</code>.
     */
    public String getObservation() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.consultations.date_rdv</code>.
     */
    public void setDateRdv(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.consultations.date_rdv</code>.
     */
    public Timestamp getDateRdv() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>public.consultations.taux_couverture</code>.
     */
    public void setTauxCouverture(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.consultations.taux_couverture</code>.
     */
    public Double getTauxCouverture() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.consultations.medecin_traitrant</code>.
     */
    public void setMedecinTraitrant(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.consultations.medecin_traitrant</code>.
     */
    public Long getMedecinTraitrant() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.consultations.structure_patient</code>.
     */
    public void setStructurePatient(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.consultations.structure_patient</code>.
     */
    public String getStructurePatient() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Long, Long, Long, String, Long, Long, Long, Boolean, Boolean, Timestamp, String, String, String, String, String, Timestamp, Double, Long, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Long, Long, Long, String, Long, Long, Long, Boolean, Boolean, Timestamp, String, String, String, String, String, Timestamp, Double, Long, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Consultations.CONSULTATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Consultations.CONSULTATIONS.TYPE_CONSULTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Consultations.CONSULTATIONS.PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Consultations.CONSULTATIONS.TEL_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Consultations.CONSULTATIONS.COUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Consultations.CONSULTATIONS.SOMME_RECU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Consultations.CONSULTATIONS.SOMME_REMISE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Consultations.CONSULTATIONS.IS_CLOSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Consultations.CONSULTATIONS.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Consultations.CONSULTATIONS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Consultations.CONSULTATIONS.NUMERO_CONSUL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Consultations.CONSULTATIONS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Consultations.CONSULTATIONS.NOM_PRENOM_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Consultations.CONSULTATIONS.MONTANT_EN_LETTRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Consultations.CONSULTATIONS.OBSERVATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return Consultations.CONSULTATIONS.DATE_RDV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field17() {
        return Consultations.CONSULTATIONS.TAUX_COUVERTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return Consultations.CONSULTATIONS.MEDECIN_TRAITRANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Consultations.CONSULTATIONS.STRUCTURE_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getTypeConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTelPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getCout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getSommeRecu();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getSommeRemise();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getIsClosed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getNumeroConsul();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getNomPrenomPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getMontantEnLettre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getObservation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getDateRdv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component17() {
        return getTauxCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component18() {
        return getMedecinTraitrant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getStructurePatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTypeConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getSommeRecu();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getSommeRemise();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getIsClosed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getNumeroConsul();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getNomPrenomPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getMontantEnLettre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getObservation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getDateRdv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value17() {
        return getTauxCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getMedecinTraitrant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getStructurePatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value2(Long value) {
        setTypeConsultation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value3(Long value) {
        setPatient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value4(String value) {
        setTelPatient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value5(Long value) {
        setCout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value6(Long value) {
        setSommeRecu(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value7(Long value) {
        setSommeRemise(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value8(Boolean value) {
        setIsClosed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value9(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value10(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value11(String value) {
        setNumeroConsul(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value12(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value13(String value) {
        setNomPrenomPatient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value14(String value) {
        setMontantEnLettre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value15(String value) {
        setObservation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value16(Timestamp value) {
        setDateRdv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value17(Double value) {
        setTauxCouverture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value18(Long value) {
        setMedecinTraitrant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord value19(String value) {
        setStructurePatient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsultationsRecord values(Long value1, Long value2, Long value3, String value4, Long value5, Long value6, Long value7, Boolean value8, Boolean value9, Timestamp value10, String value11, String value12, String value13, String value14, String value15, Timestamp value16, Double value17, Long value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsultationsRecord
     */
    public ConsultationsRecord() {
        super(Consultations.CONSULTATIONS);
    }

    /**
     * Create a detached, initialised ConsultationsRecord
     */
    public ConsultationsRecord(Long id, Long typeConsultation, Long patient, String telPatient, Long cout, Long sommeRecu, Long sommeRemise, Boolean isClosed, Boolean isDeleted, Timestamp whenDone, String numeroConsul, String whoDone, String nomPrenomPatient, String montantEnLettre, String observation, Timestamp dateRdv, Double tauxCouverture, Long medecinTraitrant, String structurePatient) {
        super(Consultations.CONSULTATIONS);

        set(0, id);
        set(1, typeConsultation);
        set(2, patient);
        set(3, telPatient);
        set(4, cout);
        set(5, sommeRecu);
        set(6, sommeRemise);
        set(7, isClosed);
        set(8, isDeleted);
        set(9, whenDone);
        set(10, numeroConsul);
        set(11, whoDone);
        set(12, nomPrenomPatient);
        set(13, montantEnLettre);
        set(14, observation);
        set(15, dateRdv);
        set(16, tauxCouverture);
        set(17, medecinTraitrant);
        set(18, structurePatient);
    }
}
