/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.FacturesDetails;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FacturesDetailsRecord extends UpdatableRecordImpl<FacturesDetailsRecord> implements Record10<Long, String, Long, Long, Long, Long, String, Timestamp, Boolean, String> {

    private static final long serialVersionUID = -1522032757;

    /**
     * Setter for <code>public.factures_details.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.factures_details.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.factures_details.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.factures_details.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.factures_details.quantie</code>.
     */
    public void setQuantie(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.factures_details.quantie</code>.
     */
    public Long getQuantie() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.factures_details.prix_unitaire</code>.
     */
    public void setPrixUnitaire(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.factures_details.prix_unitaire</code>.
     */
    public Long getPrixUnitaire() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.factures_details.taux_tva</code>.
     */
    public void setTauxTva(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.factures_details.taux_tva</code>.
     */
    public Long getTauxTva() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.factures_details.total_ttc</code>.
     */
    public void setTotalTtc(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.factures_details.total_ttc</code>.
     */
    public Long getTotalTtc() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.factures_details.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.factures_details.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.factures_details.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.factures_details.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.factures_details.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.factures_details.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.factures_details.facture</code>.
     */
    public void setFacture(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.factures_details.facture</code>.
     */
    public String getFacture() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, Long, Long, Long, Long, String, Timestamp, Boolean, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, Long, Long, Long, Long, String, Timestamp, Boolean, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return FacturesDetails.FACTURES_DETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FacturesDetails.FACTURES_DETAILS.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return FacturesDetails.FACTURES_DETAILS.QUANTIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return FacturesDetails.FACTURES_DETAILS.PRIX_UNITAIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return FacturesDetails.FACTURES_DETAILS.TAUX_TVA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return FacturesDetails.FACTURES_DETAILS.TOTAL_TTC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FacturesDetails.FACTURES_DETAILS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return FacturesDetails.FACTURES_DETAILS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return FacturesDetails.FACTURES_DETAILS.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return FacturesDetails.FACTURES_DETAILS.FACTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getQuantie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getPrixUnitaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getTauxTva();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getTotalTtc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getQuantie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getPrixUnitaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTauxTva();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getTotalTtc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value3(Long value) {
        setQuantie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value4(Long value) {
        setPrixUnitaire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value5(Long value) {
        setTauxTva(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value6(Long value) {
        setTotalTtc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value7(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value8(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value9(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord value10(String value) {
        setFacture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacturesDetailsRecord values(Long value1, String value2, Long value3, Long value4, Long value5, Long value6, String value7, Timestamp value8, Boolean value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FacturesDetailsRecord
     */
    public FacturesDetailsRecord() {
        super(FacturesDetails.FACTURES_DETAILS);
    }

    /**
     * Create a detached, initialised FacturesDetailsRecord
     */
    public FacturesDetailsRecord(Long id, String libelle, Long quantie, Long prixUnitaire, Long tauxTva, Long totalTtc, String whoDone, Timestamp whenDone, Boolean isDeleted, String facture) {
        super(FacturesDetails.FACTURES_DETAILS);

        set(0, id);
        set(1, libelle);
        set(2, quantie);
        set(3, prixUnitaire);
        set(4, tauxTva);
        set(5, totalTtc);
        set(6, whoDone);
        set(7, whenDone);
        set(8, isDeleted);
        set(9, facture);
    }
}
