/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import javax.annotation.Generated;

import models.public_.tables.MedecinPatient;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedecinPatientRecord extends UpdatableRecordImpl<MedecinPatientRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -762053850;

    /**
     * Setter for <code>public.medecin_patient.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.medecin_patient.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.medecin_patient.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.medecin_patient.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.medecin_patient.medecin_id</code>.
     */
    public void setMedecinId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.medecin_patient.medecin_id</code>.
     */
    public Long getMedecinId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MedecinPatient.MEDECIN_PATIENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MedecinPatient.MEDECIN_PATIENT.PATIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return MedecinPatient.MEDECIN_PATIENT.MEDECIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getMedecinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMedecinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MedecinPatientRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MedecinPatientRecord value2(Long value) {
        setPatientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MedecinPatientRecord value3(Long value) {
        setMedecinId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MedecinPatientRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedecinPatientRecord
     */
    public MedecinPatientRecord() {
        super(MedecinPatient.MEDECIN_PATIENT);
    }

    /**
     * Create a detached, initialised MedecinPatientRecord
     */
    public MedecinPatientRecord(Long id, Long patientId, Long medecinId) {
        super(MedecinPatient.MEDECIN_PATIENT);

        set(0, id);
        set(1, patientId);
        set(2, medecinId);
    }
}
