/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.Ordonances;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdonancesRecord extends UpdatableRecordImpl<OrdonancesRecord> implements Record10<Long, String, Long, Boolean, Timestamp, String, Boolean, Long, Long, Long> {

    private static final long serialVersionUID = 864009081;

    /**
     * Setter for <code>public.ordonances.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ordonances.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ordonances.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ordonances.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ordonances.consultation</code>.
     */
    public void setConsultation(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ordonances.consultation</code>.
     */
    public Long getConsultation() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.ordonances.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ordonances.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.ordonances.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ordonances.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.ordonances.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ordonances.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.ordonances.is_soin</code>.
     */
    public void setIsSoin(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ordonances.is_soin</code>.
     */
    public Boolean getIsSoin() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.ordonances.montant</code>.
     */
    public void setMontant(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ordonances.montant</code>.
     */
    public Long getMontant() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.ordonances.nombre</code>.
     */
    public void setNombre(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ordonances.nombre</code>.
     */
    public Long getNombre() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.ordonances.total</code>.
     */
    public void setTotal(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.ordonances.total</code>.
     */
    public Long getTotal() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, Long, Boolean, Timestamp, String, Boolean, Long, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, Long, Boolean, Timestamp, String, Boolean, Long, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Ordonances.ORDONANCES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Ordonances.ORDONANCES.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Ordonances.ORDONANCES.CONSULTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Ordonances.ORDONANCES.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Ordonances.ORDONANCES.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Ordonances.ORDONANCES.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Ordonances.ORDONANCES.IS_SOIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Ordonances.ORDONANCES.MONTANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Ordonances.ORDONANCES.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Ordonances.ORDONANCES.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getIsSoin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getMontant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getIsSoin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getMontant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value3(Long value) {
        setConsultation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value4(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value5(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value6(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value7(Boolean value) {
        setIsSoin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value8(Long value) {
        setMontant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value9(Long value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord value10(Long value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdonancesRecord values(Long value1, String value2, Long value3, Boolean value4, Timestamp value5, String value6, Boolean value7, Long value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdonancesRecord
     */
    public OrdonancesRecord() {
        super(Ordonances.ORDONANCES);
    }

    /**
     * Create a detached, initialised OrdonancesRecord
     */
    public OrdonancesRecord(Long id, String libelle, Long consultation, Boolean isDeleted, Timestamp whenDone, String whoDone, Boolean isSoin, Long montant, Long nombre, Long total) {
        super(Ordonances.ORDONANCES);

        set(0, id);
        set(1, libelle);
        set(2, consultation);
        set(3, isDeleted);
        set(4, whenDone);
        set(5, whoDone);
        set(6, isSoin);
        set(7, montant);
        set(8, nombre);
        set(9, total);
    }
}
