/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.Personnels;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonnelsRecord extends UpdatableRecordImpl<PersonnelsRecord> implements Record9<Long, String, String, String, String, String, Boolean, Timestamp, String> {

    private static final long serialVersionUID = -696114821;

    /**
     * Setter for <code>public.personnels.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.personnels.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.personnels.nom_p</code>.
     */
    public void setNomP(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.personnels.nom_p</code>.
     */
    public String getNomP() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.personnels.prenom_p</code>.
     */
    public void setPrenomP(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.personnels.prenom_p</code>.
     */
    public String getPrenomP() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.personnels.categorie</code>.
     */
    public void setCategorie(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.personnels.categorie</code>.
     */
    public String getCategorie() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.personnels.telephone</code>.
     */
    public void setTelephone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.personnels.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.personnels.adresse</code>.
     */
    public void setAdresse(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.personnels.adresse</code>.
     */
    public String getAdresse() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.personnels.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.personnels.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.personnels.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.personnels.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.personnels.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.personnels.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, Boolean, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, Boolean, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Personnels.PERSONNELS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Personnels.PERSONNELS.NOM_P;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Personnels.PERSONNELS.PRENOM_P;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Personnels.PERSONNELS.CATEGORIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Personnels.PERSONNELS.TELEPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Personnels.PERSONNELS.ADRESSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Personnels.PERSONNELS.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Personnels.PERSONNELS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Personnels.PERSONNELS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrenomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrenomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value2(String value) {
        setNomP(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value3(String value) {
        setPrenomP(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value4(String value) {
        setCategorie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value5(String value) {
        setTelephone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value6(String value) {
        setAdresse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value7(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value8(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord value9(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonnelsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonnelsRecord
     */
    public PersonnelsRecord() {
        super(Personnels.PERSONNELS);
    }

    /**
     * Create a detached, initialised PersonnelsRecord
     */
    public PersonnelsRecord(Long id, String nomP, String prenomP, String categorie, String telephone, String adresse, Boolean isDeleted, Timestamp whenDone, String whoDone) {
        super(Personnels.PERSONNELS);

        set(0, id);
        set(1, nomP);
        set(2, prenomP);
        set(3, categorie);
        set(4, telephone);
        set(5, adresse);
        set(6, isDeleted);
        set(7, whenDone);
        set(8, whoDone);
    }
}
