/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.Roles;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> implements Record5<Long, String, String, Timestamp, Boolean> {

    private static final long serialVersionUID = -298334709;

    /**
     * Setter for <code>public.roles.id_role</code>.
     */
    public void setIdRole(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.roles.id_role</code>.
     */
    public Long getIdRole() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.roles.libelle_role</code>.
     */
    public void setLibelleRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.roles.libelle_role</code>.
     */
    public String getLibelleRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.roles.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.roles.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.roles.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.roles.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.roles.on_deleted</code>.
     */
    public void setOnDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.roles.on_deleted</code>.
     */
    public Boolean getOnDeleted() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Roles.ROLES.ID_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Roles.ROLES.LIBELLE_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Roles.ROLES.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Roles.ROLES.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Roles.ROLES.ON_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelleRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelleRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getOnDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesRecord value1(Long value) {
        setIdRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesRecord value2(String value) {
        setLibelleRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesRecord value3(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesRecord value4(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesRecord value5(Boolean value) {
        setOnDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolesRecord values(Long value1, String value2, String value3, Timestamp value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(Long idRole, String libelleRole, String whoDone, Timestamp whenDone, Boolean onDeleted) {
        super(Roles.ROLES);

        set(0, idRole);
        set(1, libelleRole);
        set(2, whoDone);
        set(3, whenDone);
        set(4, onDeleted);
    }
}
