/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import javax.annotation.Generated;

import models.public_.tables.SConsultations;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SConsultationsRecord extends TableRecordImpl<SConsultationsRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 1534655874;

    /**
     * Setter for <code>public.s_consultations.nom_partenaire</code>.
     */
    public void setNomPartenaire(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.s_consultations.nom_partenaire</code>.
     */
    public String getNomPartenaire() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.s_consultations.nombre_de_consultations</code>.
     */
    public void setNombreDeConsultations(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.s_consultations.nombre_de_consultations</code>.
     */
    public Long getNombreDeConsultations() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SConsultations.S_CONSULTATIONS.NOM_PARTENAIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SConsultations.S_CONSULTATIONS.NOMBRE_DE_CONSULTATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getNomPartenaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getNombreDeConsultations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNomPartenaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getNombreDeConsultations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SConsultationsRecord value1(String value) {
        setNomPartenaire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SConsultationsRecord value2(Long value) {
        setNombreDeConsultations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SConsultationsRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SConsultationsRecord
     */
    public SConsultationsRecord() {
        super(SConsultations.S_CONSULTATIONS);
    }

    /**
     * Create a detached, initialised SConsultationsRecord
     */
    public SConsultationsRecord(String nomPartenaire, Long nombreDeConsultations) {
        super(SConsultations.S_CONSULTATIONS);

        set(0, nomPartenaire);
        set(1, nombreDeConsultations);
    }
}
