/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.VConsultations;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VConsultationsRecord extends TableRecordImpl<VConsultationsRecord> {

    private static final long serialVersionUID = -1650887428;

    /**
     * Setter for <code>public.v_consultations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_consultations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_consultations.numero_consul</code>.
     */
    public void setNumeroConsul(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_consultations.numero_consul</code>.
     */
    public String getNumeroConsul() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_consultations.type_consultation</code>.
     */
    public void setTypeConsultation(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_consultations.type_consultation</code>.
     */
    public Long getTypeConsultation() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.v_consultations.libelle_type</code>.
     */
    public void setLibelleType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_consultations.libelle_type</code>.
     */
    public String getLibelleType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_consultations.patient</code>.
     */
    public void setPatient(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_consultations.patient</code>.
     */
    public Long getPatient() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.v_consultations.id_patient</code>.
     */
    public void setIdPatient(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_consultations.id_patient</code>.
     */
    public Long getIdPatient() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.v_consultations.nom_patient</code>.
     */
    public void setNomPatient(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_consultations.nom_patient</code>.
     */
    public String getNomPatient() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_consultations.age</code>.
     */
    public void setAge(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_consultations.age</code>.
     */
    public Long getAge() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.v_consultations.partenaire_id</code>.
     */
    public void setPartenaireId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_consultations.partenaire_id</code>.
     */
    public Long getPartenaireId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.v_consultations.nom_partenaire</code>.
     */
    public void setNomPartenaire(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_consultations.nom_partenaire</code>.
     */
    public String getNomPartenaire() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.v_consultations.structure_patient</code>.
     */
    public void setStructurePatient(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_consultations.structure_patient</code>.
     */
    public String getStructurePatient() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.v_consultations.taux_couverture</code>.
     */
    public void setTauxCouverture(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_consultations.taux_couverture</code>.
     */
    public Double getTauxCouverture() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>public.v_consultations.tel_patient</code>.
     */
    public void setTelPatient(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_consultations.tel_patient</code>.
     */
    public String getTelPatient() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.v_consultations.medecin_traitrant</code>.
     */
    public void setMedecinTraitrant(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_consultations.medecin_traitrant</code>.
     */
    public Long getMedecinTraitrant() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.v_consultations.medecin</code>.
     */
    public void setMedecin(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_consultations.medecin</code>.
     */
    public String getMedecin() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_consultations.prix_consultation</code>.
     */
    public void setPrixConsultation(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_consultations.prix_consultation</code>.
     */
    public Long getPrixConsultation() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.v_consultations.montant_consultation</code>.
     */
    public void setMontantConsultation(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_consultations.montant_consultation</code>.
     */
    public Long getMontantConsultation() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>public.v_consultations.montant_en_lettre</code>.
     */
    public void setMontantEnLettre(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_consultations.montant_en_lettre</code>.
     */
    public String getMontantEnLettre() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.v_consultations.somme_recu</code>.
     */
    public void setSommeRecu(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_consultations.somme_recu</code>.
     */
    public Long getSommeRecu() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.v_consultations.somme_remise</code>.
     */
    public void setSommeRemise(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_consultations.somme_remise</code>.
     */
    public Long getSommeRemise() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.v_consultations.montant_pris_en_charge</code>.
     */
    public void setMontantPrisEnCharge(Double value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_consultations.montant_pris_en_charge</code>.
     */
    public Double getMontantPrisEnCharge() {
        return (Double) get(20);
    }

    /**
     * Setter for <code>public.v_consultations.montant_a_payer</code>.
     */
    public void setMontantAPayer(Double value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.v_consultations.montant_a_payer</code>.
     */
    public Double getMontantAPayer() {
        return (Double) get(21);
    }

    /**
     * Setter for <code>public.v_consultations.observation</code>.
     */
    public void setObservation(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.v_consultations.observation</code>.
     */
    public String getObservation() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.v_consultations.date_rdv</code>.
     */
    public void setDateRdv(Timestamp value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.v_consultations.date_rdv</code>.
     */
    public Timestamp getDateRdv() {
        return (Timestamp) get(23);
    }

    /**
     * Setter for <code>public.v_consultations.is_closed</code>.
     */
    public void setIsClosed(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.v_consultations.is_closed</code>.
     */
    public Boolean getIsClosed() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>public.v_consultations.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.v_consultations.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(25);
    }

    /**
     * Setter for <code>public.v_consultations.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.v_consultations.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(26);
    }

    /**
     * Setter for <code>public.v_consultations.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.v_consultations.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(27);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VConsultationsRecord
     */
    public VConsultationsRecord() {
        super(VConsultations.V_CONSULTATIONS);
    }

    /**
     * Create a detached, initialised VConsultationsRecord
     */
    public VConsultationsRecord(Long id, String numeroConsul, Long typeConsultation, String libelleType, Long patient, Long idPatient, String nomPatient, Long age, Long partenaireId, String nomPartenaire, String structurePatient, Double tauxCouverture, String telPatient, Long medecinTraitrant, String medecin, Long prixConsultation, Long montantConsultation, String montantEnLettre, Long sommeRecu, Long sommeRemise, Double montantPrisEnCharge, Double montantAPayer, String observation, Timestamp dateRdv, Boolean isClosed, Boolean isDeleted, Timestamp whenDone, String whoDone) {
        super(VConsultations.V_CONSULTATIONS);

        set(0, id);
        set(1, numeroConsul);
        set(2, typeConsultation);
        set(3, libelleType);
        set(4, patient);
        set(5, idPatient);
        set(6, nomPatient);
        set(7, age);
        set(8, partenaireId);
        set(9, nomPartenaire);
        set(10, structurePatient);
        set(11, tauxCouverture);
        set(12, telPatient);
        set(13, medecinTraitrant);
        set(14, medecin);
        set(15, prixConsultation);
        set(16, montantConsultation);
        set(17, montantEnLettre);
        set(18, sommeRecu);
        set(19, sommeRemise);
        set(20, montantPrisEnCharge);
        set(21, montantAPayer);
        set(22, observation);
        set(23, dateRdv);
        set(24, isClosed);
        set(25, isDeleted);
        set(26, whenDone);
        set(27, whoDone);
    }
}
