/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.VsExamMedecin;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VsExamMedecinRecord extends TableRecordImpl<VsExamMedecinRecord> implements Record7<String, String, String, String, String, Long, Timestamp> {

    private static final long serialVersionUID = 860257059;

    /**
     * Setter for <code>public.vs_exam_medecin.ref_facture</code>.
     */
    public void setRefFacture(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vs_exam_medecin.ref_facture</code>.
     */
    public String getRefFacture() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.vs_exam_medecin.nom_p</code>.
     */
    public void setNomP(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vs_exam_medecin.nom_p</code>.
     */
    public String getNomP() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vs_exam_medecin.prenom_p</code>.
     */
    public void setPrenomP(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vs_exam_medecin.prenom_p</code>.
     */
    public String getPrenomP() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vs_exam_medecin.categorie</code>.
     */
    public void setCategorie(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vs_exam_medecin.categorie</code>.
     */
    public String getCategorie() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vs_exam_medecin.telephone</code>.
     */
    public void setTelephone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vs_exam_medecin.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.vs_exam_medecin.montant</code>.
     */
    public void setMontant(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vs_exam_medecin.montant</code>.
     */
    public Long getMontant() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.vs_exam_medecin.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vs_exam_medecin.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Long, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Long, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VsExamMedecin.VS_EXAM_MEDECIN.REF_FACTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VsExamMedecin.VS_EXAM_MEDECIN.NOM_P;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VsExamMedecin.VS_EXAM_MEDECIN.PRENOM_P;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VsExamMedecin.VS_EXAM_MEDECIN.CATEGORIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VsExamMedecin.VS_EXAM_MEDECIN.TELEPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return VsExamMedecin.VS_EXAM_MEDECIN.MONTANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return VsExamMedecin.VS_EXAM_MEDECIN.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrenomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getMontant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRefFacture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrenomP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getMontant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord value1(String value) {
        setRefFacture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord value2(String value) {
        setNomP(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord value3(String value) {
        setPrenomP(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord value4(String value) {
        setCategorie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord value5(String value) {
        setTelephone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord value6(Long value) {
        setMontant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord value7(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsExamMedecinRecord values(String value1, String value2, String value3, String value4, String value5, Long value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VsExamMedecinRecord
     */
    public VsExamMedecinRecord() {
        super(VsExamMedecin.VS_EXAM_MEDECIN);
    }

    /**
     * Create a detached, initialised VsExamMedecinRecord
     */
    public VsExamMedecinRecord(String refFacture, String nomP, String prenomP, String categorie, String telephone, Long montant, Timestamp whenDone) {
        super(VsExamMedecin.VS_EXAM_MEDECIN);

        set(0, refFacture);
        set(1, nomP);
        set(2, prenomP);
        set(3, categorie);
        set(4, telephone);
        set(5, montant);
        set(6, whenDone);
    }
}
