/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.Public;
import models.public_.tables.records.ExamensOldRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamensOld extends TableImpl<ExamensOldRecord> {

    private static final long serialVersionUID = -1040547346;

    /**
     * The reference instance of <code>public.examens_old</code>
     */
    public static final ExamensOld EXAMENS_OLD = new ExamensOld();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExamensOldRecord> getRecordType() {
        return ExamensOldRecord.class;
    }

    /**
     * The column <code>public.examens_old.id</code>.
     */
    public final TableField<ExamensOldRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.examens_old.libelle</code>.
     */
    public final TableField<ExamensOldRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.examens_old.resultat</code>.
     */
    public final TableField<ExamensOldRecord, String> RESULTAT = createField("resultat", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.examens_old.observation</code>.
     */
    public final TableField<ExamensOldRecord, String> OBSERVATION = createField("observation", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.examens_old.is_deleted</code>.
     */
    public final TableField<ExamensOldRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.examens_old.when_done</code>.
     */
    public final TableField<ExamensOldRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.examens_old.consultation</code>.
     */
    public final TableField<ExamensOldRecord, Long> CONSULTATION = createField("consultation", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.examens_old.who_done</code>.
     */
    public final TableField<ExamensOldRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.examens_old.cout_examen</code>.
     */
    public final TableField<ExamensOldRecord, Long> COUT_EXAMEN = createField("cout_examen", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.examens_old</code> table reference
     */
    public ExamensOld() {
        this(DSL.name("examens_old"), null);
    }

    /**
     * Create an aliased <code>public.examens_old</code> table reference
     */
    public ExamensOld(String alias) {
        this(DSL.name(alias), EXAMENS_OLD);
    }

    /**
     * Create an aliased <code>public.examens_old</code> table reference
     */
    public ExamensOld(Name alias) {
        this(alias, EXAMENS_OLD);
    }

    private ExamensOld(Name alias, Table<ExamensOldRecord> aliased) {
        this(alias, aliased, null);
    }

    private ExamensOld(Name alias, Table<ExamensOldRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamensOld as(String alias) {
        return new ExamensOld(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExamensOld as(Name alias) {
        return new ExamensOld(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExamensOld rename(String name) {
        return new ExamensOld(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExamensOld rename(Name name) {
        return new ExamensOld(name, null);
    }
}
