/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.Public;
import models.public_.tables.records.VPatientsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VPatients extends TableImpl<VPatientsRecord> {

    private static final long serialVersionUID = -1636856935;

    /**
     * The reference instance of <code>public.v_patients</code>
     */
    public static final VPatients V_PATIENTS = new VPatients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VPatientsRecord> getRecordType() {
        return VPatientsRecord.class;
    }

    /**
     * The column <code>public.v_patients.id</code>.
     */
    public final TableField<VPatientsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_patients.nom_prenom</code>.
     */
    public final TableField<VPatientsRecord, String> NOM_PRENOM = createField("nom_prenom", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.v_patients.telephone</code>.
     */
    public final TableField<VPatientsRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_patients.partenaire</code>.
     */
    public final TableField<VPatientsRecord, Long> PARTENAIRE = createField("partenaire", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_patients.libelle</code>.
     */
    public final TableField<VPatientsRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.v_patients.taux_couverture</code>.
     */
    public final TableField<VPatientsRecord, Double> TAUX_COUVERTURE = createField("taux_couverture", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_patients.date_naissance</code>.
     */
    public final TableField<VPatientsRecord, Timestamp> DATE_NAISSANCE = createField("date_naissance", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_patients.age</code>.
     */
    public final TableField<VPatientsRecord, Long> AGE = createField("age", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_patients.is_deleted</code>.
     */
    public final TableField<VPatientsRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_patients.when_done</code>.
     */
    public final TableField<VPatientsRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_patients.poid</code>.
     */
    public final TableField<VPatientsRecord, Long> POID = createField("poid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_patients.status</code>.
     */
    public final TableField<VPatientsRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_patients.who_done</code>.
     */
    public final TableField<VPatientsRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.v_patients</code> table reference
     */
    public VPatients() {
        this(DSL.name("v_patients"), null);
    }

    /**
     * Create an aliased <code>public.v_patients</code> table reference
     */
    public VPatients(String alias) {
        this(DSL.name(alias), V_PATIENTS);
    }

    /**
     * Create an aliased <code>public.v_patients</code> table reference
     */
    public VPatients(Name alias) {
        this(alias, V_PATIENTS);
    }

    private VPatients(Name alias, Table<VPatientsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VPatients(Name alias, Table<VPatientsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPatients as(String alias) {
        return new VPatients(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPatients as(Name alias) {
        return new VPatients(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VPatients rename(String name) {
        return new VPatients(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VPatients rename(Name name) {
        return new VPatients(name, null);
    }
}
