/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.public_.Keys;
import models.public_.Public;
import models.public_.tables.records.ExamensRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Examens extends TableImpl<ExamensRecord> {

    private static final long serialVersionUID = -1799533635;

    /**
     * The reference instance of <code>public.examens</code>
     */
    public static final Examens EXAMENS = new Examens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExamensRecord> getRecordType() {
        return ExamensRecord.class;
    }

    /**
     * The column <code>public.examens.id</code>.
     */
    public final TableField<ExamensRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('examens_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.examens.libelle</code>.
     */
    public final TableField<ExamensRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR(250).nullable(false), this, "");

    /**
     * The column <code>public.examens.resultat</code>.
     */
    public final TableField<ExamensRecord, String> RESULTAT = createField("resultat", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.examens.observation</code>.
     */
    public final TableField<ExamensRecord, String> OBSERVATION = createField("observation", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.examens.is_deleted</code>.
     */
    public final TableField<ExamensRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.examens.when_done</code>.
     */
    public final TableField<ExamensRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.examens.consultation</code>.
     */
    public final TableField<ExamensRecord, Long> CONSULTATION = createField("consultation", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.examens.who_done</code>.
     */
    public final TableField<ExamensRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.examens.cout_examen</code>.
     */
    public final TableField<ExamensRecord, Long> COUT_EXAMEN = createField("cout_examen", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.examens</code> table reference
     */
    public Examens() {
        this(DSL.name("examens"), null);
    }

    /**
     * Create an aliased <code>public.examens</code> table reference
     */
    public Examens(String alias) {
        this(DSL.name(alias), EXAMENS);
    }

    /**
     * Create an aliased <code>public.examens</code> table reference
     */
    public Examens(Name alias) {
        this(alias, EXAMENS);
    }

    private Examens(Name alias, Table<ExamensRecord> aliased) {
        this(alias, aliased, null);
    }

    private Examens(Name alias, Table<ExamensRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExamensRecord, Long> getIdentity() {
        return Keys.IDENTITY_EXAMENS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExamensRecord> getPrimaryKey() {
        return Keys.EXAMENS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExamensRecord>> getKeys() {
        return Arrays.<UniqueKey<ExamensRecord>>asList(Keys.EXAMENS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ExamensRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExamensRecord, ?>>asList(Keys.EXAMENS__CONSULTATION_FKP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Examens as(String alias) {
        return new Examens(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Examens as(Name alias) {
        return new Examens(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Examens rename(String name) {
        return new Examens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Examens rename(Name name) {
        return new Examens(name, null);
    }
}
