/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.public_.Keys;
import models.public_.Public;
import models.public_.tables.records.MedecinPatientRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedecinPatient extends TableImpl<MedecinPatientRecord> {

    private static final long serialVersionUID = 1973072754;

    /**
     * The reference instance of <code>public.medecin_patient</code>
     */
    public static final MedecinPatient MEDECIN_PATIENT = new MedecinPatient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedecinPatientRecord> getRecordType() {
        return MedecinPatientRecord.class;
    }

    /**
     * The column <code>public.medecin_patient.id</code>.
     */
    public final TableField<MedecinPatientRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('medecin_patient_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.medecin_patient.patient_id</code>.
     */
    public final TableField<MedecinPatientRecord, Long> PATIENT_ID = createField("patient_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.medecin_patient.medecin_id</code>.
     */
    public final TableField<MedecinPatientRecord, Long> MEDECIN_ID = createField("medecin_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.medecin_patient</code> table reference
     */
    public MedecinPatient() {
        this(DSL.name("medecin_patient"), null);
    }

    /**
     * Create an aliased <code>public.medecin_patient</code> table reference
     */
    public MedecinPatient(String alias) {
        this(DSL.name(alias), MEDECIN_PATIENT);
    }

    /**
     * Create an aliased <code>public.medecin_patient</code> table reference
     */
    public MedecinPatient(Name alias) {
        this(alias, MEDECIN_PATIENT);
    }

    private MedecinPatient(Name alias, Table<MedecinPatientRecord> aliased) {
        this(alias, aliased, null);
    }

    private MedecinPatient(Name alias, Table<MedecinPatientRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MedecinPatientRecord, Long> getIdentity() {
        return Keys.IDENTITY_MEDECIN_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MedecinPatientRecord> getPrimaryKey() {
        return Keys.MEDECIN_PATIENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MedecinPatientRecord>> getKeys() {
        return Arrays.<UniqueKey<MedecinPatientRecord>>asList(Keys.MEDECIN_PATIENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MedecinPatientRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MedecinPatientRecord, ?>>asList(Keys.MEDECIN_PATIENT__FK_PAT, Keys.MEDECIN_PATIENT__FK_MEDECIN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MedecinPatient as(String alias) {
        return new MedecinPatient(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MedecinPatient as(Name alias) {
        return new MedecinPatient(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedecinPatient rename(String name) {
        return new MedecinPatient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedecinPatient rename(Name name) {
        return new MedecinPatient(name, null);
    }
}
