/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.public_.Keys;
import models.public_.Public;
import models.public_.tables.records.ParamsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Params extends TableImpl<ParamsRecord> {

    private static final long serialVersionUID = 394051784;

    /**
     * The reference instance of <code>public.params</code>
     */
    public static final Params PARAMS = new Params();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParamsRecord> getRecordType() {
        return ParamsRecord.class;
    }

    /**
     * The column <code>public.params.id</code>.
     */
    public final TableField<ParamsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('params_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.params.nom_structure</code>.
     */
    public final TableField<ParamsRecord, String> NOM_STRUCTURE = createField("nom_structure", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.params.adresse</code>.
     */
    public final TableField<ParamsRecord, String> ADRESSE = createField("adresse", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.params.tel</code>.
     */
    public final TableField<ParamsRecord, String> TEL = createField("tel", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.params.adress</code>.
     */
    public final TableField<ParamsRecord, String> ADRESS = createField("adress", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.params.logo</code>.
     */
    public final TableField<ParamsRecord, String> LOGO = createField("logo", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.params.info_bank</code>.
     */
    public final TableField<ParamsRecord, String> INFO_BANK = createField("info_bank", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>public.params</code> table reference
     */
    public Params() {
        this(DSL.name("params"), null);
    }

    /**
     * Create an aliased <code>public.params</code> table reference
     */
    public Params(String alias) {
        this(DSL.name(alias), PARAMS);
    }

    /**
     * Create an aliased <code>public.params</code> table reference
     */
    public Params(Name alias) {
        this(alias, PARAMS);
    }

    private Params(Name alias, Table<ParamsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Params(Name alias, Table<ParamsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ParamsRecord, Long> getIdentity() {
        return Keys.IDENTITY_PARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParamsRecord> getPrimaryKey() {
        return Keys.PARAMS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParamsRecord>> getKeys() {
        return Arrays.<UniqueKey<ParamsRecord>>asList(Keys.PARAMS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Params as(String alias) {
        return new Params(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Params as(Name alias) {
        return new Params(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Params rename(String name) {
        return new Params(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Params rename(Name name) {
        return new Params(name, null);
    }
}
