/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.public_.Indexes;
import models.public_.Keys;
import models.public_.Public;
import models.public_.tables.records.PartenaireRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Partenaire extends TableImpl<PartenaireRecord> {

    private static final long serialVersionUID = 99871928;

    /**
     * The reference instance of <code>public.partenaire</code>
     */
    public static final Partenaire PARTENAIRE = new Partenaire();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartenaireRecord> getRecordType() {
        return PartenaireRecord.class;
    }

    /**
     * The column <code>public.partenaire.id</code>.
     */
    public final TableField<PartenaireRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('partenaire_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.partenaire.libelle</code>.
     */
    public final TableField<PartenaireRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>public.partenaire.taux_couverture</code>.
     */
    public final TableField<PartenaireRecord, Double> TAUX_COUVERTURE = createField("taux_couverture", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.partenaire.telephone</code>.
     */
    public final TableField<PartenaireRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.partenaire.is_deleted</code>.
     */
    public final TableField<PartenaireRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.partenaire.when_done</code>.
     */
    public final TableField<PartenaireRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.partenaire.who_done</code>.
     */
    public final TableField<PartenaireRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>public.partenaire</code> table reference
     */
    public Partenaire() {
        this(DSL.name("partenaire"), null);
    }

    /**
     * Create an aliased <code>public.partenaire</code> table reference
     */
    public Partenaire(String alias) {
        this(DSL.name(alias), PARTENAIRE);
    }

    /**
     * Create an aliased <code>public.partenaire</code> table reference
     */
    public Partenaire(Name alias) {
        this(alias, PARTENAIRE);
    }

    private Partenaire(Name alias, Table<PartenaireRecord> aliased) {
        this(alias, aliased, null);
    }

    private Partenaire(Name alias, Table<PartenaireRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PARTENAIRE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PartenaireRecord, Long> getIdentity() {
        return Keys.IDENTITY_PARTENAIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PartenaireRecord> getPrimaryKey() {
        return Keys.PARTENAIRE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PartenaireRecord>> getKeys() {
        return Arrays.<UniqueKey<PartenaireRecord>>asList(Keys.PARTENAIRE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Partenaire as(String alias) {
        return new Partenaire(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Partenaire as(Name alias) {
        return new Partenaire(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Partenaire rename(String name) {
        return new Partenaire(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Partenaire rename(Name name) {
        return new Partenaire(name, null);
    }
}
