/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.public_.Indexes;
import models.public_.Keys;
import models.public_.Public;
import models.public_.tables.records.PersonnelsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Personnels extends TableImpl<PersonnelsRecord> {

    private static final long serialVersionUID = -1455752003;

    /**
     * The reference instance of <code>public.personnels</code>
     */
    public static final Personnels PERSONNELS = new Personnels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersonnelsRecord> getRecordType() {
        return PersonnelsRecord.class;
    }

    /**
     * The column <code>public.personnels.id</code>.
     */
    public final TableField<PersonnelsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('personnels_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.personnels.nom_p</code>.
     */
    public final TableField<PersonnelsRecord, String> NOM_P = createField("nom_p", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.personnels.prenom_p</code>.
     */
    public final TableField<PersonnelsRecord, String> PRENOM_P = createField("prenom_p", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.personnels.categorie</code>.
     */
    public final TableField<PersonnelsRecord, String> CATEGORIE = createField("categorie", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.personnels.telephone</code>.
     */
    public final TableField<PersonnelsRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.personnels.adresse</code>.
     */
    public final TableField<PersonnelsRecord, String> ADRESSE = createField("adresse", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.personnels.is_deleted</code>.
     */
    public final TableField<PersonnelsRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.personnels.when_done</code>.
     */
    public final TableField<PersonnelsRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.personnels.who_done</code>.
     */
    public final TableField<PersonnelsRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * Create a <code>public.personnels</code> table reference
     */
    public Personnels() {
        this(DSL.name("personnels"), null);
    }

    /**
     * Create an aliased <code>public.personnels</code> table reference
     */
    public Personnels(String alias) {
        this(DSL.name(alias), PERSONNELS);
    }

    /**
     * Create an aliased <code>public.personnels</code> table reference
     */
    public Personnels(Name alias) {
        this(alias, PERSONNELS);
    }

    private Personnels(Name alias, Table<PersonnelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Personnels(Name alias, Table<PersonnelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PERSONNELS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PersonnelsRecord, Long> getIdentity() {
        return Keys.IDENTITY_PERSONNELS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersonnelsRecord> getPrimaryKey() {
        return Keys.PERSONNELS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersonnelsRecord>> getKeys() {
        return Arrays.<UniqueKey<PersonnelsRecord>>asList(Keys.PERSONNELS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Personnels as(String alias) {
        return new Personnels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Personnels as(Name alias) {
        return new Personnels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Personnels rename(String name) {
        return new Personnels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Personnels rename(Name name) {
        return new Personnels(name, null);
    }
}
