/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import javax.annotation.Generated;

import models.public_.Public;
import models.public_.tables.records.SConsultationsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SConsultations extends TableImpl<SConsultationsRecord> {

    private static final long serialVersionUID = -82713194;

    /**
     * The reference instance of <code>public.s_consultations</code>
     */
    public static final SConsultations S_CONSULTATIONS = new SConsultations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SConsultationsRecord> getRecordType() {
        return SConsultationsRecord.class;
    }

    /**
     * The column <code>public.s_consultations.nom_partenaire</code>.
     */
    public final TableField<SConsultationsRecord, String> NOM_PARTENAIRE = createField("nom_partenaire", org.jooq.impl.SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.s_consultations.nombre_de_consultations</code>.
     */
    public final TableField<SConsultationsRecord, Long> NOMBRE_DE_CONSULTATIONS = createField("nombre_de_consultations", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.s_consultations</code> table reference
     */
    public SConsultations() {
        this(DSL.name("s_consultations"), null);
    }

    /**
     * Create an aliased <code>public.s_consultations</code> table reference
     */
    public SConsultations(String alias) {
        this(DSL.name(alias), S_CONSULTATIONS);
    }

    /**
     * Create an aliased <code>public.s_consultations</code> table reference
     */
    public SConsultations(Name alias) {
        this(alias, S_CONSULTATIONS);
    }

    private SConsultations(Name alias, Table<SConsultationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SConsultations(Name alias, Table<SConsultationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SConsultations as(String alias) {
        return new SConsultations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SConsultations as(Name alias) {
        return new SConsultations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SConsultations rename(String name) {
        return new SConsultations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SConsultations rename(Name name) {
        return new SConsultations(name, null);
    }
}
