/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.public_.Indexes;
import models.public_.Keys;
import models.public_.Public;
import models.public_.tables.records.TypeConsultationRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeConsultation extends TableImpl<TypeConsultationRecord> {

    private static final long serialVersionUID = 1724314744;

    /**
     * The reference instance of <code>public.type_consultation</code>
     */
    public static final TypeConsultation TYPE_CONSULTATION = new TypeConsultation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypeConsultationRecord> getRecordType() {
        return TypeConsultationRecord.class;
    }

    /**
     * The column <code>public.type_consultation.id</code>.
     */
    public final TableField<TypeConsultationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('type_consultation_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.type_consultation.libelle</code>.
     */
    public final TableField<TypeConsultationRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.type_consultation.prix</code>.
     */
    public final TableField<TypeConsultationRecord, Long> PRIX = createField("prix", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.type_consultation.is_deleted</code>.
     */
    public final TableField<TypeConsultationRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.type_consultation.when_done</code>.
     */
    public final TableField<TypeConsultationRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.type_consultation.who_done</code>.
     */
    public final TableField<TypeConsultationRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.type_consultation.prix_pcm</code>.
     */
    public final TableField<TypeConsultationRecord, Long> PRIX_PCM = createField("prix_pcm", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>public.type_consultation</code> table reference
     */
    public TypeConsultation() {
        this(DSL.name("type_consultation"), null);
    }

    /**
     * Create an aliased <code>public.type_consultation</code> table reference
     */
    public TypeConsultation(String alias) {
        this(DSL.name(alias), TYPE_CONSULTATION);
    }

    /**
     * Create an aliased <code>public.type_consultation</code> table reference
     */
    public TypeConsultation(Name alias) {
        this(alias, TYPE_CONSULTATION);
    }

    private TypeConsultation(Name alias, Table<TypeConsultationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TypeConsultation(Name alias, Table<TypeConsultationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TYPE_CONSULTATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TypeConsultationRecord, Long> getIdentity() {
        return Keys.IDENTITY_TYPE_CONSULTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TypeConsultationRecord> getPrimaryKey() {
        return Keys.TYPE_CONSULTATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TypeConsultationRecord>> getKeys() {
        return Arrays.<UniqueKey<TypeConsultationRecord>>asList(Keys.TYPE_CONSULTATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeConsultation as(String alias) {
        return new TypeConsultation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeConsultation as(Name alias) {
        return new TypeConsultation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeConsultation rename(String name) {
        return new TypeConsultation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeConsultation rename(Name name) {
        return new TypeConsultation(name, null);
    }
}
