/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.Public;
import models.public_.tables.records.VConsultationsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VConsultations extends TableImpl<VConsultationsRecord> {

    private static final long serialVersionUID = 621269856;

    /**
     * The reference instance of <code>public.v_consultations</code>
     */
    public static final VConsultations V_CONSULTATIONS = new VConsultations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VConsultationsRecord> getRecordType() {
        return VConsultationsRecord.class;
    }

    /**
     * The column <code>public.v_consultations.id</code>.
     */
    public final TableField<VConsultationsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.numero_consul</code>.
     */
    public final TableField<VConsultationsRecord, String> NUMERO_CONSUL = createField("numero_consul", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_consultations.type_consultation</code>.
     */
    public final TableField<VConsultationsRecord, Long> TYPE_CONSULTATION = createField("type_consultation", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.libelle_type</code>.
     */
    public final TableField<VConsultationsRecord, String> LIBELLE_TYPE = createField("libelle_type", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_consultations.patient</code>.
     */
    public final TableField<VConsultationsRecord, Long> PATIENT = createField("patient", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.id_patient</code>.
     */
    public final TableField<VConsultationsRecord, Long> ID_PATIENT = createField("id_patient", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.nom_patient</code>.
     */
    public final TableField<VConsultationsRecord, String> NOM_PATIENT = createField("nom_patient", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.v_consultations.age</code>.
     */
    public final TableField<VConsultationsRecord, Long> AGE = createField("age", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.partenaire_id</code>.
     */
    public final TableField<VConsultationsRecord, Long> PARTENAIRE_ID = createField("partenaire_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.nom_partenaire</code>.
     */
    public final TableField<VConsultationsRecord, String> NOM_PARTENAIRE = createField("nom_partenaire", org.jooq.impl.SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.v_consultations.structure_patient</code>.
     */
    public final TableField<VConsultationsRecord, String> STRUCTURE_PATIENT = createField("structure_patient", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_consultations.taux_couverture</code>.
     */
    public final TableField<VConsultationsRecord, Double> TAUX_COUVERTURE = createField("taux_couverture", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_consultations.tel_patient</code>.
     */
    public final TableField<VConsultationsRecord, String> TEL_PATIENT = createField("tel_patient", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_consultations.medecin_traitrant</code>.
     */
    public final TableField<VConsultationsRecord, Long> MEDECIN_TRAITRANT = createField("medecin_traitrant", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.medecin</code>.
     */
    public final TableField<VConsultationsRecord, String> MEDECIN = createField("medecin", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.v_consultations.prix_consultation</code>.
     */
    public final TableField<VConsultationsRecord, Long> PRIX_CONSULTATION = createField("prix_consultation", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.montant_consultation</code>.
     */
    public final TableField<VConsultationsRecord, Long> MONTANT_CONSULTATION = createField("montant_consultation", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.montant_en_lettre</code>.
     */
    public final TableField<VConsultationsRecord, String> MONTANT_EN_LETTRE = createField("montant_en_lettre", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.v_consultations.somme_recu</code>.
     */
    public final TableField<VConsultationsRecord, Long> SOMME_RECU = createField("somme_recu", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.somme_remise</code>.
     */
    public final TableField<VConsultationsRecord, Long> SOMME_REMISE = createField("somme_remise", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_consultations.montant_pris_en_charge</code>.
     */
    public final TableField<VConsultationsRecord, Double> MONTANT_PRIS_EN_CHARGE = createField("montant_pris_en_charge", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_consultations.montant_a_payer</code>.
     */
    public final TableField<VConsultationsRecord, Double> MONTANT_A_PAYER = createField("montant_a_payer", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_consultations.observation</code>.
     */
    public final TableField<VConsultationsRecord, String> OBSERVATION = createField("observation", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.v_consultations.date_rdv</code>.
     */
    public final TableField<VConsultationsRecord, Timestamp> DATE_RDV = createField("date_rdv", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_consultations.is_closed</code>.
     */
    public final TableField<VConsultationsRecord, Boolean> IS_CLOSED = createField("is_closed", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_consultations.is_deleted</code>.
     */
    public final TableField<VConsultationsRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_consultations.when_done</code>.
     */
    public final TableField<VConsultationsRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_consultations.who_done</code>.
     */
    public final TableField<VConsultationsRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.v_consultations.r_nbr_fact</code>.
     */
    public final TableField<VConsultationsRecord, String> R_NBR_FACT = createField("r_nbr_fact", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_consultations.r_nbr_total</code>.
     */
    public final TableField<VConsultationsRecord, String> R_NBR_TOTAL = createField("r_nbr_total", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.v_consultations.r_type_fact</code>.
     */
    public final TableField<VConsultationsRecord, String> R_TYPE_FACT = createField("r_type_fact", org.jooq.impl.SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>public.v_consultations.r_date_fact</code>.
     */
    public final TableField<VConsultationsRecord, String> R_DATE_FACT = createField("r_date_fact", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.v_consultations.r_num_dispositif_fact</code>.
     */
    public final TableField<VConsultationsRecord, String> R_NUM_DISPOSITIF_FACT = createField("r_num_dispositif_fact", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_consultations.r_nif_fact</code>.
     */
    public final TableField<VConsultationsRecord, String> R_NIF_FACT = createField("r_nif_fact", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.v_consultations.r_signature_fact</code>.
     */
    public final TableField<VConsultationsRecord, String> R_SIGNATURE_FACT = createField("r_signature_fact", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>public.v_consultations</code> table reference
     */
    public VConsultations() {
        this(DSL.name("v_consultations"), null);
    }

    /**
     * Create an aliased <code>public.v_consultations</code> table reference
     */
    public VConsultations(String alias) {
        this(DSL.name(alias), V_CONSULTATIONS);
    }

    /**
     * Create an aliased <code>public.v_consultations</code> table reference
     */
    public VConsultations(Name alias) {
        this(alias, V_CONSULTATIONS);
    }

    private VConsultations(Name alias, Table<VConsultationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VConsultations(Name alias, Table<VConsultationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VConsultations as(String alias) {
        return new VConsultations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VConsultations as(Name alias) {
        return new VConsultations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VConsultations rename(String name) {
        return new VConsultations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VConsultations rename(Name name) {
        return new VConsultations(name, null);
    }
}
