/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.Public;
import models.public_.tables.records.VOrdononceRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VOrdononce extends TableImpl<VOrdononceRecord> {

    private static final long serialVersionUID = -473845720;

    /**
     * The reference instance of <code>public.v_ordononce</code>
     */
    public static final VOrdononce V_ORDONONCE = new VOrdononce();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VOrdononceRecord> getRecordType() {
        return VOrdononceRecord.class;
    }

    /**
     * The column <code>public.v_ordononce.id</code>.
     */
    public final TableField<VOrdononceRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ordononce.libelle</code>.
     */
    public final TableField<VOrdononceRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.v_ordononce.consultation</code>.
     */
    public final TableField<VOrdononceRecord, Long> CONSULTATION = createField("consultation", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ordononce.numero_consul</code>.
     */
    public final TableField<VOrdononceRecord, String> NUMERO_CONSUL = createField("numero_consul", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ordononce.age</code>.
     */
    public final TableField<VOrdononceRecord, Long> AGE = createField("age", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ordononce.id_patient</code>.
     */
    public final TableField<VOrdononceRecord, Long> ID_PATIENT = createField("id_patient", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_ordononce.tel_patient</code>.
     */
    public final TableField<VOrdononceRecord, String> TEL_PATIENT = createField("tel_patient", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_ordononce.nom_patient</code>.
     */
    public final TableField<VOrdononceRecord, String> NOM_PATIENT = createField("nom_patient", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.v_ordononce.date_consultation</code>.
     */
    public final TableField<VOrdononceRecord, Timestamp> DATE_CONSULTATION = createField("date_consultation", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_ordononce.is_deleted</code>.
     */
    public final TableField<VOrdononceRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_ordononce.when_done</code>.
     */
    public final TableField<VOrdononceRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_ordononce.consultations</code>.
     */
    public final TableField<VOrdononceRecord, String> CONSULTATIONS = createField("consultations", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_ordononce.who_done</code>.
     */
    public final TableField<VOrdononceRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.v_ordononce.is_soin</code>.
     */
    public final TableField<VOrdononceRecord, Boolean> IS_SOIN = createField("is_soin", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_ordononce.montant</code>.
     */
    public final TableField<VOrdononceRecord, Long> MONTANT = createField("montant", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.v_ordononce</code> table reference
     */
    public VOrdononce() {
        this(DSL.name("v_ordononce"), null);
    }

    /**
     * Create an aliased <code>public.v_ordononce</code> table reference
     */
    public VOrdononce(String alias) {
        this(DSL.name(alias), V_ORDONONCE);
    }

    /**
     * Create an aliased <code>public.v_ordononce</code> table reference
     */
    public VOrdononce(Name alias) {
        this(alias, V_ORDONONCE);
    }

    private VOrdononce(Name alias, Table<VOrdononceRecord> aliased) {
        this(alias, aliased, null);
    }

    private VOrdononce(Name alias, Table<VOrdononceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VOrdononce as(String alias) {
        return new VOrdononce(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VOrdononce as(Name alias) {
        return new VOrdononce(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VOrdononce rename(String name) {
        return new VOrdononce(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VOrdononce rename(Name name) {
        return new VOrdononce(name, null);
    }
}
