/*
 * This file is generated by jOOQ.
*/
package models.public_.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.Public;
import models.public_.tables.records.VSoinsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VSoins extends TableImpl<VSoinsRecord> {

    private static final long serialVersionUID = -696834669;

    /**
     * The reference instance of <code>public.v_soins</code>
     */
    public static final VSoins V_SOINS = new VSoins();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VSoinsRecord> getRecordType() {
        return VSoinsRecord.class;
    }

    /**
     * The column <code>public.v_soins.id</code>.
     */
    public final TableField<VSoinsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.libelle</code>.
     */
    public final TableField<VSoinsRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>public.v_soins.consultation</code>.
     */
    public final TableField<VSoinsRecord, Long> CONSULTATION = createField("consultation", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.numero_consul</code>.
     */
    public final TableField<VSoinsRecord, String> NUMERO_CONSUL = createField("numero_consul", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_soins.age</code>.
     */
    public final TableField<VSoinsRecord, Long> AGE = createField("age", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.id_patient</code>.
     */
    public final TableField<VSoinsRecord, Long> ID_PATIENT = createField("id_patient", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.tel_patient</code>.
     */
    public final TableField<VSoinsRecord, String> TEL_PATIENT = createField("tel_patient", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_soins.nom_patient</code>.
     */
    public final TableField<VSoinsRecord, String> NOM_PATIENT = createField("nom_patient", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.v_soins.date_consultation</code>.
     */
    public final TableField<VSoinsRecord, Timestamp> DATE_CONSULTATION = createField("date_consultation", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_soins.is_deleted</code>.
     */
    public final TableField<VSoinsRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_soins.when_done</code>.
     */
    public final TableField<VSoinsRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.v_soins.consultations</code>.
     */
    public final TableField<VSoinsRecord, String> CONSULTATIONS = createField("consultations", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.v_soins.who_done</code>.
     */
    public final TableField<VSoinsRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.v_soins.is_soin</code>.
     */
    public final TableField<VSoinsRecord, Boolean> IS_SOIN = createField("is_soin", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.v_soins.montant</code>.
     */
    public final TableField<VSoinsRecord, Long> MONTANT = createField("montant", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.nombre</code>.
     */
    public final TableField<VSoinsRecord, Long> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.total</code>.
     */
    public final TableField<VSoinsRecord, Long> TOTAL = createField("total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.medecin</code>.
     */
    public final TableField<VSoinsRecord, Long> MEDECIN = createField("medecin", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.nom_partenaire</code>.
     */
    public final TableField<VSoinsRecord, String> NOM_PARTENAIRE = createField("nom_partenaire", org.jooq.impl.SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.v_soins.partenaire_id</code>.
     */
    public final TableField<VSoinsRecord, Long> PARTENAIRE_ID = createField("partenaire_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.v_soins.taux_couverture</code>.
     */
    public final TableField<VSoinsRecord, Double> TAUX_COUVERTURE = createField("taux_couverture", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_soins.montant_pris_en_charge</code>.
     */
    public final TableField<VSoinsRecord, Double> MONTANT_PRIS_EN_CHARGE = createField("montant_pris_en_charge", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.v_soins.montant_net_a_payer</code>.
     */
    public final TableField<VSoinsRecord, Double> MONTANT_NET_A_PAYER = createField("montant_net_a_payer", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.v_soins</code> table reference
     */
    public VSoins() {
        this(DSL.name("v_soins"), null);
    }

    /**
     * Create an aliased <code>public.v_soins</code> table reference
     */
    public VSoins(String alias) {
        this(DSL.name(alias), V_SOINS);
    }

    /**
     * Create an aliased <code>public.v_soins</code> table reference
     */
    public VSoins(Name alias) {
        this(alias, V_SOINS);
    }

    private VSoins(Name alias, Table<VSoinsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VSoins(Name alias, Table<VSoinsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSoins as(String alias) {
        return new VSoins(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSoins as(Name alias) {
        return new VSoins(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VSoins rename(String name) {
        return new VSoins(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VSoins rename(Name name) {
        return new VSoins(name, null);
    }
}
