/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.BasMedicaments;
import models.public_.tables.records.BasMedicamentsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasMedicamentsDao extends DAOImpl<BasMedicamentsRecord, models.public_.tables.pojos.BasMedicaments, Long> {

    /**
     * Create a new BasMedicamentsDao without any configuration
     */
    public BasMedicamentsDao() {
        super(BasMedicaments.BAS_MEDICAMENTS, models.public_.tables.pojos.BasMedicaments.class);
    }

    /**
     * Create a new BasMedicamentsDao with an attached configuration
     */
    public BasMedicamentsDao(Configuration configuration) {
        super(BasMedicaments.BAS_MEDICAMENTS, models.public_.tables.pojos.BasMedicaments.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.BasMedicaments object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasMedicaments> fetchById(Long... values) {
        return fetch(BasMedicaments.BAS_MEDICAMENTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.public_.tables.pojos.BasMedicaments fetchOneById(Long value) {
        return fetchOne(BasMedicaments.BAS_MEDICAMENTS.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasMedicaments> fetchByLibelle(String... values) {
        return fetch(BasMedicaments.BAS_MEDICAMENTS.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasMedicaments> fetchByIsDeleted(Boolean... values) {
        return fetch(BasMedicaments.BAS_MEDICAMENTS.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasMedicaments> fetchByWhenDone(Timestamp... values) {
        return fetch(BasMedicaments.BAS_MEDICAMENTS.WHEN_DONE, values);
    }
}
