/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.BasSoins;
import models.public_.tables.records.BasSoinsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasSoinsDao extends DAOImpl<BasSoinsRecord, models.public_.tables.pojos.BasSoins, Long> {

    /**
     * Create a new BasSoinsDao without any configuration
     */
    public BasSoinsDao() {
        super(BasSoins.BAS_SOINS, models.public_.tables.pojos.BasSoins.class);
    }

    /**
     * Create a new BasSoinsDao with an attached configuration
     */
    public BasSoinsDao(Configuration configuration) {
        super(BasSoins.BAS_SOINS, models.public_.tables.pojos.BasSoins.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.BasSoins object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasSoins> fetchById(Long... values) {
        return fetch(BasSoins.BAS_SOINS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.public_.tables.pojos.BasSoins fetchOneById(Long value) {
        return fetchOne(BasSoins.BAS_SOINS.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasSoins> fetchByLibelle(String... values) {
        return fetch(BasSoins.BAS_SOINS.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>prix_norm IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasSoins> fetchByPrixNorm(Long... values) {
        return fetch(BasSoins.BAS_SOINS.PRIX_NORM, values);
    }

    /**
     * Fetch records that have <code>prix_pcm IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasSoins> fetchByPrixPcm(Long... values) {
        return fetch(BasSoins.BAS_SOINS.PRIX_PCM, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasSoins> fetchByIsDeleted(Boolean... values) {
        return fetch(BasSoins.BAS_SOINS.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasSoins> fetchByWhenDone(Timestamp... values) {
        return fetch(BasSoins.BAS_SOINS.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.BasSoins> fetchByWhoDone(String... values) {
        return fetch(BasSoins.BAS_SOINS.WHO_DONE, values);
    }
}
