/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.Examens;
import models.public_.tables.records.ExamensRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamensDao extends DAOImpl<ExamensRecord, models.public_.tables.pojos.Examens, Long> {

    /**
     * Create a new ExamensDao without any configuration
     */
    public ExamensDao() {
        super(Examens.EXAMENS, models.public_.tables.pojos.Examens.class);
    }

    /**
     * Create a new ExamensDao with an attached configuration
     */
    public ExamensDao(Configuration configuration) {
        super(Examens.EXAMENS, models.public_.tables.pojos.Examens.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.Examens object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchById(Long... values) {
        return fetch(Examens.EXAMENS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.public_.tables.pojos.Examens fetchOneById(Long value) {
        return fetchOne(Examens.EXAMENS.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByLibelle(String... values) {
        return fetch(Examens.EXAMENS.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>resultat IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByResultat(String... values) {
        return fetch(Examens.EXAMENS.RESULTAT, values);
    }

    /**
     * Fetch records that have <code>observation IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByObservation(String... values) {
        return fetch(Examens.EXAMENS.OBSERVATION, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByIsDeleted(Boolean... values) {
        return fetch(Examens.EXAMENS.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByWhenDone(Timestamp... values) {
        return fetch(Examens.EXAMENS.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>consultation IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByConsultation(Long... values) {
        return fetch(Examens.EXAMENS.CONSULTATION, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByWhoDone(String... values) {
        return fetch(Examens.EXAMENS.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>cout_examen IN (values)</code>
     */
    public List<models.public_.tables.pojos.Examens> fetchByCoutExamen(Long... values) {
        return fetch(Examens.EXAMENS.COUT_EXAMEN, values);
    }
}
