/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.FacturesDetails;
import models.public_.tables.records.FacturesDetailsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FacturesDetailsDao extends DAOImpl<FacturesDetailsRecord, models.public_.tables.pojos.FacturesDetails, Long> {

    /**
     * Create a new FacturesDetailsDao without any configuration
     */
    public FacturesDetailsDao() {
        super(FacturesDetails.FACTURES_DETAILS, models.public_.tables.pojos.FacturesDetails.class);
    }

    /**
     * Create a new FacturesDetailsDao with an attached configuration
     */
    public FacturesDetailsDao(Configuration configuration) {
        super(FacturesDetails.FACTURES_DETAILS, models.public_.tables.pojos.FacturesDetails.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.FacturesDetails object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchById(Long... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.public_.tables.pojos.FacturesDetails fetchOneById(Long value) {
        return fetchOne(FacturesDetails.FACTURES_DETAILS.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByLibelle(String... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>quantie IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByQuantie(Long... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.QUANTIE, values);
    }

    /**
     * Fetch records that have <code>prix_unitaire IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByPrixUnitaire(Long... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.PRIX_UNITAIRE, values);
    }

    /**
     * Fetch records that have <code>taux_tva IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByTauxTva(Long... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.TAUX_TVA, values);
    }

    /**
     * Fetch records that have <code>total_ttc IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByTotalTtc(Long... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.TOTAL_TTC, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByWhoDone(String... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByWhenDone(Timestamp... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByIsDeleted(Boolean... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>facture IN (values)</code>
     */
    public List<models.public_.tables.pojos.FacturesDetails> fetchByFacture(String... values) {
        return fetch(FacturesDetails.FACTURES_DETAILS.FACTURE, values);
    }
}
