/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.Partenaire;
import models.public_.tables.records.PartenaireRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartenaireDao extends DAOImpl<PartenaireRecord, models.public_.tables.pojos.Partenaire, Long> {

    /**
     * Create a new PartenaireDao without any configuration
     */
    public PartenaireDao() {
        super(Partenaire.PARTENAIRE, models.public_.tables.pojos.Partenaire.class);
    }

    /**
     * Create a new PartenaireDao with an attached configuration
     */
    public PartenaireDao(Configuration configuration) {
        super(Partenaire.PARTENAIRE, models.public_.tables.pojos.Partenaire.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.Partenaire object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.public_.tables.pojos.Partenaire> fetchById(Long... values) {
        return fetch(Partenaire.PARTENAIRE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.public_.tables.pojos.Partenaire fetchOneById(Long value) {
        return fetchOne(Partenaire.PARTENAIRE.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.public_.tables.pojos.Partenaire> fetchByLibelle(String... values) {
        return fetch(Partenaire.PARTENAIRE.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>taux_couverture IN (values)</code>
     */
    public List<models.public_.tables.pojos.Partenaire> fetchByTauxCouverture(Double... values) {
        return fetch(Partenaire.PARTENAIRE.TAUX_COUVERTURE, values);
    }

    /**
     * Fetch records that have <code>telephone IN (values)</code>
     */
    public List<models.public_.tables.pojos.Partenaire> fetchByTelephone(String... values) {
        return fetch(Partenaire.PARTENAIRE.TELEPHONE, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.public_.tables.pojos.Partenaire> fetchByIsDeleted(Boolean... values) {
        return fetch(Partenaire.PARTENAIRE.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.Partenaire> fetchByWhenDone(Timestamp... values) {
        return fetch(Partenaire.PARTENAIRE.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.Partenaire> fetchByWhoDone(String... values) {
        return fetch(Partenaire.PARTENAIRE.WHO_DONE, values);
    }
}
