/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.TypeConsultation;
import models.public_.tables.records.TypeConsultationRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeConsultationDao extends DAOImpl<TypeConsultationRecord, models.public_.tables.pojos.TypeConsultation, Long> {

    /**
     * Create a new TypeConsultationDao without any configuration
     */
    public TypeConsultationDao() {
        super(TypeConsultation.TYPE_CONSULTATION, models.public_.tables.pojos.TypeConsultation.class);
    }

    /**
     * Create a new TypeConsultationDao with an attached configuration
     */
    public TypeConsultationDao(Configuration configuration) {
        super(TypeConsultation.TYPE_CONSULTATION, models.public_.tables.pojos.TypeConsultation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.TypeConsultation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.public_.tables.pojos.TypeConsultation> fetchById(Long... values) {
        return fetch(TypeConsultation.TYPE_CONSULTATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.public_.tables.pojos.TypeConsultation fetchOneById(Long value) {
        return fetchOne(TypeConsultation.TYPE_CONSULTATION.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.public_.tables.pojos.TypeConsultation> fetchByLibelle(String... values) {
        return fetch(TypeConsultation.TYPE_CONSULTATION.LIBELLE, values);
    }

    /**
     * Fetch records that have <code>prix IN (values)</code>
     */
    public List<models.public_.tables.pojos.TypeConsultation> fetchByPrix(Long... values) {
        return fetch(TypeConsultation.TYPE_CONSULTATION.PRIX, values);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<models.public_.tables.pojos.TypeConsultation> fetchByIsDeleted(Boolean... values) {
        return fetch(TypeConsultation.TYPE_CONSULTATION.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.TypeConsultation> fetchByWhenDone(Timestamp... values) {
        return fetch(TypeConsultation.TYPE_CONSULTATION.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.TypeConsultation> fetchByWhoDone(String... values) {
        return fetch(TypeConsultation.TYPE_CONSULTATION.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>prix_pcm IN (values)</code>
     */
    public List<models.public_.tables.pojos.TypeConsultation> fetchByPrixPcm(Long... values) {
        return fetch(TypeConsultation.TYPE_CONSULTATION.PRIX_PCM, values);
    }
}
