/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FacturesDetails implements Serializable {

    private static final long serialVersionUID = -1080758880;

    private Long      id;
    private String    libelle;
    private Long      quantie;
    private Long      prixUnitaire;
    private Long      tauxTva;
    private Long      totalTtc;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   isDeleted;
    private String    facture;

    public FacturesDetails() {}

    public FacturesDetails(FacturesDetails value) {
        this.id = value.id;
        this.libelle = value.libelle;
        this.quantie = value.quantie;
        this.prixUnitaire = value.prixUnitaire;
        this.tauxTva = value.tauxTva;
        this.totalTtc = value.totalTtc;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.isDeleted = value.isDeleted;
        this.facture = value.facture;
    }

    public FacturesDetails(
        Long      id,
        String    libelle,
        Long      quantie,
        Long      prixUnitaire,
        Long      tauxTva,
        Long      totalTtc,
        String    whoDone,
        Timestamp whenDone,
        Boolean   isDeleted,
        String    facture
    ) {
        this.id = id;
        this.libelle = libelle;
        this.quantie = quantie;
        this.prixUnitaire = prixUnitaire;
        this.tauxTva = tauxTva;
        this.totalTtc = totalTtc;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.isDeleted = isDeleted;
        this.facture = facture;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public Long getQuantie() {
        return this.quantie;
    }

    public void setQuantie(Long quantie) {
        this.quantie = quantie;
    }

    public Long getPrixUnitaire() {
        return this.prixUnitaire;
    }

    public void setPrixUnitaire(Long prixUnitaire) {
        this.prixUnitaire = prixUnitaire;
    }

    public Long getTauxTva() {
        return this.tauxTva;
    }

    public void setTauxTva(Long tauxTva) {
        this.tauxTva = tauxTva;
    }

    public Long getTotalTtc() {
        return this.totalTtc;
    }

    public void setTotalTtc(Long totalTtc) {
        this.totalTtc = totalTtc;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getFacture() {
        return this.facture;
    }

    public void setFacture(String facture) {
        this.facture = facture;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FacturesDetails (");

        sb.append(id);
        sb.append(", ").append(libelle);
        sb.append(", ").append(quantie);
        sb.append(", ").append(prixUnitaire);
        sb.append(", ").append(tauxTva);
        sb.append(", ").append(totalTtc);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(facture);

        sb.append(")");
        return sb.toString();
    }
}
