/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rendezvous implements Serializable {

    private static final long serialVersionUID = -466683202;

    private Long      idRdv;
    private String    nomPatient;
    private String    numTel;
    private String    motifRdv;
    private Timestamp dateRdv;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   onDeleted;

    public Rendezvous() {}

    public Rendezvous(Rendezvous value) {
        this.idRdv = value.idRdv;
        this.nomPatient = value.nomPatient;
        this.numTel = value.numTel;
        this.motifRdv = value.motifRdv;
        this.dateRdv = value.dateRdv;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.onDeleted = value.onDeleted;
    }

    public Rendezvous(
        Long      idRdv,
        String    nomPatient,
        String    numTel,
        String    motifRdv,
        Timestamp dateRdv,
        String    whoDone,
        Timestamp whenDone,
        Boolean   onDeleted
    ) {
        this.idRdv = idRdv;
        this.nomPatient = nomPatient;
        this.numTel = numTel;
        this.motifRdv = motifRdv;
        this.dateRdv = dateRdv;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.onDeleted = onDeleted;
    }

    public Long getIdRdv() {
        return this.idRdv;
    }

    public void setIdRdv(Long idRdv) {
        this.idRdv = idRdv;
    }

    public String getNomPatient() {
        return this.nomPatient;
    }

    public void setNomPatient(String nomPatient) {
        this.nomPatient = nomPatient;
    }

    public String getNumTel() {
        return this.numTel;
    }

    public void setNumTel(String numTel) {
        this.numTel = numTel;
    }

    public String getMotifRdv() {
        return this.motifRdv;
    }

    public void setMotifRdv(String motifRdv) {
        this.motifRdv = motifRdv;
    }

    public Timestamp getDateRdv() {
        return this.dateRdv;
    }

    public void setDateRdv(Timestamp dateRdv) {
        this.dateRdv = dateRdv;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rendezvous (");

        sb.append(idRdv);
        sb.append(", ").append(nomPatient);
        sb.append(", ").append(numTel);
        sb.append(", ").append(motifRdv);
        sb.append(", ").append(dateRdv);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(onDeleted);

        sb.append(")");
        return sb.toString();
    }
}
