/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles implements Serializable {

    private static final long serialVersionUID = 430184408;

    private Long      idRole;
    private String    libelleRole;
    private String    whoDone;
    private Timestamp whenDone;
    private Boolean   onDeleted;

    public Roles() {}

    public Roles(Roles value) {
        this.idRole = value.idRole;
        this.libelleRole = value.libelleRole;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.onDeleted = value.onDeleted;
    }

    public Roles(
        Long      idRole,
        String    libelleRole,
        String    whoDone,
        Timestamp whenDone,
        Boolean   onDeleted
    ) {
        this.idRole = idRole;
        this.libelleRole = libelleRole;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.onDeleted = onDeleted;
    }

    public Long getIdRole() {
        return this.idRole;
    }

    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }

    public String getLibelleRole() {
        return this.libelleRole;
    }

    public void setLibelleRole(String libelleRole) {
        this.libelleRole = libelleRole;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public Boolean getOnDeleted() {
        return this.onDeleted;
    }

    public void setOnDeleted(Boolean onDeleted) {
        this.onDeleted = onDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Roles (");

        sb.append(idRole);
        sb.append(", ").append(libelleRole);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(onDeleted);

        sb.append(")");
        return sb.toString();
    }
}
