/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeConsultation implements Serializable {

    private static final long serialVersionUID = 1174241591;

    private Long      id;
    private String    libelle;
    private Long      prix;
    private Boolean   isDeleted;
    private Timestamp whenDone;
    private String    whoDone;
    private Long      prixPcm;

    public TypeConsultation() {}

    public TypeConsultation(TypeConsultation value) {
        this.id = value.id;
        this.libelle = value.libelle;
        this.prix = value.prix;
        this.isDeleted = value.isDeleted;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
        this.prixPcm = value.prixPcm;
    }

    public TypeConsultation(
        Long      id,
        String    libelle,
        Long      prix,
        Boolean   isDeleted,
        Timestamp whenDone,
        String    whoDone,
        Long      prixPcm
    ) {
        this.id = id;
        this.libelle = libelle;
        this.prix = prix;
        this.isDeleted = isDeleted;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
        this.prixPcm = prixPcm;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public Long getPrix() {
        return this.prix;
    }

    public void setPrix(Long prix) {
        this.prix = prix;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Long getPrixPcm() {
        return this.prixPcm;
    }

    public void setPrixPcm(Long prixPcm) {
        this.prixPcm = prixPcm;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TypeConsultation (");

        sb.append(id);
        sb.append(", ").append(libelle);
        sb.append(", ").append(prix);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(prixPcm);

        sb.append(")");
        return sb.toString();
    }
}
