/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -55736428;

    private String    login;
    private String    droit;
    private Boolean   etat;
    private String    passe;
    private String    whoDone;
    private Timestamp whenDone;
    private String    nomPrenom;

    public Users() {}

    public Users(Users value) {
        this.login = value.login;
        this.droit = value.droit;
        this.etat = value.etat;
        this.passe = value.passe;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.nomPrenom = value.nomPrenom;
    }

    public Users(
        String    login,
        String    droit,
        Boolean   etat,
        String    passe,
        String    whoDone,
        Timestamp whenDone,
        String    nomPrenom
    ) {
        this.login = login;
        this.droit = droit;
        this.etat = etat;
        this.passe = passe;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.nomPrenom = nomPrenom;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getDroit() {
        return this.droit;
    }

    public void setDroit(String droit) {
        this.droit = droit;
    }

    public Boolean getEtat() {
        return this.etat;
    }

    public void setEtat(Boolean etat) {
        this.etat = etat;
    }

    public String getPasse() {
        return this.passe;
    }

    public void setPasse(String passe) {
        this.passe = passe;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getNomPrenom() {
        return this.nomPrenom;
    }

    public void setNomPrenom(String nomPrenom) {
        this.nomPrenom = nomPrenom;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(login);
        sb.append(", ").append(droit);
        sb.append(", ").append(etat);
        sb.append(", ").append(passe);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(nomPrenom);

        sb.append(")");
        return sb.toString();
    }
}
