/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VOrdononce implements Serializable {

    private static final long serialVersionUID = -364197491;

    private Long      id;
    private String    libelle;
    private Long      consultation;
    private String    numeroConsul;
    private Long      age;
    private Long      idPatient;
    private String    telPatient;
    private String    nomPatient;
    private Timestamp dateConsultation;
    private Boolean   isDeleted;
    private Timestamp whenDone;
    private String    consultations;
    private String    whoDone;
    private Boolean   isSoin;
    private Long      montant;

    public VOrdononce() {}

    public VOrdononce(VOrdononce value) {
        this.id = value.id;
        this.libelle = value.libelle;
        this.consultation = value.consultation;
        this.numeroConsul = value.numeroConsul;
        this.age = value.age;
        this.idPatient = value.idPatient;
        this.telPatient = value.telPatient;
        this.nomPatient = value.nomPatient;
        this.dateConsultation = value.dateConsultation;
        this.isDeleted = value.isDeleted;
        this.whenDone = value.whenDone;
        this.consultations = value.consultations;
        this.whoDone = value.whoDone;
        this.isSoin = value.isSoin;
        this.montant = value.montant;
    }

    public VOrdononce(
        Long      id,
        String    libelle,
        Long      consultation,
        String    numeroConsul,
        Long      age,
        Long      idPatient,
        String    telPatient,
        String    nomPatient,
        Timestamp dateConsultation,
        Boolean   isDeleted,
        Timestamp whenDone,
        String    consultations,
        String    whoDone,
        Boolean   isSoin,
        Long      montant
    ) {
        this.id = id;
        this.libelle = libelle;
        this.consultation = consultation;
        this.numeroConsul = numeroConsul;
        this.age = age;
        this.idPatient = idPatient;
        this.telPatient = telPatient;
        this.nomPatient = nomPatient;
        this.dateConsultation = dateConsultation;
        this.isDeleted = isDeleted;
        this.whenDone = whenDone;
        this.consultations = consultations;
        this.whoDone = whoDone;
        this.isSoin = isSoin;
        this.montant = montant;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public Long getConsultation() {
        return this.consultation;
    }

    public void setConsultation(Long consultation) {
        this.consultation = consultation;
    }

    public String getNumeroConsul() {
        return this.numeroConsul;
    }

    public void setNumeroConsul(String numeroConsul) {
        this.numeroConsul = numeroConsul;
    }

    public Long getAge() {
        return this.age;
    }

    public void setAge(Long age) {
        this.age = age;
    }

    public Long getIdPatient() {
        return this.idPatient;
    }

    public void setIdPatient(Long idPatient) {
        this.idPatient = idPatient;
    }

    public String getTelPatient() {
        return this.telPatient;
    }

    public void setTelPatient(String telPatient) {
        this.telPatient = telPatient;
    }

    public String getNomPatient() {
        return this.nomPatient;
    }

    public void setNomPatient(String nomPatient) {
        this.nomPatient = nomPatient;
    }

    public Timestamp getDateConsultation() {
        return this.dateConsultation;
    }

    public void setDateConsultation(Timestamp dateConsultation) {
        this.dateConsultation = dateConsultation;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getConsultations() {
        return this.consultations;
    }

    public void setConsultations(String consultations) {
        this.consultations = consultations;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Boolean getIsSoin() {
        return this.isSoin;
    }

    public void setIsSoin(Boolean isSoin) {
        this.isSoin = isSoin;
    }

    public Long getMontant() {
        return this.montant;
    }

    public void setMontant(Long montant) {
        this.montant = montant;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VOrdononce (");

        sb.append(id);
        sb.append(", ").append(libelle);
        sb.append(", ").append(consultation);
        sb.append(", ").append(numeroConsul);
        sb.append(", ").append(age);
        sb.append(", ").append(idPatient);
        sb.append(", ").append(telPatient);
        sb.append(", ").append(nomPatient);
        sb.append(", ").append(dateConsultation);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(consultations);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(isSoin);
        sb.append(", ").append(montant);

        sb.append(")");
        return sb.toString();
    }
}
