/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VsExamMedecin implements Serializable {

    private static final long serialVersionUID = 852212618;

    private String    refFacture;
    private String    nomP;
    private String    prenomP;
    private String    categorie;
    private String    telephone;
    private Long      montant;
    private Timestamp whenDone;

    public VsExamMedecin() {}

    public VsExamMedecin(VsExamMedecin value) {
        this.refFacture = value.refFacture;
        this.nomP = value.nomP;
        this.prenomP = value.prenomP;
        this.categorie = value.categorie;
        this.telephone = value.telephone;
        this.montant = value.montant;
        this.whenDone = value.whenDone;
    }

    public VsExamMedecin(
        String    refFacture,
        String    nomP,
        String    prenomP,
        String    categorie,
        String    telephone,
        Long      montant,
        Timestamp whenDone
    ) {
        this.refFacture = refFacture;
        this.nomP = nomP;
        this.prenomP = prenomP;
        this.categorie = categorie;
        this.telephone = telephone;
        this.montant = montant;
        this.whenDone = whenDone;
    }

    public String getRefFacture() {
        return this.refFacture;
    }

    public void setRefFacture(String refFacture) {
        this.refFacture = refFacture;
    }

    public String getNomP() {
        return this.nomP;
    }

    public void setNomP(String nomP) {
        this.nomP = nomP;
    }

    public String getPrenomP() {
        return this.prenomP;
    }

    public void setPrenomP(String prenomP) {
        this.prenomP = prenomP;
    }

    public String getCategorie() {
        return this.categorie;
    }

    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public Long getMontant() {
        return this.montant;
    }

    public void setMontant(Long montant) {
        this.montant = montant;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VsExamMedecin (");

        sb.append(refFacture);
        sb.append(", ").append(nomP);
        sb.append(", ").append(prenomP);
        sb.append(", ").append(categorie);
        sb.append(", ").append(telephone);
        sb.append(", ").append(montant);
        sb.append(", ").append(whenDone);

        sb.append(")");
        return sb.toString();
    }
}
