/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Consultations implements Serializable {

    private static final long serialVersionUID = -715920458;

    private Long      id;
    private Long      typeConsultation;
    private Long      patient;
    private String    telPatient;
    private Long      cout;
    private Long      sommeRecu;
    private Long      sommeRemise;
    private Boolean   isClosed;
    private Boolean   isDeleted;
    private Timestamp whenDone;
    private String    numeroConsul;
    private String    whoDone;
    private String    nomPrenomPatient;
    private String    montantEnLettre;
    private String    observation;
    private Timestamp dateRdv;
    private Double    tauxCouverture;
    private Long      medecinTraitrant;
    private String    structurePatient;
    private String    rNbrFact;
    private String    rNbrTotal;
    private String    rTypeFact;
    private String    rDateFact;
    private String    rNumDispositifFact;
    private String    rNifFact;
    private String    rSignatureFact;

    public Consultations() {}

    public Consultations(Consultations value) {
        this.id = value.id;
        this.typeConsultation = value.typeConsultation;
        this.patient = value.patient;
        this.telPatient = value.telPatient;
        this.cout = value.cout;
        this.sommeRecu = value.sommeRecu;
        this.sommeRemise = value.sommeRemise;
        this.isClosed = value.isClosed;
        this.isDeleted = value.isDeleted;
        this.whenDone = value.whenDone;
        this.numeroConsul = value.numeroConsul;
        this.whoDone = value.whoDone;
        this.nomPrenomPatient = value.nomPrenomPatient;
        this.montantEnLettre = value.montantEnLettre;
        this.observation = value.observation;
        this.dateRdv = value.dateRdv;
        this.tauxCouverture = value.tauxCouverture;
        this.medecinTraitrant = value.medecinTraitrant;
        this.structurePatient = value.structurePatient;
        this.rNbrFact = value.rNbrFact;
        this.rNbrTotal = value.rNbrTotal;
        this.rTypeFact = value.rTypeFact;
        this.rDateFact = value.rDateFact;
        this.rNumDispositifFact = value.rNumDispositifFact;
        this.rNifFact = value.rNifFact;
        this.rSignatureFact = value.rSignatureFact;
    }

    public Consultations(
        Long      id,
        Long      typeConsultation,
        Long      patient,
        String    telPatient,
        Long      cout,
        Long      sommeRecu,
        Long      sommeRemise,
        Boolean   isClosed,
        Boolean   isDeleted,
        Timestamp whenDone,
        String    numeroConsul,
        String    whoDone,
        String    nomPrenomPatient,
        String    montantEnLettre,
        String    observation,
        Timestamp dateRdv,
        Double    tauxCouverture,
        Long      medecinTraitrant,
        String    structurePatient,
        String    rNbrFact,
        String    rNbrTotal,
        String    rTypeFact,
        String    rDateFact,
        String    rNumDispositifFact,
        String    rNifFact,
        String    rSignatureFact
    ) {
        this.id = id;
        this.typeConsultation = typeConsultation;
        this.patient = patient;
        this.telPatient = telPatient;
        this.cout = cout;
        this.sommeRecu = sommeRecu;
        this.sommeRemise = sommeRemise;
        this.isClosed = isClosed;
        this.isDeleted = isDeleted;
        this.whenDone = whenDone;
        this.numeroConsul = numeroConsul;
        this.whoDone = whoDone;
        this.nomPrenomPatient = nomPrenomPatient;
        this.montantEnLettre = montantEnLettre;
        this.observation = observation;
        this.dateRdv = dateRdv;
        this.tauxCouverture = tauxCouverture;
        this.medecinTraitrant = medecinTraitrant;
        this.structurePatient = structurePatient;
        this.rNbrFact = rNbrFact;
        this.rNbrTotal = rNbrTotal;
        this.rTypeFact = rTypeFact;
        this.rDateFact = rDateFact;
        this.rNumDispositifFact = rNumDispositifFact;
        this.rNifFact = rNifFact;
        this.rSignatureFact = rSignatureFact;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTypeConsultation() {
        return this.typeConsultation;
    }

    public void setTypeConsultation(Long typeConsultation) {
        this.typeConsultation = typeConsultation;
    }

    public Long getPatient() {
        return this.patient;
    }

    public void setPatient(Long patient) {
        this.patient = patient;
    }

    public String getTelPatient() {
        return this.telPatient;
    }

    public void setTelPatient(String telPatient) {
        this.telPatient = telPatient;
    }

    public Long getCout() {
        return this.cout;
    }

    public void setCout(Long cout) {
        this.cout = cout;
    }

    public Long getSommeRecu() {
        return this.sommeRecu;
    }

    public void setSommeRecu(Long sommeRecu) {
        this.sommeRecu = sommeRecu;
    }

    public Long getSommeRemise() {
        return this.sommeRemise;
    }

    public void setSommeRemise(Long sommeRemise) {
        this.sommeRemise = sommeRemise;
    }

    public Boolean getIsClosed() {
        return this.isClosed;
    }

    public void setIsClosed(Boolean isClosed) {
        this.isClosed = isClosed;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getNumeroConsul() {
        return this.numeroConsul;
    }

    public void setNumeroConsul(String numeroConsul) {
        this.numeroConsul = numeroConsul;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public String getNomPrenomPatient() {
        return this.nomPrenomPatient;
    }

    public void setNomPrenomPatient(String nomPrenomPatient) {
        this.nomPrenomPatient = nomPrenomPatient;
    }

    public String getMontantEnLettre() {
        return this.montantEnLettre;
    }

    public void setMontantEnLettre(String montantEnLettre) {
        this.montantEnLettre = montantEnLettre;
    }

    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public Timestamp getDateRdv() {
        return this.dateRdv;
    }

    public void setDateRdv(Timestamp dateRdv) {
        this.dateRdv = dateRdv;
    }

    public Double getTauxCouverture() {
        return this.tauxCouverture;
    }

    public void setTauxCouverture(Double tauxCouverture) {
        this.tauxCouverture = tauxCouverture;
    }

    public Long getMedecinTraitrant() {
        return this.medecinTraitrant;
    }

    public void setMedecinTraitrant(Long medecinTraitrant) {
        this.medecinTraitrant = medecinTraitrant;
    }

    public String getStructurePatient() {
        return this.structurePatient;
    }

    public void setStructurePatient(String structurePatient) {
        this.structurePatient = structurePatient;
    }

    public String getRNbrFact() {
        return this.rNbrFact;
    }

    public void setRNbrFact(String rNbrFact) {
        this.rNbrFact = rNbrFact;
    }

    public String getRNbrTotal() {
        return this.rNbrTotal;
    }

    public void setRNbrTotal(String rNbrTotal) {
        this.rNbrTotal = rNbrTotal;
    }

    public String getRTypeFact() {
        return this.rTypeFact;
    }

    public void setRTypeFact(String rTypeFact) {
        this.rTypeFact = rTypeFact;
    }

    public String getRDateFact() {
        return this.rDateFact;
    }

    public void setRDateFact(String rDateFact) {
        this.rDateFact = rDateFact;
    }

    public String getRNumDispositifFact() {
        return this.rNumDispositifFact;
    }

    public void setRNumDispositifFact(String rNumDispositifFact) {
        this.rNumDispositifFact = rNumDispositifFact;
    }

    public String getRNifFact() {
        return this.rNifFact;
    }

    public void setRNifFact(String rNifFact) {
        this.rNifFact = rNifFact;
    }

    public String getRSignatureFact() {
        return this.rSignatureFact;
    }

    public void setRSignatureFact(String rSignatureFact) {
        this.rSignatureFact = rSignatureFact;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Consultations (");

        sb.append(id);
        sb.append(", ").append(typeConsultation);
        sb.append(", ").append(patient);
        sb.append(", ").append(telPatient);
        sb.append(", ").append(cout);
        sb.append(", ").append(sommeRecu);
        sb.append(", ").append(sommeRemise);
        sb.append(", ").append(isClosed);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(numeroConsul);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(nomPrenomPatient);
        sb.append(", ").append(montantEnLettre);
        sb.append(", ").append(observation);
        sb.append(", ").append(dateRdv);
        sb.append(", ").append(tauxCouverture);
        sb.append(", ").append(medecinTraitrant);
        sb.append(", ").append(structurePatient);
        sb.append(", ").append(rNbrFact);
        sb.append(", ").append(rNbrTotal);
        sb.append(", ").append(rTypeFact);
        sb.append(", ").append(rDateFact);
        sb.append(", ").append(rNumDispositifFact);
        sb.append(", ").append(rNifFact);
        sb.append(", ").append(rSignatureFact);

        sb.append(")");
        return sb.toString();
    }
}
