/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InfosMedicale implements Serializable {

    private static final long serialVersionUID = -1452963343;

    private Long      id;
    private String    libelle;
    private Boolean   isDeleted;
    private Boolean   isAnt;
    private Long      patient;
    private Timestamp whenDone;
    private String    whoDone;
    private String    resultat;

    public InfosMedicale() {}

    public InfosMedicale(InfosMedicale value) {
        this.id = value.id;
        this.libelle = value.libelle;
        this.isDeleted = value.isDeleted;
        this.isAnt = value.isAnt;
        this.patient = value.patient;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
        this.resultat = value.resultat;
    }

    public InfosMedicale(
        Long      id,
        String    libelle,
        Boolean   isDeleted,
        Boolean   isAnt,
        Long      patient,
        Timestamp whenDone,
        String    whoDone,
        String    resultat
    ) {
        this.id = id;
        this.libelle = libelle;
        this.isDeleted = isDeleted;
        this.isAnt = isAnt;
        this.patient = patient;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
        this.resultat = resultat;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Boolean getIsAnt() {
        return this.isAnt;
    }

    public void setIsAnt(Boolean isAnt) {
        this.isAnt = isAnt;
    }

    public Long getPatient() {
        return this.patient;
    }

    public void setPatient(Long patient) {
        this.patient = patient;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public String getResultat() {
        return this.resultat;
    }

    public void setResultat(String resultat) {
        this.resultat = resultat;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InfosMedicale (");

        sb.append(id);
        sb.append(", ").append(libelle);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(isAnt);
        sb.append(", ").append(patient);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(resultat);

        sb.append(")");
        return sb.toString();
    }
}
