/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedecinPatient implements Serializable {

    private static final long serialVersionUID = 105359239;

    private Long id;
    private Long patientId;
    private Long medecinId;

    public MedecinPatient() {}

    public MedecinPatient(MedecinPatient value) {
        this.id = value.id;
        this.patientId = value.patientId;
        this.medecinId = value.medecinId;
    }

    public MedecinPatient(
        Long id,
        Long patientId,
        Long medecinId
    ) {
        this.id = id;
        this.patientId = patientId;
        this.medecinId = medecinId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPatientId() {
        return this.patientId;
    }

    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    public Long getMedecinId() {
        return this.medecinId;
    }

    public void setMedecinId(Long medecinId) {
        this.medecinId = medecinId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MedecinPatient (");

        sb.append(id);
        sb.append(", ").append(patientId);
        sb.append(", ").append(medecinId);

        sb.append(")");
        return sb.toString();
    }
}
