/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Personnels implements Serializable {

    private static final long serialVersionUID = 1173932399;

    private Long      id;
    private String    nomP;
    private String    prenomP;
    private String    categorie;
    private String    telephone;
    private String    adresse;
    private Boolean   isDeleted;
    private Timestamp whenDone;
    private String    whoDone;

    public Personnels() {}

    public Personnels(Personnels value) {
        this.id = value.id;
        this.nomP = value.nomP;
        this.prenomP = value.prenomP;
        this.categorie = value.categorie;
        this.telephone = value.telephone;
        this.adresse = value.adresse;
        this.isDeleted = value.isDeleted;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
    }

    public Personnels(
        Long      id,
        String    nomP,
        String    prenomP,
        String    categorie,
        String    telephone,
        String    adresse,
        Boolean   isDeleted,
        Timestamp whenDone,
        String    whoDone
    ) {
        this.id = id;
        this.nomP = nomP;
        this.prenomP = prenomP;
        this.categorie = categorie;
        this.telephone = telephone;
        this.adresse = adresse;
        this.isDeleted = isDeleted;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomP() {
        return this.nomP;
    }

    public void setNomP(String nomP) {
        this.nomP = nomP;
    }

    public String getPrenomP() {
        return this.prenomP;
    }

    public void setPrenomP(String prenomP) {
        this.prenomP = prenomP;
    }

    public String getCategorie() {
        return this.categorie;
    }

    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getAdresse() {
        return this.adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Personnels (");

        sb.append(id);
        sb.append(", ").append(nomP);
        sb.append(", ").append(prenomP);
        sb.append(", ").append(categorie);
        sb.append(", ").append(telephone);
        sb.append(", ").append(adresse);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);

        sb.append(")");
        return sb.toString();
    }
}
