/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SConsultations implements Serializable {

    private static final long serialVersionUID = -1905150139;

    private String nomPartenaire;
    private Long   nombreDeConsultations;

    public SConsultations() {}

    public SConsultations(SConsultations value) {
        this.nomPartenaire = value.nomPartenaire;
        this.nombreDeConsultations = value.nombreDeConsultations;
    }

    public SConsultations(
        String nomPartenaire,
        Long   nombreDeConsultations
    ) {
        this.nomPartenaire = nomPartenaire;
        this.nombreDeConsultations = nombreDeConsultations;
    }

    public String getNomPartenaire() {
        return this.nomPartenaire;
    }

    public void setNomPartenaire(String nomPartenaire) {
        this.nomPartenaire = nomPartenaire;
    }

    public Long getNombreDeConsultations() {
        return this.nombreDeConsultations;
    }

    public void setNombreDeConsultations(Long nombreDeConsultations) {
        this.nombreDeConsultations = nombreDeConsultations;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SConsultations (");

        sb.append(nomPartenaire);
        sb.append(", ").append(nombreDeConsultations);

        sb.append(")");
        return sb.toString();
    }
}
