/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VConsultations implements Serializable {

    private static final long serialVersionUID = 370392511;

    private Long      id;
    private String    numeroConsul;
    private Long      typeConsultation;
    private String    libelleType;
    private Long      patient;
    private Long      idPatient;
    private String    nomPatient;
    private Long      age;
    private Long      partenaireId;
    private String    nomPartenaire;
    private String    structurePatient;
    private Double    tauxCouverture;
    private String    telPatient;
    private Long      medecinTraitrant;
    private String    medecin;
    private Long      prixConsultation;
    private Long      montantConsultation;
    private String    montantEnLettre;
    private Long      sommeRecu;
    private Long      sommeRemise;
    private Double    montantPrisEnCharge;
    private Double    montantAPayer;
    private String    observation;
    private Timestamp dateRdv;
    private Boolean   isClosed;
    private Boolean   isDeleted;
    private Timestamp whenDone;
    private String    whoDone;
    private String    rNbrFact;
    private String    rNbrTotal;
    private String    rTypeFact;
    private String    rDateFact;
    private String    rNumDispositifFact;
    private String    rNifFact;
    private String    rSignatureFact;

    public VConsultations() {}

    public VConsultations(VConsultations value) {
        this.id = value.id;
        this.numeroConsul = value.numeroConsul;
        this.typeConsultation = value.typeConsultation;
        this.libelleType = value.libelleType;
        this.patient = value.patient;
        this.idPatient = value.idPatient;
        this.nomPatient = value.nomPatient;
        this.age = value.age;
        this.partenaireId = value.partenaireId;
        this.nomPartenaire = value.nomPartenaire;
        this.structurePatient = value.structurePatient;
        this.tauxCouverture = value.tauxCouverture;
        this.telPatient = value.telPatient;
        this.medecinTraitrant = value.medecinTraitrant;
        this.medecin = value.medecin;
        this.prixConsultation = value.prixConsultation;
        this.montantConsultation = value.montantConsultation;
        this.montantEnLettre = value.montantEnLettre;
        this.sommeRecu = value.sommeRecu;
        this.sommeRemise = value.sommeRemise;
        this.montantPrisEnCharge = value.montantPrisEnCharge;
        this.montantAPayer = value.montantAPayer;
        this.observation = value.observation;
        this.dateRdv = value.dateRdv;
        this.isClosed = value.isClosed;
        this.isDeleted = value.isDeleted;
        this.whenDone = value.whenDone;
        this.whoDone = value.whoDone;
        this.rNbrFact = value.rNbrFact;
        this.rNbrTotal = value.rNbrTotal;
        this.rTypeFact = value.rTypeFact;
        this.rDateFact = value.rDateFact;
        this.rNumDispositifFact = value.rNumDispositifFact;
        this.rNifFact = value.rNifFact;
        this.rSignatureFact = value.rSignatureFact;
    }

    public VConsultations(
        Long      id,
        String    numeroConsul,
        Long      typeConsultation,
        String    libelleType,
        Long      patient,
        Long      idPatient,
        String    nomPatient,
        Long      age,
        Long      partenaireId,
        String    nomPartenaire,
        String    structurePatient,
        Double    tauxCouverture,
        String    telPatient,
        Long      medecinTraitrant,
        String    medecin,
        Long      prixConsultation,
        Long      montantConsultation,
        String    montantEnLettre,
        Long      sommeRecu,
        Long      sommeRemise,
        Double    montantPrisEnCharge,
        Double    montantAPayer,
        String    observation,
        Timestamp dateRdv,
        Boolean   isClosed,
        Boolean   isDeleted,
        Timestamp whenDone,
        String    whoDone,
        String    rNbrFact,
        String    rNbrTotal,
        String    rTypeFact,
        String    rDateFact,
        String    rNumDispositifFact,
        String    rNifFact,
        String    rSignatureFact
    ) {
        this.id = id;
        this.numeroConsul = numeroConsul;
        this.typeConsultation = typeConsultation;
        this.libelleType = libelleType;
        this.patient = patient;
        this.idPatient = idPatient;
        this.nomPatient = nomPatient;
        this.age = age;
        this.partenaireId = partenaireId;
        this.nomPartenaire = nomPartenaire;
        this.structurePatient = structurePatient;
        this.tauxCouverture = tauxCouverture;
        this.telPatient = telPatient;
        this.medecinTraitrant = medecinTraitrant;
        this.medecin = medecin;
        this.prixConsultation = prixConsultation;
        this.montantConsultation = montantConsultation;
        this.montantEnLettre = montantEnLettre;
        this.sommeRecu = sommeRecu;
        this.sommeRemise = sommeRemise;
        this.montantPrisEnCharge = montantPrisEnCharge;
        this.montantAPayer = montantAPayer;
        this.observation = observation;
        this.dateRdv = dateRdv;
        this.isClosed = isClosed;
        this.isDeleted = isDeleted;
        this.whenDone = whenDone;
        this.whoDone = whoDone;
        this.rNbrFact = rNbrFact;
        this.rNbrTotal = rNbrTotal;
        this.rTypeFact = rTypeFact;
        this.rDateFact = rDateFact;
        this.rNumDispositifFact = rNumDispositifFact;
        this.rNifFact = rNifFact;
        this.rSignatureFact = rSignatureFact;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNumeroConsul() {
        return this.numeroConsul;
    }

    public void setNumeroConsul(String numeroConsul) {
        this.numeroConsul = numeroConsul;
    }

    public Long getTypeConsultation() {
        return this.typeConsultation;
    }

    public void setTypeConsultation(Long typeConsultation) {
        this.typeConsultation = typeConsultation;
    }

    public String getLibelleType() {
        return this.libelleType;
    }

    public void setLibelleType(String libelleType) {
        this.libelleType = libelleType;
    }

    public Long getPatient() {
        return this.patient;
    }

    public void setPatient(Long patient) {
        this.patient = patient;
    }

    public Long getIdPatient() {
        return this.idPatient;
    }

    public void setIdPatient(Long idPatient) {
        this.idPatient = idPatient;
    }

    public String getNomPatient() {
        return this.nomPatient;
    }

    public void setNomPatient(String nomPatient) {
        this.nomPatient = nomPatient;
    }

    public Long getAge() {
        return this.age;
    }

    public void setAge(Long age) {
        this.age = age;
    }

    public Long getPartenaireId() {
        return this.partenaireId;
    }

    public void setPartenaireId(Long partenaireId) {
        this.partenaireId = partenaireId;
    }

    public String getNomPartenaire() {
        return this.nomPartenaire;
    }

    public void setNomPartenaire(String nomPartenaire) {
        this.nomPartenaire = nomPartenaire;
    }

    public String getStructurePatient() {
        return this.structurePatient;
    }

    public void setStructurePatient(String structurePatient) {
        this.structurePatient = structurePatient;
    }

    public Double getTauxCouverture() {
        return this.tauxCouverture;
    }

    public void setTauxCouverture(Double tauxCouverture) {
        this.tauxCouverture = tauxCouverture;
    }

    public String getTelPatient() {
        return this.telPatient;
    }

    public void setTelPatient(String telPatient) {
        this.telPatient = telPatient;
    }

    public Long getMedecinTraitrant() {
        return this.medecinTraitrant;
    }

    public void setMedecinTraitrant(Long medecinTraitrant) {
        this.medecinTraitrant = medecinTraitrant;
    }

    public String getMedecin() {
        return this.medecin;
    }

    public void setMedecin(String medecin) {
        this.medecin = medecin;
    }

    public Long getPrixConsultation() {
        return this.prixConsultation;
    }

    public void setPrixConsultation(Long prixConsultation) {
        this.prixConsultation = prixConsultation;
    }

    public Long getMontantConsultation() {
        return this.montantConsultation;
    }

    public void setMontantConsultation(Long montantConsultation) {
        this.montantConsultation = montantConsultation;
    }

    public String getMontantEnLettre() {
        return this.montantEnLettre;
    }

    public void setMontantEnLettre(String montantEnLettre) {
        this.montantEnLettre = montantEnLettre;
    }

    public Long getSommeRecu() {
        return this.sommeRecu;
    }

    public void setSommeRecu(Long sommeRecu) {
        this.sommeRecu = sommeRecu;
    }

    public Long getSommeRemise() {
        return this.sommeRemise;
    }

    public void setSommeRemise(Long sommeRemise) {
        this.sommeRemise = sommeRemise;
    }

    public Double getMontantPrisEnCharge() {
        return this.montantPrisEnCharge;
    }

    public void setMontantPrisEnCharge(Double montantPrisEnCharge) {
        this.montantPrisEnCharge = montantPrisEnCharge;
    }

    public Double getMontantAPayer() {
        return this.montantAPayer;
    }

    public void setMontantAPayer(Double montantAPayer) {
        this.montantAPayer = montantAPayer;
    }

    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public Timestamp getDateRdv() {
        return this.dateRdv;
    }

    public void setDateRdv(Timestamp dateRdv) {
        this.dateRdv = dateRdv;
    }

    public Boolean getIsClosed() {
        return this.isClosed;
    }

    public void setIsClosed(Boolean isClosed) {
        this.isClosed = isClosed;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public String getRNbrFact() {
        return this.rNbrFact;
    }

    public void setRNbrFact(String rNbrFact) {
        this.rNbrFact = rNbrFact;
    }

    public String getRNbrTotal() {
        return this.rNbrTotal;
    }

    public void setRNbrTotal(String rNbrTotal) {
        this.rNbrTotal = rNbrTotal;
    }

    public String getRTypeFact() {
        return this.rTypeFact;
    }

    public void setRTypeFact(String rTypeFact) {
        this.rTypeFact = rTypeFact;
    }

    public String getRDateFact() {
        return this.rDateFact;
    }

    public void setRDateFact(String rDateFact) {
        this.rDateFact = rDateFact;
    }

    public String getRNumDispositifFact() {
        return this.rNumDispositifFact;
    }

    public void setRNumDispositifFact(String rNumDispositifFact) {
        this.rNumDispositifFact = rNumDispositifFact;
    }

    public String getRNifFact() {
        return this.rNifFact;
    }

    public void setRNifFact(String rNifFact) {
        this.rNifFact = rNifFact;
    }

    public String getRSignatureFact() {
        return this.rSignatureFact;
    }

    public void setRSignatureFact(String rSignatureFact) {
        this.rSignatureFact = rSignatureFact;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VConsultations (");

        sb.append(id);
        sb.append(", ").append(numeroConsul);
        sb.append(", ").append(typeConsultation);
        sb.append(", ").append(libelleType);
        sb.append(", ").append(patient);
        sb.append(", ").append(idPatient);
        sb.append(", ").append(nomPatient);
        sb.append(", ").append(age);
        sb.append(", ").append(partenaireId);
        sb.append(", ").append(nomPartenaire);
        sb.append(", ").append(structurePatient);
        sb.append(", ").append(tauxCouverture);
        sb.append(", ").append(telPatient);
        sb.append(", ").append(medecinTraitrant);
        sb.append(", ").append(medecin);
        sb.append(", ").append(prixConsultation);
        sb.append(", ").append(montantConsultation);
        sb.append(", ").append(montantEnLettre);
        sb.append(", ").append(sommeRecu);
        sb.append(", ").append(sommeRemise);
        sb.append(", ").append(montantPrisEnCharge);
        sb.append(", ").append(montantAPayer);
        sb.append(", ").append(observation);
        sb.append(", ").append(dateRdv);
        sb.append(", ").append(isClosed);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(rNbrFact);
        sb.append(", ").append(rNbrTotal);
        sb.append(", ").append(rTypeFact);
        sb.append(", ").append(rDateFact);
        sb.append(", ").append(rNumDispositifFact);
        sb.append(", ").append(rNifFact);
        sb.append(", ").append(rSignatureFact);

        sb.append(")");
        return sb.toString();
    }
}
