/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VSoins implements Serializable {

    private static final long serialVersionUID = -80342932;

    private Long      id;
    private String    libelle;
    private Long      consultation;
    private String    numeroConsul;
    private Long      age;
    private Long      idPatient;
    private String    telPatient;
    private String    nomPatient;
    private Timestamp dateConsultation;
    private Boolean   isDeleted;
    private Timestamp whenDone;
    private String    consultations;
    private String    whoDone;
    private Boolean   isSoin;
    private Long      montant;
    private Long      nombre;
    private Long      total;
    private Long      medecin;
    private String    nomPartenaire;
    private Long      partenaireId;
    private Double    tauxCouverture;
    private Double    montantPrisEnCharge;
    private Double    montantNetAPayer;

    public VSoins() {}

    public VSoins(VSoins value) {
        this.id = value.id;
        this.libelle = value.libelle;
        this.consultation = value.consultation;
        this.numeroConsul = value.numeroConsul;
        this.age = value.age;
        this.idPatient = value.idPatient;
        this.telPatient = value.telPatient;
        this.nomPatient = value.nomPatient;
        this.dateConsultation = value.dateConsultation;
        this.isDeleted = value.isDeleted;
        this.whenDone = value.whenDone;
        this.consultations = value.consultations;
        this.whoDone = value.whoDone;
        this.isSoin = value.isSoin;
        this.montant = value.montant;
        this.nombre = value.nombre;
        this.total = value.total;
        this.medecin = value.medecin;
        this.nomPartenaire = value.nomPartenaire;
        this.partenaireId = value.partenaireId;
        this.tauxCouverture = value.tauxCouverture;
        this.montantPrisEnCharge = value.montantPrisEnCharge;
        this.montantNetAPayer = value.montantNetAPayer;
    }

    public VSoins(
        Long      id,
        String    libelle,
        Long      consultation,
        String    numeroConsul,
        Long      age,
        Long      idPatient,
        String    telPatient,
        String    nomPatient,
        Timestamp dateConsultation,
        Boolean   isDeleted,
        Timestamp whenDone,
        String    consultations,
        String    whoDone,
        Boolean   isSoin,
        Long      montant,
        Long      nombre,
        Long      total,
        Long      medecin,
        String    nomPartenaire,
        Long      partenaireId,
        Double    tauxCouverture,
        Double    montantPrisEnCharge,
        Double    montantNetAPayer
    ) {
        this.id = id;
        this.libelle = libelle;
        this.consultation = consultation;
        this.numeroConsul = numeroConsul;
        this.age = age;
        this.idPatient = idPatient;
        this.telPatient = telPatient;
        this.nomPatient = nomPatient;
        this.dateConsultation = dateConsultation;
        this.isDeleted = isDeleted;
        this.whenDone = whenDone;
        this.consultations = consultations;
        this.whoDone = whoDone;
        this.isSoin = isSoin;
        this.montant = montant;
        this.nombre = nombre;
        this.total = total;
        this.medecin = medecin;
        this.nomPartenaire = nomPartenaire;
        this.partenaireId = partenaireId;
        this.tauxCouverture = tauxCouverture;
        this.montantPrisEnCharge = montantPrisEnCharge;
        this.montantNetAPayer = montantNetAPayer;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public Long getConsultation() {
        return this.consultation;
    }

    public void setConsultation(Long consultation) {
        this.consultation = consultation;
    }

    public String getNumeroConsul() {
        return this.numeroConsul;
    }

    public void setNumeroConsul(String numeroConsul) {
        this.numeroConsul = numeroConsul;
    }

    public Long getAge() {
        return this.age;
    }

    public void setAge(Long age) {
        this.age = age;
    }

    public Long getIdPatient() {
        return this.idPatient;
    }

    public void setIdPatient(Long idPatient) {
        this.idPatient = idPatient;
    }

    public String getTelPatient() {
        return this.telPatient;
    }

    public void setTelPatient(String telPatient) {
        this.telPatient = telPatient;
    }

    public String getNomPatient() {
        return this.nomPatient;
    }

    public void setNomPatient(String nomPatient) {
        this.nomPatient = nomPatient;
    }

    public Timestamp getDateConsultation() {
        return this.dateConsultation;
    }

    public void setDateConsultation(Timestamp dateConsultation) {
        this.dateConsultation = dateConsultation;
    }

    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getConsultations() {
        return this.consultations;
    }

    public void setConsultations(String consultations) {
        this.consultations = consultations;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Boolean getIsSoin() {
        return this.isSoin;
    }

    public void setIsSoin(Boolean isSoin) {
        this.isSoin = isSoin;
    }

    public Long getMontant() {
        return this.montant;
    }

    public void setMontant(Long montant) {
        this.montant = montant;
    }

    public Long getNombre() {
        return this.nombre;
    }

    public void setNombre(Long nombre) {
        this.nombre = nombre;
    }

    public Long getTotal() {
        return this.total;
    }

    public void setTotal(Long total) {
        this.total = total;
    }

    public Long getMedecin() {
        return this.medecin;
    }

    public void setMedecin(Long medecin) {
        this.medecin = medecin;
    }

    public String getNomPartenaire() {
        return this.nomPartenaire;
    }

    public void setNomPartenaire(String nomPartenaire) {
        this.nomPartenaire = nomPartenaire;
    }

    public Long getPartenaireId() {
        return this.partenaireId;
    }

    public void setPartenaireId(Long partenaireId) {
        this.partenaireId = partenaireId;
    }

    public Double getTauxCouverture() {
        return this.tauxCouverture;
    }

    public void setTauxCouverture(Double tauxCouverture) {
        this.tauxCouverture = tauxCouverture;
    }

    public Double getMontantPrisEnCharge() {
        return this.montantPrisEnCharge;
    }

    public void setMontantPrisEnCharge(Double montantPrisEnCharge) {
        this.montantPrisEnCharge = montantPrisEnCharge;
    }

    public Double getMontantNetAPayer() {
        return this.montantNetAPayer;
    }

    public void setMontantNetAPayer(Double montantNetAPayer) {
        this.montantNetAPayer = montantNetAPayer;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VSoins (");

        sb.append(id);
        sb.append(", ").append(libelle);
        sb.append(", ").append(consultation);
        sb.append(", ").append(numeroConsul);
        sb.append(", ").append(age);
        sb.append(", ").append(idPatient);
        sb.append(", ").append(telPatient);
        sb.append(", ").append(nomPatient);
        sb.append(", ").append(dateConsultation);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(consultations);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(isSoin);
        sb.append(", ").append(montant);
        sb.append(", ").append(nombre);
        sb.append(", ").append(total);
        sb.append(", ").append(medecin);
        sb.append(", ").append(nomPartenaire);
        sb.append(", ").append(partenaireId);
        sb.append(", ").append(tauxCouverture);
        sb.append(", ").append(montantPrisEnCharge);
        sb.append(", ").append(montantNetAPayer);

        sb.append(")");
        return sb.toString();
    }
}
