/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import javax.annotation.Generated;

import models.public_.tables.Params;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParamsRecord extends UpdatableRecordImpl<ParamsRecord> implements Record7<Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1985032745;

    /**
     * Setter for <code>public.params.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.params.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.params.nom_structure</code>.
     */
    public void setNomStructure(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.params.nom_structure</code>.
     */
    public String getNomStructure() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.params.adresse</code>.
     */
    public void setAdresse(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.params.adresse</code>.
     */
    public String getAdresse() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.params.tel</code>.
     */
    public void setTel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.params.tel</code>.
     */
    public String getTel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.params.adress</code>.
     */
    public void setAdress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.params.adress</code>.
     */
    public String getAdress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.params.logo</code>.
     */
    public void setLogo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.params.logo</code>.
     */
    public String getLogo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.params.info_bank</code>.
     */
    public void setInfoBank(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.params.info_bank</code>.
     */
    public String getInfoBank() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Params.PARAMS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Params.PARAMS.NOM_STRUCTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Params.PARAMS.ADRESSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Params.PARAMS.TEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Params.PARAMS.ADRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Params.PARAMS.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Params.PARAMS.INFO_BANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAdress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getInfoBank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomStructure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAdress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInfoBank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value2(String value) {
        setNomStructure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value3(String value) {
        setAdresse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value4(String value) {
        setTel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value5(String value) {
        setAdress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value6(String value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord value7(String value) {
        setInfoBank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParamsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParamsRecord
     */
    public ParamsRecord() {
        super(Params.PARAMS);
    }

    /**
     * Create a detached, initialised ParamsRecord
     */
    public ParamsRecord(Long id, String nomStructure, String adresse, String tel, String adress, String logo, String infoBank) {
        super(Params.PARAMS);

        set(0, id);
        set(1, nomStructure);
        set(2, adresse);
        set(3, tel);
        set(4, adress);
        set(5, logo);
        set(6, infoBank);
    }
}
