/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.public_.tables.VExamens;

import org.jooq.Field;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VExamensRecord extends TableRecordImpl<VExamensRecord> implements Record21<Long, String, String, String, Boolean, Timestamp, Long, String, Long, String, Double, Long, Double, Double, String, Long, Long, Long, String, String, Timestamp> {

    private static final long serialVersionUID = 2089540486;

    /**
     * Setter for <code>public.v_examens.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_examens.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_examens.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_examens.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_examens.resultat</code>.
     */
    public void setResultat(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_examens.resultat</code>.
     */
    public String getResultat() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_examens.observation</code>.
     */
    public void setObservation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_examens.observation</code>.
     */
    public String getObservation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_examens.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_examens.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.v_examens.when_done</code>.
     */
    public void setWhenDone(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_examens.when_done</code>.
     */
    public Timestamp getWhenDone() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.v_examens.consultation</code>.
     */
    public void setConsultation(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_examens.consultation</code>.
     */
    public Long getConsultation() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.v_examens.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_examens.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.v_examens.partenaire_id</code>.
     */
    public void setPartenaireId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_examens.partenaire_id</code>.
     */
    public Long getPartenaireId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.v_examens.nom_partenaire</code>.
     */
    public void setNomPartenaire(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_examens.nom_partenaire</code>.
     */
    public String getNomPartenaire() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.v_examens.taux_couverture</code>.
     */
    public void setTauxCouverture(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_examens.taux_couverture</code>.
     */
    public Double getTauxCouverture() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>public.v_examens.cout_examen</code>.
     */
    public void setCoutExamen(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_examens.cout_examen</code>.
     */
    public Long getCoutExamen() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.v_examens.montant_pris_en_charge</code>.
     */
    public void setMontantPrisEnCharge(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_examens.montant_pris_en_charge</code>.
     */
    public Double getMontantPrisEnCharge() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.v_examens.montant_net_a_payer</code>.
     */
    public void setMontantNetAPayer(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_examens.montant_net_a_payer</code>.
     */
    public Double getMontantNetAPayer() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.v_examens.numero_consul</code>.
     */
    public void setNumeroConsul(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_examens.numero_consul</code>.
     */
    public String getNumeroConsul() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.v_examens.medecin</code>.
     */
    public void setMedecin(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_examens.medecin</code>.
     */
    public Long getMedecin() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.v_examens.age</code>.
     */
    public void setAge(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.v_examens.age</code>.
     */
    public Long getAge() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>public.v_examens.id_patient</code>.
     */
    public void setIdPatient(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.v_examens.id_patient</code>.
     */
    public Long getIdPatient() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.v_examens.nom_patient</code>.
     */
    public void setNomPatient(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.v_examens.nom_patient</code>.
     */
    public String getNomPatient() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.v_examens.tel_patient</code>.
     */
    public void setTelPatient(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.v_examens.tel_patient</code>.
     */
    public String getTelPatient() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.v_examens.date_consultation</code>.
     */
    public void setDateConsultation(Timestamp value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.v_examens.date_consultation</code>.
     */
    public Timestamp getDateConsultation() {
        return (Timestamp) get(20);
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, String, String, Boolean, Timestamp, Long, String, Long, String, Double, Long, Double, Double, String, Long, Long, Long, String, String, Timestamp> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, String, String, Boolean, Timestamp, Long, String, Long, String, Double, Long, Double, Double, String, Long, Long, Long, String, String, Timestamp> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VExamens.V_EXAMENS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VExamens.V_EXAMENS.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VExamens.V_EXAMENS.RESULTAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VExamens.V_EXAMENS.OBSERVATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return VExamens.V_EXAMENS.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return VExamens.V_EXAMENS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return VExamens.V_EXAMENS.CONSULTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VExamens.V_EXAMENS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return VExamens.V_EXAMENS.PARTENAIRE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VExamens.V_EXAMENS.NOM_PARTENAIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field11() {
        return VExamens.V_EXAMENS.TAUX_COUVERTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return VExamens.V_EXAMENS.COUT_EXAMEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return VExamens.V_EXAMENS.MONTANT_PRIS_EN_CHARGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field14() {
        return VExamens.V_EXAMENS.MONTANT_NET_A_PAYER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VExamens.V_EXAMENS.NUMERO_CONSUL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return VExamens.V_EXAMENS.MEDECIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return VExamens.V_EXAMENS.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return VExamens.V_EXAMENS.ID_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return VExamens.V_EXAMENS.NOM_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return VExamens.V_EXAMENS.TEL_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field21() {
        return VExamens.V_EXAMENS.DATE_CONSULTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getResultat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getObservation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getPartenaireId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getNomPartenaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component11() {
        return getTauxCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getCoutExamen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component13() {
        return getMontantPrisEnCharge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component14() {
        return getMontantNetAPayer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getNumeroConsul();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getMedecin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component17() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component18() {
        return getIdPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getNomPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getTelPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component21() {
        return getDateConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getResultat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getObservation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getPartenaireId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNomPartenaire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value11() {
        return getTauxCouverture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getCoutExamen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getMontantPrisEnCharge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value14() {
        return getMontantNetAPayer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getNumeroConsul();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getMedecin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getIdPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getNomPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getTelPatient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value21() {
        return getDateConsultation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value3(String value) {
        setResultat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value4(String value) {
        setObservation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value5(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value6(Timestamp value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value7(Long value) {
        setConsultation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value8(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value9(Long value) {
        setPartenaireId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value10(String value) {
        setNomPartenaire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value11(Double value) {
        setTauxCouverture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value12(Long value) {
        setCoutExamen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value13(Double value) {
        setMontantPrisEnCharge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value14(Double value) {
        setMontantNetAPayer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value15(String value) {
        setNumeroConsul(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value16(Long value) {
        setMedecin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value17(Long value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value18(Long value) {
        setIdPatient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value19(String value) {
        setNomPatient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value20(String value) {
        setTelPatient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord value21(Timestamp value) {
        setDateConsultation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VExamensRecord values(Long value1, String value2, String value3, String value4, Boolean value5, Timestamp value6, Long value7, String value8, Long value9, String value10, Double value11, Long value12, Double value13, Double value14, String value15, Long value16, Long value17, Long value18, String value19, String value20, Timestamp value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VExamensRecord
     */
    public VExamensRecord() {
        super(VExamens.V_EXAMENS);
    }

    /**
     * Create a detached, initialised VExamensRecord
     */
    public VExamensRecord(Long id, String libelle, String resultat, String observation, Boolean isDeleted, Timestamp whenDone, Long consultation, String whoDone, Long partenaireId, String nomPartenaire, Double tauxCouverture, Long coutExamen, Double montantPrisEnCharge, Double montantNetAPayer, String numeroConsul, Long medecin, Long age, Long idPatient, String nomPatient, String telPatient, Timestamp dateConsultation) {
        super(VExamens.V_EXAMENS);

        set(0, id);
        set(1, libelle);
        set(2, resultat);
        set(3, observation);
        set(4, isDeleted);
        set(5, whenDone);
        set(6, consultation);
        set(7, whoDone);
        set(8, partenaireId);
        set(9, nomPartenaire);
        set(10, tauxCouverture);
        set(11, coutExamen);
        set(12, montantPrisEnCharge);
        set(13, montantNetAPayer);
        set(14, numeroConsul);
        set(15, medecin);
        set(16, age);
        set(17, idPatient);
        set(18, nomPatient);
        set(19, telPatient);
        set(20, dateConsultation);
    }
}
