play.filters {

  # Enabled filters are run automatically against Play.
  # CSRFFilter, AllowedHostFilters, and SecurityHeadersFilters are enabled by default.
  #enabled += filters.LoggingFilter

 
  hosts {
    # Allow requests to example.com, its subdomains, and localhost:9000.
   allowed = [".example.com", "localhost:9000", "192.168.43.108:9000"]
  }
}

play.db {
  # The combination of these two settings results in "db.default" as the
  # default JDBC pool:
  config = "db"
  default = "default"

  # Play uses HikariCP as the default connection pool.  You can override
  # settings by changing the prototype:
  prototype {
    # Sets a fixed JDBC connection pool size of 50
    hikaricp.minimumIdle = 5
    hikaricp.maximumPoolSize = 50
  }
}

play.http.secret.key = "01254789"
play.filters.headers.contentSecurityPolicy=null

#defined in milliseconds
application.session.timeout=1200000
