/*
 * This file is generated by jOOQ.
*/
package models.stock.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.stock.Stock;
import models.stock.tables.records.VArticleRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VArticle extends TableImpl<VArticleRecord> {

    private static final long serialVersionUID = -1936677006;

    /**
     * The reference instance of <code>stock.v_article</code>
     */
    public static final VArticle V_ARTICLE = new VArticle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VArticleRecord> getRecordType() {
        return VArticleRecord.class;
    }

    /**
     * The column <code>stock.v_article.id</code>.
     */
    public final TableField<VArticleRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_article.code_produit</code>.
     */
    public final TableField<VArticleRecord, String> CODE_PRODUIT = createField("code_produit", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>stock.v_article.libelle</code>.
     */
    public final TableField<VArticleRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_article.description</code>.
     */
    public final TableField<VArticleRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stock.v_article.prix_vente</code>.
     */
    public final TableField<VArticleRecord, Long> PRIX_VENTE = createField("prix_vente", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_article.quantite_disponible</code>.
     */
    public final TableField<VArticleRecord, Integer> QUANTITE_DISPONIBLE = createField("quantite_disponible", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stock.v_article.who_done</code>.
     */
    public final TableField<VArticleRecord, String> WHO_DONE = createField("who_done", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_article.when_done</code>.
     */
    public final TableField<VArticleRecord, Timestamp> WHEN_DONE = createField("when_done", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>stock.v_article.libelle_range</code>.
     */
    public final TableField<VArticleRecord, String> LIBELLE_RANGE = createField("libelle_range", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_article.id_range</code>.
     */
    public final TableField<VArticleRecord, Long> ID_RANGE = createField("id_range", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_article.who_done_range</code>.
     */
    public final TableField<VArticleRecord, String> WHO_DONE_RANGE = createField("who_done_range", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_article.p_qte</code>.
     */
    public final TableField<VArticleRecord, Long> P_QTE = createField("p_qte", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_article.produit_qte_id</code>.
     */
    public final TableField<VArticleRecord, Long> PRODUIT_QTE_ID = createField("produit_qte_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_article.be_transfert</code>.
     */
    public final TableField<VArticleRecord, Boolean> BE_TRANSFERT = createField("be_transfert", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>stock.v_article</code> table reference
     */
    public VArticle() {
        this(DSL.name("v_article"), null);
    }

    /**
     * Create an aliased <code>stock.v_article</code> table reference
     */
    public VArticle(String alias) {
        this(DSL.name(alias), V_ARTICLE);
    }

    /**
     * Create an aliased <code>stock.v_article</code> table reference
     */
    public VArticle(Name alias) {
        this(alias, V_ARTICLE);
    }

    private VArticle(Name alias, Table<VArticleRecord> aliased) {
        this(alias, aliased, null);
    }

    private VArticle(Name alias, Table<VArticleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stock.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VArticle as(String alias) {
        return new VArticle(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VArticle as(Name alias) {
        return new VArticle(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VArticle rename(String name) {
        return new VArticle(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VArticle rename(Name name) {
        return new VArticle(name, null);
    }
}
