/*
 * This file is generated by jOOQ.
*/
package models.stock.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.stock.Stock;
import models.stock.tables.records.VMouvementRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VMouvement extends TableImpl<VMouvementRecord> {

    private static final long serialVersionUID = 2077307203;

    /**
     * The reference instance of <code>stock.v_mouvement</code>
     */
    public static final VMouvement V_MOUVEMENT = new VMouvement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VMouvementRecord> getRecordType() {
        return VMouvementRecord.class;
    }

    /**
     * The column <code>stock.v_mouvement.id_article</code>.
     */
    public final TableField<VMouvementRecord, Long> ID_ARTICLE = createField("id_article", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_mouvement.code_produit</code>.
     */
    public final TableField<VMouvementRecord, String> CODE_PRODUIT = createField("code_produit", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>stock.v_mouvement.libelle</code>.
     */
    public final TableField<VMouvementRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_mouvement.description</code>.
     */
    public final TableField<VMouvementRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stock.v_mouvement.prix_vente</code>.
     */
    public final TableField<VMouvementRecord, Long> PRIX_VENTE = createField("prix_vente", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_mouvement.quantite_disponible</code>.
     */
    public final TableField<VMouvementRecord, Integer> QUANTITE_DISPONIBLE = createField("quantite_disponible", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stock.v_mouvement.who_done_article</code>.
     */
    public final TableField<VMouvementRecord, String> WHO_DONE_ARTICLE = createField("who_done_article", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_mouvement.when_done_article</code>.
     */
    public final TableField<VMouvementRecord, Timestamp> WHEN_DONE_ARTICLE = createField("when_done_article", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>stock.v_mouvement.id_m</code>.
     */
    public final TableField<VMouvementRecord, Long> ID_M = createField("id_m", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_mouvement.prix</code>.
     */
    public final TableField<VMouvementRecord, Long> PRIX = createField("prix", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_mouvement.quantite_m</code>.
     */
    public final TableField<VMouvementRecord, Integer> QUANTITE_M = createField("quantite_m", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stock.v_mouvement.operation</code>.
     */
    public final TableField<VMouvementRecord, String> OPERATION = createField("operation", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>stock.v_mouvement.who_done_m</code>.
     */
    public final TableField<VMouvementRecord, String> WHO_DONE_M = createField("who_done_m", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_mouvement.when_done_m</code>.
     */
    public final TableField<VMouvementRecord, Timestamp> WHEN_DONE_M = createField("when_done_m", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>stock.v_mouvement.facture_id</code>.
     */
    public final TableField<VMouvementRecord, Long> FACTURE_ID = createField("facture_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_mouvement.montant_mouvement</code>.
     */
    public final TableField<VMouvementRecord, Long> MONTANT_MOUVEMENT = createField("montant_mouvement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_mouvement.is_ok</code>.
     */
    public final TableField<VMouvementRecord, Boolean> IS_OK = createField("is_ok", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>stock.v_mouvement.libelle_range</code>.
     */
    public final TableField<VMouvementRecord, String> LIBELLE_RANGE = createField("libelle_range", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_mouvement.id_range</code>.
     */
    public final TableField<VMouvementRecord, Long> ID_RANGE = createField("id_range", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_mouvement.is_rejet</code>.
     */
    public final TableField<VMouvementRecord, Boolean> IS_REJET = createField("is_rejet", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>stock.v_mouvement.designation</code>.
     */
    public final TableField<VMouvementRecord, String> DESIGNATION = createField("designation", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * Create a <code>stock.v_mouvement</code> table reference
     */
    public VMouvement() {
        this(DSL.name("v_mouvement"), null);
    }

    /**
     * Create an aliased <code>stock.v_mouvement</code> table reference
     */
    public VMouvement(String alias) {
        this(DSL.name(alias), V_MOUVEMENT);
    }

    /**
     * Create an aliased <code>stock.v_mouvement</code> table reference
     */
    public VMouvement(Name alias) {
        this(alias, V_MOUVEMENT);
    }

    private VMouvement(Name alias, Table<VMouvementRecord> aliased) {
        this(alias, aliased, null);
    }

    private VMouvement(Name alias, Table<VMouvementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stock.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMouvement as(String alias) {
        return new VMouvement(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VMouvement as(Name alias) {
        return new VMouvement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VMouvement rename(String name) {
        return new VMouvement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VMouvement rename(Name name) {
        return new VMouvement(name, null);
    }
}
