/*
 * This file is generated by jOOQ.
*/
package models.stock.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.stock.Stock;
import models.stock.tables.records.VRejetRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VRejet extends TableImpl<VRejetRecord> {

    private static final long serialVersionUID = 1769410772;

    /**
     * The reference instance of <code>stock.v_rejet</code>
     */
    public static final VRejet V_REJET = new VRejet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VRejetRecord> getRecordType() {
        return VRejetRecord.class;
    }

    /**
     * The column <code>stock.v_rejet.id_article</code>.
     */
    public final TableField<VRejetRecord, Long> ID_ARTICLE = createField("id_article", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.code_produit</code>.
     */
    public final TableField<VRejetRecord, String> CODE_PRODUIT = createField("code_produit", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>stock.v_rejet.libelle</code>.
     */
    public final TableField<VRejetRecord, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_rejet.description</code>.
     */
    public final TableField<VRejetRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>stock.v_rejet.prix_vente</code>.
     */
    public final TableField<VRejetRecord, Long> PRIX_VENTE = createField("prix_vente", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.quantite_disponible</code>.
     */
    public final TableField<VRejetRecord, Integer> QUANTITE_DISPONIBLE = createField("quantite_disponible", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stock.v_rejet.who_done_article</code>.
     */
    public final TableField<VRejetRecord, String> WHO_DONE_ARTICLE = createField("who_done_article", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_rejet.when_done_article</code>.
     */
    public final TableField<VRejetRecord, Timestamp> WHEN_DONE_ARTICLE = createField("when_done_article", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>stock.v_rejet.id_m</code>.
     */
    public final TableField<VRejetRecord, Long> ID_M = createField("id_m", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.prix</code>.
     */
    public final TableField<VRejetRecord, Long> PRIX = createField("prix", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.quantite_m</code>.
     */
    public final TableField<VRejetRecord, Integer> QUANTITE_M = createField("quantite_m", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stock.v_rejet.operation</code>.
     */
    public final TableField<VRejetRecord, String> OPERATION = createField("operation", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>stock.v_rejet.who_done_m</code>.
     */
    public final TableField<VRejetRecord, String> WHO_DONE_M = createField("who_done_m", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_rejet.when_done_m</code>.
     */
    public final TableField<VRejetRecord, Timestamp> WHEN_DONE_M = createField("when_done_m", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>stock.v_rejet.facture_id</code>.
     */
    public final TableField<VRejetRecord, Long> FACTURE_ID = createField("facture_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.client</code>.
     */
    public final TableField<VRejetRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stock.v_rejet.when_done_f</code>.
     */
    public final TableField<VRejetRecord, Timestamp> WHEN_DONE_F = createField("when_done_f", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>stock.v_rejet.montantlettre</code>.
     */
    public final TableField<VRejetRecord, String> MONTANTLETTRE = createField("montantlettre", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stock.v_rejet.montantchiffre</code>.
     */
    public final TableField<VRejetRecord, Long> MONTANTCHIFFRE = createField("montantchiffre", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.when_imprime</code>.
     */
    public final TableField<VRejetRecord, Timestamp> WHEN_IMPRIME = createField("when_imprime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>stock.v_rejet.montant_mouvement</code>.
     */
    public final TableField<VRejetRecord, Long> MONTANT_MOUVEMENT = createField("montant_mouvement", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.libelle_range</code>.
     */
    public final TableField<VRejetRecord, String> LIBELLE_RANGE = createField("libelle_range", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>stock.v_rejet.id_range</code>.
     */
    public final TableField<VRejetRecord, Long> ID_RANGE = createField("id_range", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.is_rejet</code>.
     */
    public final TableField<VRejetRecord, Boolean> IS_REJET = createField("is_rejet", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>stock.v_rejet.montant_client</code>.
     */
    public final TableField<VRejetRecord, Long> MONTANT_CLIENT = createField("montant_client", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stock.v_rejet.montant_remis</code>.
     */
    public final TableField<VRejetRecord, Long> MONTANT_REMIS = createField("montant_remis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>stock.v_rejet</code> table reference
     */
    public VRejet() {
        this(DSL.name("v_rejet"), null);
    }

    /**
     * Create an aliased <code>stock.v_rejet</code> table reference
     */
    public VRejet(String alias) {
        this(DSL.name(alias), V_REJET);
    }

    /**
     * Create an aliased <code>stock.v_rejet</code> table reference
     */
    public VRejet(Name alias) {
        this(alias, V_REJET);
    }

    private VRejet(Name alias, Table<VRejetRecord> aliased) {
        this(alias, aliased, null);
    }

    private VRejet(Name alias, Table<VRejetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Stock.STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRejet as(String alias) {
        return new VRejet(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VRejet as(Name alias) {
        return new VRejet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VRejet rename(String name) {
        return new VRejet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VRejet rename(Name name) {
        return new VRejet(name, null);
    }
}
