/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Confi implements Serializable {

    private static final long serialVersionUID = 200775365;

    private Long   id;
    private String url;
    private String driver;
    private String username;
    private String password;
    private String template;
    private String tempPdf;

    public Confi() {}

    public Confi(Confi value) {
        this.id = value.id;
        this.url = value.url;
        this.driver = value.driver;
        this.username = value.username;
        this.password = value.password;
        this.template = value.template;
        this.tempPdf = value.tempPdf;
    }

    public Confi(
        Long   id,
        String url,
        String driver,
        String username,
        String password,
        String template,
        String tempPdf
    ) {
        this.id = id;
        this.url = url;
        this.driver = driver;
        this.username = username;
        this.password = password;
        this.template = template;
        this.tempPdf = tempPdf;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDriver() {
        return this.driver;
    }

    public void setDriver(String driver) {
        this.driver = driver;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getTemplate() {
        return this.template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public String getTempPdf() {
        return this.tempPdf;
    }

    public void setTempPdf(String tempPdf) {
        this.tempPdf = tempPdf;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Confi (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(driver);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(template);
        sb.append(", ").append(tempPdf);

        sb.append(")");
        return sb.toString();
    }
}
