/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VArticle implements Serializable {

    private static final long serialVersionUID = 378689594;

    private Long      id;
    private String    codeProduit;
    private String    libelle;
    private String    description;
    private Long      prixVente;
    private Integer   quantiteDisponible;
    private String    whoDone;
    private Timestamp whenDone;
    private String    libelleRange;
    private Long      idRange;
    private String    whoDoneRange;
    private Long      pQte;
    private Long      produitQteId;
    private Boolean   beTransfert;

    public VArticle() {}

    public VArticle(VArticle value) {
        this.id = value.id;
        this.codeProduit = value.codeProduit;
        this.libelle = value.libelle;
        this.description = value.description;
        this.prixVente = value.prixVente;
        this.quantiteDisponible = value.quantiteDisponible;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.libelleRange = value.libelleRange;
        this.idRange = value.idRange;
        this.whoDoneRange = value.whoDoneRange;
        this.pQte = value.pQte;
        this.produitQteId = value.produitQteId;
        this.beTransfert = value.beTransfert;
    }

    public VArticle(
        Long      id,
        String    codeProduit,
        String    libelle,
        String    description,
        Long      prixVente,
        Integer   quantiteDisponible,
        String    whoDone,
        Timestamp whenDone,
        String    libelleRange,
        Long      idRange,
        String    whoDoneRange,
        Long      pQte,
        Long      produitQteId,
        Boolean   beTransfert
    ) {
        this.id = id;
        this.codeProduit = codeProduit;
        this.libelle = libelle;
        this.description = description;
        this.prixVente = prixVente;
        this.quantiteDisponible = quantiteDisponible;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.libelleRange = libelleRange;
        this.idRange = idRange;
        this.whoDoneRange = whoDoneRange;
        this.pQte = pQte;
        this.produitQteId = produitQteId;
        this.beTransfert = beTransfert;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodeProduit() {
        return this.codeProduit;
    }

    public void setCodeProduit(String codeProduit) {
        this.codeProduit = codeProduit;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getPrixVente() {
        return this.prixVente;
    }

    public void setPrixVente(Long prixVente) {
        this.prixVente = prixVente;
    }

    public Integer getQuantiteDisponible() {
        return this.quantiteDisponible;
    }

    public void setQuantiteDisponible(Integer quantiteDisponible) {
        this.quantiteDisponible = quantiteDisponible;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public Timestamp getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(Timestamp whenDone) {
        this.whenDone = whenDone;
    }

    public String getLibelleRange() {
        return this.libelleRange;
    }

    public void setLibelleRange(String libelleRange) {
        this.libelleRange = libelleRange;
    }

    public Long getIdRange() {
        return this.idRange;
    }

    public void setIdRange(Long idRange) {
        this.idRange = idRange;
    }

    public String getWhoDoneRange() {
        return this.whoDoneRange;
    }

    public void setWhoDoneRange(String whoDoneRange) {
        this.whoDoneRange = whoDoneRange;
    }

    public Long getPQte() {
        return this.pQte;
    }

    public void setPQte(Long pQte) {
        this.pQte = pQte;
    }

    public Long getProduitQteId() {
        return this.produitQteId;
    }

    public void setProduitQteId(Long produitQteId) {
        this.produitQteId = produitQteId;
    }

    public Boolean getBeTransfert() {
        return this.beTransfert;
    }

    public void setBeTransfert(Boolean beTransfert) {
        this.beTransfert = beTransfert;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VArticle (");

        sb.append(id);
        sb.append(", ").append(codeProduit);
        sb.append(", ").append(libelle);
        sb.append(", ").append(description);
        sb.append(", ").append(prixVente);
        sb.append(", ").append(quantiteDisponible);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(libelleRange);
        sb.append(", ").append(idRange);
        sb.append(", ").append(whoDoneRange);
        sb.append(", ").append(pQte);
        sb.append(", ").append(produitQteId);
        sb.append(", ").append(beTransfert);

        sb.append(")");
        return sb.toString();
    }
}
