/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VMouvement implements Serializable {

    private static final long serialVersionUID = 777823754;

    private Long      idArticle;
    private String    codeProduit;
    private String    libelle;
    private String    description;
    private Long      prixVente;
    private Integer   quantiteDisponible;
    private String    whoDoneArticle;
    private Timestamp whenDoneArticle;
    private Long      idM;
    private Long      prix;
    private Integer   quantiteM;
    private String    operation;
    private String    whoDoneM;
    private Timestamp whenDoneM;
    private Long      factureId;
    private Long      montantMouvement;
    private Boolean   isOk;
    private String    libelleRange;
    private Long      idRange;
    private Boolean   isRejet;
    private String    designation;

    public VMouvement() {}

    public VMouvement(VMouvement value) {
        this.idArticle = value.idArticle;
        this.codeProduit = value.codeProduit;
        this.libelle = value.libelle;
        this.description = value.description;
        this.prixVente = value.prixVente;
        this.quantiteDisponible = value.quantiteDisponible;
        this.whoDoneArticle = value.whoDoneArticle;
        this.whenDoneArticle = value.whenDoneArticle;
        this.idM = value.idM;
        this.prix = value.prix;
        this.quantiteM = value.quantiteM;
        this.operation = value.operation;
        this.whoDoneM = value.whoDoneM;
        this.whenDoneM = value.whenDoneM;
        this.factureId = value.factureId;
        this.montantMouvement = value.montantMouvement;
        this.isOk = value.isOk;
        this.libelleRange = value.libelleRange;
        this.idRange = value.idRange;
        this.isRejet = value.isRejet;
        this.designation = value.designation;
    }

    public VMouvement(
        Long      idArticle,
        String    codeProduit,
        String    libelle,
        String    description,
        Long      prixVente,
        Integer   quantiteDisponible,
        String    whoDoneArticle,
        Timestamp whenDoneArticle,
        Long      idM,
        Long      prix,
        Integer   quantiteM,
        String    operation,
        String    whoDoneM,
        Timestamp whenDoneM,
        Long      factureId,
        Long      montantMouvement,
        Boolean   isOk,
        String    libelleRange,
        Long      idRange,
        Boolean   isRejet,
        String    designation
    ) {
        this.idArticle = idArticle;
        this.codeProduit = codeProduit;
        this.libelle = libelle;
        this.description = description;
        this.prixVente = prixVente;
        this.quantiteDisponible = quantiteDisponible;
        this.whoDoneArticle = whoDoneArticle;
        this.whenDoneArticle = whenDoneArticle;
        this.idM = idM;
        this.prix = prix;
        this.quantiteM = quantiteM;
        this.operation = operation;
        this.whoDoneM = whoDoneM;
        this.whenDoneM = whenDoneM;
        this.factureId = factureId;
        this.montantMouvement = montantMouvement;
        this.isOk = isOk;
        this.libelleRange = libelleRange;
        this.idRange = idRange;
        this.isRejet = isRejet;
        this.designation = designation;
    }

    public Long getIdArticle() {
        return this.idArticle;
    }

    public void setIdArticle(Long idArticle) {
        this.idArticle = idArticle;
    }

    public String getCodeProduit() {
        return this.codeProduit;
    }

    public void setCodeProduit(String codeProduit) {
        this.codeProduit = codeProduit;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getPrixVente() {
        return this.prixVente;
    }

    public void setPrixVente(Long prixVente) {
        this.prixVente = prixVente;
    }

    public Integer getQuantiteDisponible() {
        return this.quantiteDisponible;
    }

    public void setQuantiteDisponible(Integer quantiteDisponible) {
        this.quantiteDisponible = quantiteDisponible;
    }

    public String getWhoDoneArticle() {
        return this.whoDoneArticle;
    }

    public void setWhoDoneArticle(String whoDoneArticle) {
        this.whoDoneArticle = whoDoneArticle;
    }

    public Timestamp getWhenDoneArticle() {
        return this.whenDoneArticle;
    }

    public void setWhenDoneArticle(Timestamp whenDoneArticle) {
        this.whenDoneArticle = whenDoneArticle;
    }

    public Long getIdM() {
        return this.idM;
    }

    public void setIdM(Long idM) {
        this.idM = idM;
    }

    public Long getPrix() {
        return this.prix;
    }

    public void setPrix(Long prix) {
        this.prix = prix;
    }

    public Integer getQuantiteM() {
        return this.quantiteM;
    }

    public void setQuantiteM(Integer quantiteM) {
        this.quantiteM = quantiteM;
    }

    public String getOperation() {
        return this.operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

    public String getWhoDoneM() {
        return this.whoDoneM;
    }

    public void setWhoDoneM(String whoDoneM) {
        this.whoDoneM = whoDoneM;
    }

    public Timestamp getWhenDoneM() {
        return this.whenDoneM;
    }

    public void setWhenDoneM(Timestamp whenDoneM) {
        this.whenDoneM = whenDoneM;
    }

    public Long getFactureId() {
        return this.factureId;
    }

    public void setFactureId(Long factureId) {
        this.factureId = factureId;
    }

    public Long getMontantMouvement() {
        return this.montantMouvement;
    }

    public void setMontantMouvement(Long montantMouvement) {
        this.montantMouvement = montantMouvement;
    }

    public Boolean getIsOk() {
        return this.isOk;
    }

    public void setIsOk(Boolean isOk) {
        this.isOk = isOk;
    }

    public String getLibelleRange() {
        return this.libelleRange;
    }

    public void setLibelleRange(String libelleRange) {
        this.libelleRange = libelleRange;
    }

    public Long getIdRange() {
        return this.idRange;
    }

    public void setIdRange(Long idRange) {
        this.idRange = idRange;
    }

    public Boolean getIsRejet() {
        return this.isRejet;
    }

    public void setIsRejet(Boolean isRejet) {
        this.isRejet = isRejet;
    }

    public String getDesignation() {
        return this.designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VMouvement (");

        sb.append(idArticle);
        sb.append(", ").append(codeProduit);
        sb.append(", ").append(libelle);
        sb.append(", ").append(description);
        sb.append(", ").append(prixVente);
        sb.append(", ").append(quantiteDisponible);
        sb.append(", ").append(whoDoneArticle);
        sb.append(", ").append(whenDoneArticle);
        sb.append(", ").append(idM);
        sb.append(", ").append(prix);
        sb.append(", ").append(quantiteM);
        sb.append(", ").append(operation);
        sb.append(", ").append(whoDoneM);
        sb.append(", ").append(whenDoneM);
        sb.append(", ").append(factureId);
        sb.append(", ").append(montantMouvement);
        sb.append(", ").append(isOk);
        sb.append(", ").append(libelleRange);
        sb.append(", ").append(idRange);
        sb.append(", ").append(isRejet);
        sb.append(", ").append(designation);

        sb.append(")");
        return sb.toString();
    }
}
