/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import models.stock.tables.Confi;
import models.stock.tables.records.ConfiRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfiDao extends DAOImpl<ConfiRecord, models.stock.tables.pojos.Confi, Long> {

    /**
     * Create a new ConfiDao without any configuration
     */
    public ConfiDao() {
        super(Confi.CONFI, models.stock.tables.pojos.Confi.class);
    }

    /**
     * Create a new ConfiDao with an attached configuration
     */
    public ConfiDao(Configuration configuration) {
        super(Confi.CONFI, models.stock.tables.pojos.Confi.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.stock.tables.pojos.Confi object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.stock.tables.pojos.Confi> fetchById(Long... values) {
        return fetch(Confi.CONFI.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.stock.tables.pojos.Confi fetchOneById(Long value) {
        return fetchOne(Confi.CONFI.ID, value);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<models.stock.tables.pojos.Confi> fetchByUrl(String... values) {
        return fetch(Confi.CONFI.URL, values);
    }

    /**
     * Fetch records that have <code>driver IN (values)</code>
     */
    public List<models.stock.tables.pojos.Confi> fetchByDriver(String... values) {
        return fetch(Confi.CONFI.DRIVER, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<models.stock.tables.pojos.Confi> fetchByUsername(String... values) {
        return fetch(Confi.CONFI.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<models.stock.tables.pojos.Confi> fetchByPassword(String... values) {
        return fetch(Confi.CONFI.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>template IN (values)</code>
     */
    public List<models.stock.tables.pojos.Confi> fetchByTemplate(String... values) {
        return fetch(Confi.CONFI.TEMPLATE, values);
    }

    /**
     * Fetch records that have <code>temp_pdf IN (values)</code>
     */
    public List<models.stock.tables.pojos.Confi> fetchByTempPdf(String... values) {
        return fetch(Confi.CONFI.TEMP_PDF, values);
    }
}
