/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.stock.tables.Facture;
import models.stock.tables.records.FactureRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FactureDao extends DAOImpl<FactureRecord, models.stock.tables.pojos.Facture, Long> {

    /**
     * Create a new FactureDao without any configuration
     */
    public FactureDao() {
        super(Facture.FACTURE, models.stock.tables.pojos.Facture.class);
    }

    /**
     * Create a new FactureDao with an attached configuration
     */
    public FactureDao(Configuration configuration) {
        super(Facture.FACTURE, models.stock.tables.pojos.Facture.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.stock.tables.pojos.Facture object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchById(Long... values) {
        return fetch(Facture.FACTURE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.stock.tables.pojos.Facture fetchOneById(Long value) {
        return fetchOne(Facture.FACTURE.ID, value);
    }

    /**
     * Fetch records that have <code>client IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByClient(String... values) {
        return fetch(Facture.FACTURE.CLIENT, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByWhenDone(Timestamp... values) {
        return fetch(Facture.FACTURE.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>montantlettre IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByMontantlettre(String... values) {
        return fetch(Facture.FACTURE.MONTANTLETTRE, values);
    }

    /**
     * Fetch records that have <code>montantchiffre IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByMontantchiffre(Long... values) {
        return fetch(Facture.FACTURE.MONTANTCHIFFRE, values);
    }

    /**
     * Fetch records that have <code>when_imprime IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByWhenImprime(Timestamp... values) {
        return fetch(Facture.FACTURE.WHEN_IMPRIME, values);
    }

    /**
     * Fetch records that have <code>montant_client IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByMontantClient(Long... values) {
        return fetch(Facture.FACTURE.MONTANT_CLIENT, values);
    }

    /**
     * Fetch records that have <code>montant_remi IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByMontantRemi(Long... values) {
        return fetch(Facture.FACTURE.MONTANT_REMI, values);
    }

    /**
     * Fetch records that have <code>is_transfert IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByIsTransfert(Boolean... values) {
        return fetch(Facture.FACTURE.IS_TRANSFERT, values);
    }

    /**
     * Fetch records that have <code>service_id IN (values)</code>
     */
    public List<models.stock.tables.pojos.Facture> fetchByServiceId(Integer... values) {
        return fetch(Facture.FACTURE.SERVICE_ID, values);
    }
}
