/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import models.stock.tables.Rangee;
import models.stock.tables.records.RangeeRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RangeeDao extends DAOImpl<RangeeRecord, models.stock.tables.pojos.Rangee, Long> {

    /**
     * Create a new RangeeDao without any configuration
     */
    public RangeeDao() {
        super(Rangee.RANGEE, models.stock.tables.pojos.Rangee.class);
    }

    /**
     * Create a new RangeeDao with an attached configuration
     */
    public RangeeDao(Configuration configuration) {
        super(Rangee.RANGEE, models.stock.tables.pojos.Rangee.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.stock.tables.pojos.Rangee object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.stock.tables.pojos.Rangee> fetchById(Long... values) {
        return fetch(Rangee.RANGEE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.stock.tables.pojos.Rangee fetchOneById(Long value) {
        return fetchOne(Rangee.RANGEE.ID, value);
    }

    /**
     * Fetch records that have <code>libelle IN (values)</code>
     */
    public List<models.stock.tables.pojos.Rangee> fetchByLibelle(String... values) {
        return fetch(Rangee.RANGEE.LIBELLE, values);
    }

    /**
     * Fetch a unique record that has <code>libelle = value</code>
     */
    public models.stock.tables.pojos.Rangee fetchOneByLibelle(String value) {
        return fetchOne(Rangee.RANGEE.LIBELLE, value);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.stock.tables.pojos.Rangee> fetchByWhoDone(String... values) {
        return fetch(Rangee.RANGEE.WHO_DONE, values);
    }
}
