/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.MedecinPatient;
import models.public_.tables.records.MedecinPatientRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedecinPatientDao extends DAOImpl<MedecinPatientRecord, models.public_.tables.pojos.MedecinPatient, Long> {

    /**
     * Create a new MedecinPatientDao without any configuration
     */
    public MedecinPatientDao() {
        super(MedecinPatient.MEDECIN_PATIENT, models.public_.tables.pojos.MedecinPatient.class);
    }

    /**
     * Create a new MedecinPatientDao with an attached configuration
     */
    public MedecinPatientDao(Configuration configuration) {
        super(MedecinPatient.MEDECIN_PATIENT, models.public_.tables.pojos.MedecinPatient.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.MedecinPatient object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.public_.tables.pojos.MedecinPatient> fetchById(Long... values) {
        return fetch(MedecinPatient.MEDECIN_PATIENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.public_.tables.pojos.MedecinPatient fetchOneById(Long value) {
        return fetchOne(MedecinPatient.MEDECIN_PATIENT.ID, value);
    }

    /**
     * Fetch records that have <code>patient_id IN (values)</code>
     */
    public List<models.public_.tables.pojos.MedecinPatient> fetchByPatientId(Long... values) {
        return fetch(MedecinPatient.MEDECIN_PATIENT.PATIENT_ID, values);
    }

    /**
     * Fetch records that have <code>medecin_id IN (values)</code>
     */
    public List<models.public_.tables.pojos.MedecinPatient> fetchByMedecinId(Long... values) {
        return fetch(MedecinPatient.MEDECIN_PATIENT.MEDECIN_ID, values);
    }
}
