/*
 * This file is generated by jOOQ.
*/
package models.public_.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import models.public_.tables.Rendezvous;
import models.public_.tables.records.RendezvousRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RendezvousDao extends DAOImpl<RendezvousRecord, models.public_.tables.pojos.Rendezvous, Long> {

    /**
     * Create a new RendezvousDao without any configuration
     */
    public RendezvousDao() {
        super(Rendezvous.RENDEZVOUS, models.public_.tables.pojos.Rendezvous.class);
    }

    /**
     * Create a new RendezvousDao with an attached configuration
     */
    public RendezvousDao(Configuration configuration) {
        super(Rendezvous.RENDEZVOUS, models.public_.tables.pojos.Rendezvous.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(models.public_.tables.pojos.Rendezvous object) {
        return object.getIdRdv();
    }

    /**
     * Fetch records that have <code>id_rdv IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByIdRdv(Long... values) {
        return fetch(Rendezvous.RENDEZVOUS.ID_RDV, values);
    }

    /**
     * Fetch a unique record that has <code>id_rdv = value</code>
     */
    public models.public_.tables.pojos.Rendezvous fetchOneByIdRdv(Long value) {
        return fetchOne(Rendezvous.RENDEZVOUS.ID_RDV, value);
    }

    /**
     * Fetch records that have <code>nom_patient IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByNomPatient(String... values) {
        return fetch(Rendezvous.RENDEZVOUS.NOM_PATIENT, values);
    }

    /**
     * Fetch records that have <code>num_tel IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByNumTel(String... values) {
        return fetch(Rendezvous.RENDEZVOUS.NUM_TEL, values);
    }

    /**
     * Fetch records that have <code>motif_rdv IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByMotifRdv(String... values) {
        return fetch(Rendezvous.RENDEZVOUS.MOTIF_RDV, values);
    }

    /**
     * Fetch records that have <code>date_rdv IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByDateRdv(Timestamp... values) {
        return fetch(Rendezvous.RENDEZVOUS.DATE_RDV, values);
    }

    /**
     * Fetch records that have <code>who_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByWhoDone(String... values) {
        return fetch(Rendezvous.RENDEZVOUS.WHO_DONE, values);
    }

    /**
     * Fetch records that have <code>when_done IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByWhenDone(Timestamp... values) {
        return fetch(Rendezvous.RENDEZVOUS.WHEN_DONE, values);
    }

    /**
     * Fetch records that have <code>on_deleted IN (values)</code>
     */
    public List<models.public_.tables.pojos.Rendezvous> fetchByOnDeleted(Boolean... values) {
        return fetch(Rendezvous.RENDEZVOUS.ON_DELETED, values);
    }
}
