/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.records;


import javax.annotation.Generated;

import models.stock.tables.Rangee;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RangeeRecord extends UpdatableRecordImpl<RangeeRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1718101634;

    /**
     * Setter for <code>stock.rangee.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stock.rangee.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stock.rangee.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stock.rangee.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stock.rangee.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stock.rangee.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Rangee.RANGEE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Rangee.RANGEE.LIBELLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Rangee.RANGEE.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RangeeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RangeeRecord value2(String value) {
        setLibelle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RangeeRecord value3(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RangeeRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RangeeRecord
     */
    public RangeeRecord() {
        super(Rangee.RANGEE);
    }

    /**
     * Create a detached, initialised RangeeRecord
     */
    public RangeeRecord(Long id, String libelle, String whoDone) {
        super(Rangee.RANGEE);

        set(0, id);
        set(1, libelle);
        set(2, whoDone);
    }
}
