/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.records;


import javax.annotation.Generated;

import models.stock.tables.Services;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicesRecord extends UpdatableRecordImpl<ServicesRecord> implements Record5<Integer, String, String, String, Boolean> {

    private static final long serialVersionUID = 559264237;

    /**
     * Setter for <code>stock.services.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stock.services.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stock.services.nom_s</code>.
     */
    public void setNomS(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stock.services.nom_s</code>.
     */
    public String getNomS() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stock.services.adresse_s</code>.
     */
    public void setAdresseS(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stock.services.adresse_s</code>.
     */
    public String getAdresseS() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stock.services.telephone_s</code>.
     */
    public void setTelephoneS(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stock.services.telephone_s</code>.
     */
    public String getTelephoneS() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stock.services.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>stock.services.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Services.SERVICES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Services.SERVICES.NOM_S;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Services.SERVICES.ADRESSE_S;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Services.SERVICES.TELEPHONE_S;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Services.SERVICES.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNomS();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAdresseS();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTelephoneS();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomS();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAdresseS();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelephoneS();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value2(String value) {
        setNomS(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value3(String value) {
        setAdresseS(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value4(String value) {
        setTelephoneS(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord value5(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServicesRecord values(Integer value1, String value2, String value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicesRecord
     */
    public ServicesRecord() {
        super(Services.SERVICES);
    }

    /**
     * Create a detached, initialised ServicesRecord
     */
    public ServicesRecord(Integer id, String nomS, String adresseS, String telephoneS, Boolean isDeleted) {
        super(Services.SERVICES);

        set(0, id);
        set(1, nomS);
        set(2, adresseS);
        set(3, telephoneS);
        set(4, isDeleted);
    }
}
