/*
 * This file is generated by jOOQ.
*/
package models.stock.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import models.stock.tables.VAchat;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAchatRecord extends TableRecordImpl<VAchatRecord> {

    private static final long serialVersionUID = -56607172;

    /**
     * Setter for <code>stock.v_achat.id_article</code>.
     */
    public void setIdArticle(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stock.v_achat.id_article</code>.
     */
    public Long getIdArticle() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stock.v_achat.libelle</code>.
     */
    public void setLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stock.v_achat.libelle</code>.
     */
    public String getLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stock.v_achat.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stock.v_achat.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stock.v_achat.prix_vente</code>.
     */
    public void setPrixVente(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>stock.v_achat.prix_vente</code>.
     */
    public Long getPrixVente() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>stock.v_achat.quantite_disponible</code>.
     */
    public void setQuantiteDisponible(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>stock.v_achat.quantite_disponible</code>.
     */
    public Integer getQuantiteDisponible() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>stock.v_achat.who_done_article</code>.
     */
    public void setWhoDoneArticle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stock.v_achat.who_done_article</code>.
     */
    public String getWhoDoneArticle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stock.v_achat.when_done_article</code>.
     */
    public void setWhenDoneArticle(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>stock.v_achat.when_done_article</code>.
     */
    public Timestamp getWhenDoneArticle() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>stock.v_achat.id_m</code>.
     */
    public void setIdM(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>stock.v_achat.id_m</code>.
     */
    public Long getIdM() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>stock.v_achat.prix</code>.
     */
    public void setPrix(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>stock.v_achat.prix</code>.
     */
    public Long getPrix() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>stock.v_achat.quantite_m</code>.
     */
    public void setQuantiteM(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>stock.v_achat.quantite_m</code>.
     */
    public Integer getQuantiteM() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>stock.v_achat.operation</code>.
     */
    public void setOperation(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stock.v_achat.operation</code>.
     */
    public String getOperation() {
        return (String) get(10);
    }

    /**
     * Setter for <code>stock.v_achat.who_done_m</code>.
     */
    public void setWhoDoneM(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>stock.v_achat.who_done_m</code>.
     */
    public String getWhoDoneM() {
        return (String) get(11);
    }

    /**
     * Setter for <code>stock.v_achat.when_done_m</code>.
     */
    public void setWhenDoneM(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>stock.v_achat.when_done_m</code>.
     */
    public Timestamp getWhenDoneM() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>stock.v_achat.facture_id</code>.
     */
    public void setFactureId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>stock.v_achat.facture_id</code>.
     */
    public Long getFactureId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>stock.v_achat.client</code>.
     */
    public void setClient(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>stock.v_achat.client</code>.
     */
    public String getClient() {
        return (String) get(14);
    }

    /**
     * Setter for <code>stock.v_achat.when_done_f</code>.
     */
    public void setWhenDoneF(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>stock.v_achat.when_done_f</code>.
     */
    public Timestamp getWhenDoneF() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>stock.v_achat.montantlettre</code>.
     */
    public void setMontantlettre(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>stock.v_achat.montantlettre</code>.
     */
    public String getMontantlettre() {
        return (String) get(16);
    }

    /**
     * Setter for <code>stock.v_achat.montantchiffre</code>.
     */
    public void setMontantchiffre(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>stock.v_achat.montantchiffre</code>.
     */
    public Long getMontantchiffre() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>stock.v_achat.when_imprime</code>.
     */
    public void setWhenImprime(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>stock.v_achat.when_imprime</code>.
     */
    public Timestamp getWhenImprime() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>stock.v_achat.montant_mouvement</code>.
     */
    public void setMontantMouvement(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>stock.v_achat.montant_mouvement</code>.
     */
    public Long getMontantMouvement() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>stock.v_achat.libelle_range</code>.
     */
    public void setLibelleRange(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>stock.v_achat.libelle_range</code>.
     */
    public String getLibelleRange() {
        return (String) get(20);
    }

    /**
     * Setter for <code>stock.v_achat.id_range</code>.
     */
    public void setIdRange(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>stock.v_achat.id_range</code>.
     */
    public Long getIdRange() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>stock.v_achat.is_rejet</code>.
     */
    public void setIsRejet(Boolean value) {
        set(22, value);
    }

    /**
     * Getter for <code>stock.v_achat.is_rejet</code>.
     */
    public Boolean getIsRejet() {
        return (Boolean) get(22);
    }

    /**
     * Setter for <code>stock.v_achat.montant_client</code>.
     */
    public void setMontantClient(Long value) {
        set(23, value);
    }

    /**
     * Getter for <code>stock.v_achat.montant_client</code>.
     */
    public Long getMontantClient() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>stock.v_achat.montant_remis</code>.
     */
    public void setMontantRemis(Long value) {
        set(24, value);
    }

    /**
     * Getter for <code>stock.v_achat.montant_remis</code>.
     */
    public Long getMontantRemis() {
        return (Long) get(24);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VAchatRecord
     */
    public VAchatRecord() {
        super(VAchat.V_ACHAT);
    }

    /**
     * Create a detached, initialised VAchatRecord
     */
    public VAchatRecord(Long idArticle, String libelle, String description, Long prixVente, Integer quantiteDisponible, String whoDoneArticle, Timestamp whenDoneArticle, Long idM, Long prix, Integer quantiteM, String operation, String whoDoneM, Timestamp whenDoneM, Long factureId, String client, Timestamp whenDoneF, String montantlettre, Long montantchiffre, Timestamp whenImprime, Long montantMouvement, String libelleRange, Long idRange, Boolean isRejet, Long montantClient, Long montantRemis) {
        super(VAchat.V_ACHAT);

        set(0, idArticle);
        set(1, libelle);
        set(2, description);
        set(3, prixVente);
        set(4, quantiteDisponible);
        set(5, whoDoneArticle);
        set(6, whenDoneArticle);
        set(7, idM);
        set(8, prix);
        set(9, quantiteM);
        set(10, operation);
        set(11, whoDoneM);
        set(12, whenDoneM);
        set(13, factureId);
        set(14, client);
        set(15, whenDoneF);
        set(16, montantlettre);
        set(17, montantchiffre);
        set(18, whenImprime);
        set(19, montantMouvement);
        set(20, libelleRange);
        set(21, idRange);
        set(22, isRejet);
        set(23, montantClient);
        set(24, montantRemis);
    }
}
