/*
 * This file is generated by jOOQ.
*/
package models.stock;


import javax.annotation.Generated;

import models.stock.tables.Article;
import models.stock.tables.Confi;
import models.stock.tables.Facture;
import models.stock.tables.Fournisseur;
import models.stock.tables.Mouvement;
import models.stock.tables.Rangee;
import models.stock.tables.Services;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>stock</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLES_LIBELLE_KEY = Indexes0.ARTICLES_LIBELLE_KEY;
    public static final Index ARTICLES_PKEY = Indexes0.ARTICLES_PKEY;
    public static final Index CONFI_PKEY = Indexes0.CONFI_PKEY;
    public static final Index FACTURES_PKEY = Indexes0.FACTURES_PKEY;
    public static final Index FOURNISSEUR_PKEY = Indexes0.FOURNISSEUR_PKEY;
    public static final Index MOUVEMENT_PKEY = Indexes0.MOUVEMENT_PKEY;
    public static final Index RANGE_PKEY = Indexes0.RANGE_PKEY;
    public static final Index RANGEE_LIBELLE_KEY = Indexes0.RANGEE_LIBELLE_KEY;
    public static final Index SERVICE_PKEY = Indexes0.SERVICE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ARTICLES_LIBELLE_KEY = createIndex("articles_libelle_key", Article.ARTICLE, new OrderField[] { Article.ARTICLE.LIBELLE }, true);
        public static Index ARTICLES_PKEY = createIndex("articles_pkey", Article.ARTICLE, new OrderField[] { Article.ARTICLE.ID }, true);
        public static Index CONFI_PKEY = createIndex("confi_pkey", Confi.CONFI, new OrderField[] { Confi.CONFI.ID }, true);
        public static Index FACTURES_PKEY = createIndex("factures_pkey", Facture.FACTURE, new OrderField[] { Facture.FACTURE.ID }, true);
        public static Index FOURNISSEUR_PKEY = createIndex("fournisseur_pkey", Fournisseur.FOURNISSEUR, new OrderField[] { Fournisseur.FOURNISSEUR.ID }, true);
        public static Index MOUVEMENT_PKEY = createIndex("Mouvement_pkey", Mouvement.MOUVEMENT, new OrderField[] { Mouvement.MOUVEMENT.ID }, true);
        public static Index RANGE_PKEY = createIndex("range_pkey", Rangee.RANGEE, new OrderField[] { Rangee.RANGEE.ID }, true);
        public static Index RANGEE_LIBELLE_KEY = createIndex("rangee_libelle_key", Rangee.RANGEE, new OrderField[] { Rangee.RANGEE.LIBELLE }, true);
        public static Index SERVICE_PKEY = createIndex("service_pkey", Services.SERVICES, new OrderField[] { Services.SERVICES.ID }, true);
    }
}
