/*
 * This file is generated by jOOQ.
*/
package models.stock;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.DefaultCatalog;
import models.stock.tables.Article;
import models.stock.tables.Confi;
import models.stock.tables.Facture;
import models.stock.tables.Fournisseur;
import models.stock.tables.Mouvement;
import models.stock.tables.Rangee;
import models.stock.tables.Role;
import models.stock.tables.Services;
import models.stock.tables.VAchat;
import models.stock.tables.VArticle;
import models.stock.tables.VFacture;
import models.stock.tables.VFactureConsulster;
import models.stock.tables.VMouvement;
import models.stock.tables.VRejet;
import models.stock.tables.VVente;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stock extends SchemaImpl {

    private static final long serialVersionUID = -2020714093;

    /**
     * The reference instance of <code>stock</code>
     */
    public static final Stock STOCK = new Stock();

    /**
     * The table <code>stock.article</code>.
     */
    public final Article ARTICLE = models.stock.tables.Article.ARTICLE;

    /**
     * The table <code>stock.confi</code>.
     */
    public final Confi CONFI = models.stock.tables.Confi.CONFI;

    /**
     * The table <code>stock.facture</code>.
     */
    public final Facture FACTURE = models.stock.tables.Facture.FACTURE;

    /**
     * The table <code>stock.fournisseur</code>.
     */
    public final Fournisseur FOURNISSEUR = models.stock.tables.Fournisseur.FOURNISSEUR;

    /**
     * The table <code>stock.mouvement</code>.
     */
    public final Mouvement MOUVEMENT = models.stock.tables.Mouvement.MOUVEMENT;

    /**
     * The table <code>stock.rangee</code>.
     */
    public final Rangee RANGEE = models.stock.tables.Rangee.RANGEE;

    /**
     * The table <code>stock.role</code>.
     */
    public final Role ROLE = models.stock.tables.Role.ROLE;

    /**
     * The table <code>stock.services</code>.
     */
    public final Services SERVICES = models.stock.tables.Services.SERVICES;

    /**
     * The table <code>stock.v_achat</code>.
     */
    public final VAchat V_ACHAT = models.stock.tables.VAchat.V_ACHAT;

    /**
     * The table <code>stock.v_article</code>.
     */
    public final VArticle V_ARTICLE = models.stock.tables.VArticle.V_ARTICLE;

    /**
     * The table <code>stock.v_facture</code>.
     */
    public final VFacture V_FACTURE = models.stock.tables.VFacture.V_FACTURE;

    /**
     * The table <code>stock.v_facture_consulster</code>.
     */
    public final VFactureConsulster V_FACTURE_CONSULSTER = models.stock.tables.VFactureConsulster.V_FACTURE_CONSULSTER;

    /**
     * The table <code>stock.v_mouvement</code>.
     */
    public final VMouvement V_MOUVEMENT = models.stock.tables.VMouvement.V_MOUVEMENT;

    /**
     * The table <code>stock.v_rejet</code>.
     */
    public final VRejet V_REJET = models.stock.tables.VRejet.V_REJET;

    /**
     * The table <code>stock.v_vente</code>.
     */
    public final VVente V_VENTE = models.stock.tables.VVente.V_VENTE;

    /**
     * No further instances allowed
     */
    private Stock() {
        super("stock", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ARTICLE_ID_SEQ,
            Sequences.CONFI_ID_SEQ,
            Sequences.FACTURE_ID_SEQ,
            Sequences.FOURNISSEUR_ID_SEQ,
            Sequences.MOUVEMENT_ID_SEQ,
            Sequences.RANGE_ID_SEQ,
            Sequences.ROLE_IDROLE_SEQ,
            Sequences.SERVICES_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            Confi.CONFI,
            Facture.FACTURE,
            Fournisseur.FOURNISSEUR,
            Mouvement.MOUVEMENT,
            Rangee.RANGEE,
            Role.ROLE,
            Services.SERVICES,
            VAchat.V_ACHAT,
            VArticle.V_ARTICLE,
            VFacture.V_FACTURE,
            VFactureConsulster.V_FACTURE_CONSULSTER,
            VMouvement.V_MOUVEMENT,
            VRejet.V_REJET,
            VVente.V_VENTE);
    }
}
