/*
 * This file is generated by jOOQ.
*/
package models.stock;


import javax.annotation.Generated;

import models.stock.tables.Article;
import models.stock.tables.Confi;
import models.stock.tables.Facture;
import models.stock.tables.Fournisseur;
import models.stock.tables.Mouvement;
import models.stock.tables.Rangee;
import models.stock.tables.Role;
import models.stock.tables.Services;
import models.stock.tables.VAchat;
import models.stock.tables.VArticle;
import models.stock.tables.VFacture;
import models.stock.tables.VFactureConsulster;
import models.stock.tables.VMouvement;
import models.stock.tables.VRejet;
import models.stock.tables.VVente;


/**
 * Convenience access to all tables in stock
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stock.article</code>.
     */
    public static final Article ARTICLE = models.stock.tables.Article.ARTICLE;

    /**
     * The table <code>stock.confi</code>.
     */
    public static final Confi CONFI = models.stock.tables.Confi.CONFI;

    /**
     * The table <code>stock.facture</code>.
     */
    public static final Facture FACTURE = models.stock.tables.Facture.FACTURE;

    /**
     * The table <code>stock.fournisseur</code>.
     */
    public static final Fournisseur FOURNISSEUR = models.stock.tables.Fournisseur.FOURNISSEUR;

    /**
     * The table <code>stock.mouvement</code>.
     */
    public static final Mouvement MOUVEMENT = models.stock.tables.Mouvement.MOUVEMENT;

    /**
     * The table <code>stock.rangee</code>.
     */
    public static final Rangee RANGEE = models.stock.tables.Rangee.RANGEE;

    /**
     * The table <code>stock.role</code>.
     */
    public static final Role ROLE = models.stock.tables.Role.ROLE;

    /**
     * The table <code>stock.services</code>.
     */
    public static final Services SERVICES = models.stock.tables.Services.SERVICES;

    /**
     * The table <code>stock.v_achat</code>.
     */
    public static final VAchat V_ACHAT = models.stock.tables.VAchat.V_ACHAT;

    /**
     * The table <code>stock.v_article</code>.
     */
    public static final VArticle V_ARTICLE = models.stock.tables.VArticle.V_ARTICLE;

    /**
     * The table <code>stock.v_facture</code>.
     */
    public static final VFacture V_FACTURE = models.stock.tables.VFacture.V_FACTURE;

    /**
     * The table <code>stock.v_facture_consulster</code>.
     */
    public static final VFactureConsulster V_FACTURE_CONSULSTER = models.stock.tables.VFactureConsulster.V_FACTURE_CONSULSTER;

    /**
     * The table <code>stock.v_mouvement</code>.
     */
    public static final VMouvement V_MOUVEMENT = models.stock.tables.VMouvement.V_MOUVEMENT;

    /**
     * The table <code>stock.v_rejet</code>.
     */
    public static final VRejet V_REJET = models.stock.tables.VRejet.V_REJET;

    /**
     * The table <code>stock.v_vente</code>.
     */
    public static final VVente V_VENTE = models.stock.tables.VVente.V_VENTE;
}
